CHRONOS-LoRa: src/chronos.cpp File Reference
chronos.cpp File Reference
#include "chronos.hpp"
#include "magick/colorspace.h"
#include "magick/common.h"
#include "magick/constitute.h"
#include "magick/error.h"
#include "magick/image.h"
#include "magick/magick.h"
#include "magick/pixel_cache.h"
#include "magick/resize.h"
#include "wand/magick_wand.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
static Quantum chronos_clamp_quantum (double v)
Clamp GraphicsMagick's Quantum value from signed to unisgned limit.
static void chronos_process_image (const char *in_filename, const char *out_filename, Chronos_Process_Function fn)
Process the Image in GraphicsMagick context.
void chronos_rgb_to_grayscale (const char *in_filename, const char *out_filename)
Convert an image's colorspace, without changing file format, from RGB to Grayscale.
void chronos_rgb_to_ycocg (char **argv)
static Image * chronos_convert_to_ppm_op (Image *image, ExceptionInfo *exception_info)
The operation to convert to PPM.
void chronos_convert_to_ppm (const char *in_filename, const char *out_filename)
Convert any GraphicsMagick supported image format to PPM image format.
void chronos_resize_image (const char *in_filename, const char *out_filename)
void chronos_scale_image (const char *in_filename, const char *out_filename)
Function Documentation
chronos_clamp_quantum()
static Quantum chronos_clamp_quantum (double v) static
Clamp GraphicsMagick's Quantum value from signed to unisgned limit.
Parameters
v -> the double value
Referenced by chronos_rgb_to_ycocg().
chronos_convert_to_ppm()
void chronos_convert_to_ppm (const char * in_filename, const char * out_filename)
Convert any GraphicsMagick supported image format to PPM image format.
Parameters
*in_filename The input's filename
*out_filename The output's filename (must include .PPM or .ppm)
chronos_convert_to_ppm_op()
static Image * chronos_convert_to_ppm_op (Image * image, ExceptionInfo * exception_info) static
The operation to convert to PPM.
Parameters
*image -> The image object
*exception_info -> The exception's information
Referenced by chronos_convert_to_ppm().
chronos_process_image()
static void chronos_process_image (const char * in_filename, const char * out_filename, Chronos_Process_Function fn) static
Process the Image in GraphicsMagick context.
Parameters
*in_filename -> The input's filename
*out_filename -> The output's filename
Referenced by chronos_convert_to_ppm().
chronos_resize_image()
void chronos_resize_image (const char * in_filename, const char * out_filename)
chronos_rgb_to_grayscale()
void chronos_rgb_to_grayscale (const char * in_filename, const char * out_filename)
Convert an image's colorspace, without changing file format, from RGB to Grayscale.
Parameters
*in_filename The input's filename
*out_filename The output's filename
chronos_rgb_to_ycocg()
void chronos_rgb_to_ycocg (char ** argv)
chronos_scale_image()
void chronos_scale_image (const char * in_filename, const char * out_filename)