CHRONOS-LoRa: detail::uint128 Class Reference
detail::uint128 Class Reference
#include <format.h>
Public Member Functions
constexpr uint128 (uint64_t hi, uint64_t lo)
constexpr uint128 (uint64_t value=0)
constexpr auto high () const noexcept -> uint64_t
constexpr auto low () const noexcept -> uint64_t
template<typename T , FMT_ENABLE_IF(std::is_integral< T >::value) >
constexpr operator T () const
FMT_CONSTEXPR auto operator>> (int shift) const -> uint128
FMT_CONSTEXPR auto operator<< (int shift) const -> uint128
FMT_CONSTEXPR auto operator>>= (int shift) -> uint128 &
FMT_CONSTEXPR void operator+= (uint128 n)
FMT_CONSTEXPR void operator&= (uint128 n)
FMT_CONSTEXPR20 auto operator+= (uint64_t n) noexcept -> uint128 &
Private Attributes
uint64_t lo_
uint64_t hi_
Friends
constexpr auto operator== (const uint128 &lhs, const uint128 &rhs) -> bool
constexpr auto operator!= (const uint128 &lhs, const uint128 &rhs) -> bool
constexpr auto operator> (const uint128 &lhs, const uint128 &rhs) -> bool
constexpr auto operator| (const uint128 &lhs, const uint128 &rhs) -> uint128
constexpr auto operator& (const uint128 &lhs, const uint128 &rhs) -> uint128
FMT_CONSTEXPR auto operator+ (const uint128 &lhs, const uint128 &rhs) -> uint128
FMT_CONSTEXPR auto operator* (const uint128 &lhs, uint32_t rhs) -> uint128
constexpr auto operator- (const uint128 &lhs, uint64_t rhs) -> uint128
Constructor & Destructor Documentation
uint128() [1/2]
constexpr detail::uint128::uint128 (uint64_t hi, uint64_t lo) inline constexpr
Referenced by operator<<(), operator>>(), detail::umul128(), and detail::dragonbox::umul192_lower128().
uint128() [2/2]
constexpr detail::uint128::uint128 (uint64_t value = 0) inline constexpr
Member Function Documentation
high()
constexpr auto detail::uint128::high () const -> uint64_t inline constexpr noexcept
Referenced by detail::dragonbox::cache_accessor< double >::compute_delta(), detail::dragonbox::cache_accessor< double >::compute_left_endpoint_for_shorter_interval_case(), detail::dragonbox::cache_accessor< double >::compute_mul(), detail::dragonbox::cache_accessor< double >::compute_mul_parity(), detail::dragonbox::cache_accessor< double >::compute_right_endpoint_for_shorter_interval_case(), detail::dragonbox::cache_accessor< double >::compute_round_up_for_shorter_interval_case(), detail::format_float(), detail::dragonbox::umul192_lower128(), and detail::dragonbox::umul192_upper128().
low()
constexpr auto detail::uint128::low () const -> uint64_t inline constexpr noexcept
Referenced by detail::dragonbox::cache_accessor< double >::compute_mul(), detail::dragonbox::cache_accessor< double >::compute_mul_parity(), detail::format_float(), detail::dragonbox::umul192_lower128(), and detail::dragonbox::umul192_upper128().
operator T()
template<typename T , FMT_ENABLE_IF(std::is_integral< T >::value) > constexpr detail::uint128::operator T () const inline explicit constexpr
operator&=()
FMT_CONSTEXPR void detail::uint128::operator&= (uint128 n) inline
operator+=() [1/2]
FMT_CONSTEXPR void detail::uint128::operator+= (uint128 n) inline
operator+=() [2/2]
FMT_CONSTEXPR20 auto detail::uint128::operator+= (uint64_t n) -> uint128& inline noexcept
Referenced by detail::dragonbox::umul192_upper128().
operator<<()
FMT_CONSTEXPR auto detail::uint128::operator<< (int shift) const -> uint128 inline
Referenced by operator<<().
operator>>()
FMT_CONSTEXPR auto detail::uint128::operator>> (int shift) const -> uint128 inline
Referenced by operator>>(), and operator>>=().
operator>>=()
FMT_CONSTEXPR auto detail::uint128::operator>>= (int shift) -> uint128& inline
Friends And Related Symbol Documentation
operator!=
constexpr auto operator!= (const uint128 & lhs, const uint128 & rhs) -> bool friend
operator&
constexpr auto operator& (const uint128 & lhs, const uint128 & rhs) -> uint128 friend
operator*
FMT_CONSTEXPR auto operator* (const uint128 & lhs, uint32_t rhs) -> uint128 friend
operator+
FMT_CONSTEXPR auto operator+ (const uint128 & lhs, const uint128 & rhs) -> uint128 friend
operator-
constexpr auto operator- (const uint128 & lhs, uint64_t rhs) -> uint128 friend
operator==
constexpr auto operator== (const uint128 & lhs, const uint128 & rhs) -> bool friend
operator>
constexpr auto operator> (const uint128 & lhs, const uint128 & rhs) -> bool friend
operator|
constexpr auto operator| (const uint128 & lhs, const uint128 & rhs) -> uint128 friend
Member Data Documentation
hi_
uint64_t detail::uint128::hi_ private
Referenced by high(), operator&=(), operator+=(), operator+=(), operator<<(), operator>>(), uint128(), and uint128().
lo_
uint64_t detail::uint128::lo_ private
Referenced by low(), operator T(), operator&=(), operator+=(), operator+=(), operator<<(), operator>>(), uint128(), and uint128().
The documentation for this class was generated from the following file:
thirdparty/fmt/include/fmt/format.h