CHRONOS-LoRa: cxxopts::Value Class Reference
cxxopts::Value Class Reference abstract
#include <cxxopts.hpp>
Public Member Functions
virtual ~Value ()=default
virtual std::shared_ptr< Value > clone () const =0
virtual void add (const std::string &text) const =0
virtual void parse (const std::string &text) const =0
virtual void parse () const =0
virtual bool has_default () const =0
virtual bool is_container () const =0
virtual bool has_implicit () const =0
virtual std::string get_default_value () const =0
virtual std::string get_implicit_value () const =0
virtual std::shared_ptr< Value > default_value (const std::string &value)=0
virtual std::shared_ptr< Value > implicit_value (const std::string &value)=0
virtual std::shared_ptr< Value > no_implicit_value ()=0
virtual bool is_boolean () const =0
Constructor & Destructor Documentation
~Value()
virtual cxxopts::Value::~Value () virtual default
Member Function Documentation
add()
virtual void cxxopts::Value::add (const std::string & text) const pure virtual
Implemented in cxxopts::values::abstract_value< T >, and cxxopts::values::abstract_value< bool >.
Referenced by cxxopts::OptionValue::add().
clone()
virtual std::shared_ptr< Value > cxxopts::Value::clone () const pure virtual
Implemented in cxxopts::values::standard_value< T >, and cxxopts::values::standard_value< bool >.
Referenced by cxxopts::OptionDetails::make_storage(), and cxxopts::OptionDetails::OptionDetails().
default_value()
virtual std::shared_ptr< Value > cxxopts::Value::default_value (const std::string & value) pure virtual
Implemented in cxxopts::values::abstract_value< T >, and cxxopts::values::abstract_value< bool >.
Referenced by main().
get_default_value()
virtual std::string cxxopts::Value::get_default_value () const pure virtual
Implemented in cxxopts::values::abstract_value< T >, and cxxopts::values::abstract_value< bool >.
Referenced by cxxopts::Options::add_option(), and cxxopts::OptionParser::parse_default().
get_implicit_value()
virtual std::string cxxopts::Value::get_implicit_value () const pure virtual
Implemented in cxxopts::values::abstract_value< T >, and cxxopts::values::abstract_value< bool >.
Referenced by cxxopts::Options::add_option(), cxxopts::OptionParser::checked_parse_arg(), and cxxopts::OptionParser::parse().
has_default()
virtual bool cxxopts::Value::has_default () const pure virtual
Implemented in cxxopts::values::abstract_value< T >, and cxxopts::values::abstract_value< bool >.
Referenced by cxxopts::Options::add_option(), and cxxopts::OptionParser::parse().
has_implicit()
virtual bool cxxopts::Value::has_implicit () const pure virtual
Implemented in cxxopts::values::abstract_value< T >, and cxxopts::values::abstract_value< bool >.
Referenced by cxxopts::Options::add_option(), cxxopts::OptionParser::checked_parse_arg(), and cxxopts::OptionParser::parse().
implicit_value()
virtual std::shared_ptr< Value > cxxopts::Value::implicit_value (const std::string & value) pure virtual
Implemented in cxxopts::values::abstract_value< T >, and cxxopts::values::abstract_value< bool >.
is_boolean()
virtual bool cxxopts::Value::is_boolean () const pure virtual
Implemented in cxxopts::values::abstract_value< T >, and cxxopts::values::abstract_value< bool >.
Referenced by cxxopts::Options::add_option().
is_container()
virtual bool cxxopts::Value::is_container () const pure virtual
Implemented in cxxopts::values::abstract_value< T >, and cxxopts::values::abstract_value< bool >.
Referenced by cxxopts::Options::add_option(), and cxxopts::OptionParser::consume_positional().
no_implicit_value()
virtual std::shared_ptr< Value > cxxopts::Value::no_implicit_value () pure virtual
Implemented in cxxopts::values::abstract_value< T >, and cxxopts::values::abstract_value< bool >.
parse() [1/2]
virtual void cxxopts::Value::parse () const pure virtual
Implemented in cxxopts::values::abstract_value< T >, and cxxopts::values::abstract_value< bool >.
Referenced by cxxopts::OptionValue::parse_default().
parse() [2/2]
virtual void cxxopts::Value::parse (const std::string & text) const pure virtual
Implemented in cxxopts::values::abstract_value< T >, and cxxopts::values::abstract_value< bool >.
Referenced by cxxopts::OptionValue::parse().
The documentation for this class was generated from the following file:
thirdparty/libcxxopts-dev/cxxopts.hpp