CHRONOS-LoRa: cxxopts::OptionDetails Class Reference
cxxopts::OptionDetails Class Reference
#include <cxxopts.hpp>
Public Member Functions
OptionDetails (std::string short_, OptionNames long_, String desc, std::shared_ptr< const Value > val)
OptionDetails (const OptionDetails &rhs)
OptionDetails (OptionDetails &&rhs)=default
CXXOPTS_NODISCARD const String & description () const
CXXOPTS_NODISCARD const Value & value () const
CXXOPTS_NODISCARD std::shared_ptr< Value > make_storage () const
CXXOPTS_NODISCARD const std::string & short_name () const
CXXOPTS_NODISCARD const std::string & first_long_name () const
CXXOPTS_NODISCARD const std::string & essential_name () const
CXXOPTS_NODISCARD const OptionNames & long_names () const
std::size_t hash () const
Private Attributes
std::string m_short {}
OptionNames m_long {}
String m_desc {}
std::shared_ptr< const Value > m_value {}
int m_count
std::size_t m_hash {}
Constructor & Destructor Documentation
OptionDetails() [1/3]
cxxopts::OptionDetails::OptionDetails (std::string short_, OptionNames long_, String desc, std::shared_ptr< const Value > val) inline
OptionDetails() [2/3]
cxxopts::OptionDetails::OptionDetails (const OptionDetails & rhs) inline
OptionDetails() [3/3]
cxxopts::OptionDetails::OptionDetails (OptionDetails && rhs) default
Member Function Documentation
description()
CXXOPTS_NODISCARD const String & cxxopts::OptionDetails::description () const inline
essential_name()
CXXOPTS_NODISCARD const std::string & cxxopts::OptionDetails::essential_name () const inline
Referenced by cxxopts::OptionParser::add_to_option(), cxxopts::OptionParser::parse_default(), and cxxopts::OptionParser::parse_option().
first_long_name()
CXXOPTS_NODISCARD const std::string & cxxopts::OptionDetails::first_long_name () const inline
Referenced by OptionDetails().
hash()
std::size_t cxxopts::OptionDetails::hash () const inline
Referenced by cxxopts::OptionParser::add_to_option(), cxxopts::OptionParser::consume_positional(), cxxopts::OptionParser::finalise_aliases(), cxxopts::OptionParser::parse(), cxxopts::OptionParser::parse_default(), cxxopts::OptionParser::parse_no_value(), and cxxopts::OptionParser::parse_option().
long_names()
CXXOPTS_NODISCARD const OptionNames & cxxopts::OptionDetails::long_names () const inline
Referenced by cxxopts::OptionValue::add(), cxxopts::OptionParser::finalise_aliases(), cxxopts::OptionValue::parse(), cxxopts::OptionValue::parse_default(), and cxxopts::OptionValue::parse_no_value().
make_storage()
CXXOPTS_NODISCARD std::shared_ptr< Value > cxxopts::OptionDetails::make_storage () const inline
Referenced by cxxopts::OptionValue::ensure_value().
short_name()
CXXOPTS_NODISCARD const std::string & cxxopts::OptionDetails::short_name () const inline
Referenced by cxxopts::OptionParser::finalise_aliases().
value()
CXXOPTS_NODISCARD const Value & cxxopts::OptionDetails::value () const inline
Referenced by cxxopts::OptionParser::checked_parse_arg(), cxxopts::OptionParser::consume_positional(), cxxopts::OptionParser::parse(), and cxxopts::OptionParser::parse_default().
Member Data Documentation
m_count
int cxxopts::OptionDetails::m_count private
Referenced by OptionDetails(), and OptionDetails().
m_desc
String cxxopts::OptionDetails::m_desc {} private
Referenced by description(), OptionDetails(), and OptionDetails().
m_hash
std::size_t cxxopts::OptionDetails::m_hash {} private
Referenced by hash(), and OptionDetails().
m_long
OptionNames cxxopts::OptionDetails::m_long {} private
Referenced by essential_name(), first_long_name(), long_names(), and OptionDetails().
m_short
std::string cxxopts::OptionDetails::m_short {} private
Referenced by essential_name(), OptionDetails(), and short_name().
m_value
std::shared_ptr<const Value> cxxopts::OptionDetails::m_value {} private
Referenced by make_storage(), OptionDetails(), OptionDetails(), and value().
The documentation for this class was generated from the following file:
thirdparty/libcxxopts-dev/cxxopts.hpp