CHRONOS-LoRa: detail::printf_arg_formatter< Char > Class Template Reference
detail::printf_arg_formatter< Char > Class Template Reference
#include <printf.h>
Public Member Functions
printf_arg_formatter (basic_appender< Char > iter, format_specs &s, context_type &ctx)
void operator() (monostate value)
template<typename T , FMT_ENABLE_IF(detail::is_integral< T >::value) >
void operator() (T value)
template<typename T , FMT_ENABLE_IF(std::is_floating_point< T >::value) >
void operator() (T value)
void operator() (const char *value)
void operator() (const wchar_t *value)
void operator() (basic_string_view< Char > value)
void operator() (const void *value)
void operator() (typename basic_format_arg< context_type >::handle handle)
Public Member Functions inherited from detail::arg_formatter< Char >
template<typename T , FMT_ENABLE_IF(is_builtin< T >::value) >
FMT_CONSTEXPR FMT_INLINE void operator() (T value)
template<typename T , FMT_ENABLE_IF(!is_builtin< T >::value) >
void operator() (T)
void operator() (typename basic_format_arg< buffered_context< Char > >::handle)
Private Types
using base = arg_formatter< Char >
using context_type = basic_printf_context< Char >
Private Member Functions
void write_null_pointer (bool is_string=false)
template<typename T >
void write (T value)
Private Attributes
context_type & context_
Additional Inherited Members
Public Attributes inherited from detail::arg_formatter< Char >
basic_appender< Char > out
const format_specs & specs
FMT_NO_UNIQUE_ADDRESS locale_ref locale
Member Typedef Documentation
base
template<typename Char > using detail::printf_arg_formatter< Char >::base = arg_formatter<Char> private
context_type
template<typename Char > using detail::printf_arg_formatter< Char >::context_type = basic_printf_context<Char> private
Constructor & Destructor Documentation
printf_arg_formatter()
template<typename Char > detail::printf_arg_formatter< Char >::printf_arg_formatter (basic_appender< Char > iter, format_specs & s, context_type & ctx) inline
Member Function Documentation
operator()() [1/8]
template<typename Char > void detail::printf_arg_formatter< Char >::operator() (basic_string_view< Char > value) inline
operator()() [2/8]
template<typename Char > void detail::printf_arg_formatter< Char >::operator() (const char * value) inline
operator()() [3/8]
template<typename Char > void detail::printf_arg_formatter< Char >::operator() (const void * value) inline
operator()() [4/8]
template<typename Char > void detail::printf_arg_formatter< Char >::operator() (const wchar_t * value) inline
operator()() [5/8]
template<typename Char > void detail::printf_arg_formatter< Char >::operator() (monostate value) inline
operator()() [6/8]
template<typename Char > template<typename T , FMT_ENABLE_IF(detail::is_integral< T >::value) > void detail::printf_arg_formatter< Char >::operator() (T value) inline
operator()() [7/8]
template<typename Char > template<typename T , FMT_ENABLE_IF(std::is_floating_point< T >::value) > void detail::printf_arg_formatter< Char >::operator() (T value) inline
operator()() [8/8]
template<typename Char > void detail::printf_arg_formatter< Char >::operator() (typename basic_format_arg< context_type >::handle handle) inline
write()
template<typename Char > template<typename T > void detail::printf_arg_formatter< Char >::write (T value) inline private
write_null_pointer()
template<typename Char > void detail::printf_arg_formatter< Char >::write_null_pointer (bool is_string = false) inline private
Referenced by detail::printf_arg_formatter< Char >::operator()(), detail::printf_arg_formatter< Char >::operator()(), and detail::printf_arg_formatter< Char >::operator()().
Member Data Documentation
context_
template<typename Char > context_type& detail::printf_arg_formatter< Char >::context_ private
Referenced by detail::printf_arg_formatter< Char >::operator()(), and detail::printf_arg_formatter< Char >::printf_arg_formatter().
The documentation for this class was generated from the following file:
thirdparty/fmt/include/fmt/printf.h