CHRONOS-LoRa: basic_memory_buffer< T, SIZE, Allocator > Class Template Reference
basic_memory_buffer< T, SIZE, Allocator > Class Template Reference
#include <format.h>
Public Types
using value_type = T
using const_reference = const T &
Public Types inherited from detail::buffer< T >
using value_type = T
using const_reference = const T &
Public Member Functions
FMT_CONSTEXPR basic_memory_buffer (const Allocator &alloc=Allocator())
FMT_CONSTEXPR20 ~basic_memory_buffer ()
FMT_CONSTEXPR20 basic_memory_buffer (basic_memory_buffer &&other) noexcept
auto operator= (basic_memory_buffer &&other) noexcept -> basic_memory_buffer &
Moves the content of the other basic_memory_buffer object to this one.
auto get_allocator () const -> Allocator
FMT_CONSTEXPR void resize (size_t count)
void reserve (size_t new_capacity)
Increases the buffer capacity to new_capacity.
template<typename ContiguousRange >
FMT_CONSTEXPR20 void append (const ContiguousRange &range)
Public Member Functions inherited from detail::buffer< T >
buffer (const buffer &)=delete
void operator= (const buffer &)=delete
auto begin () noexcept -> T *
auto end () noexcept -> T *
auto begin () const noexcept -> const T *
auto end () const noexcept -> const T *
constexpr auto size () const noexcept -> size_t
Returns the size of this buffer.
constexpr auto capacity () const noexcept -> size_t
Returns the capacity of this buffer.
FMT_CONSTEXPR auto data () noexcept -> T *
Returns a pointer to the buffer data (not null-terminated).
FMT_CONSTEXPR auto data () const noexcept -> const T *
FMT_CONSTEXPR void clear ()
Clears this buffer.
FMT_CONSTEXPR void try_resize (size_t count)
FMT_CONSTEXPR void try_reserve (size_t new_capacity)
FMT_CONSTEXPR void push_back (const T &value)
template<typename U >
FMT_CONSTEXPR20 void append (const U *begin, const U *end)
Appends data to the end of the buffer.
template<typename Idx >
FMT_CONSTEXPR auto operator[] (Idx index) -> T &
template<typename Idx >
constexpr auto operator[] (Idx index) const -> const T &
Private Member Functions
FMT_CONSTEXPR20 void deallocate ()
template<typename Alloc = Allocator, FMT_ENABLE_IF(std::allocator_traits< Alloc >:: propagate_on_container_move_assignment::value) >
FMT_CONSTEXPR20 auto move_alloc (basic_memory_buffer &other) -> bool
template<typename Alloc = Allocator, FMT_ENABLE_IF(!std::allocator_traits< Alloc >:: propagate_on_container_move_assignment::value) >
FMT_CONSTEXPR20 auto move_alloc (basic_memory_buffer &other) -> bool
FMT_CONSTEXPR20 void move (basic_memory_buffer &other)
Static Private Member Functions
static FMT_CONSTEXPR20 void grow (detail::buffer< T > &buf, size_t size)
Private Attributes
T store_ [SIZE]
FMT_NO_UNIQUE_ADDRESS Allocator alloc_
Additional Inherited Members
Protected Member Functions inherited from detail::buffer< T >
FMT_CONSTEXPR buffer (grow_fun grow, size_t sz) noexcept
constexpr buffer (grow_fun grow, T *p=nullptr, size_t sz=0, size_t cap=0) noexcept
FMT_CONSTEXPR20 ~buffer ()=default
buffer (buffer &&)=default
FMT_CONSTEXPR void set (T *buf_data, size_t buf_capacity) noexcept
Sets the buffer data and capacity.
Detailed Description
template<typename T, size_t SIZE = inline_buffer_size, typename Allocator = detail::allocator<T>>
class basic_memory_buffer< T, SIZE, Allocator >
A dynamically growing memory buffer for trivially copyable/constructible types with the first SIZE elements stored in the object itself. Most commonly used via the memory_buffer alias for char.
Example:
auto out = fmt::memory_buffer();
fmt::format_to(std::back_inserter(out), "The answer is {}.", 42);
This will append "The answer is 42." to out. The buffer content can be converted to std::string with to_string(out).
Member Typedef Documentation
const_reference
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = detail::allocator<T>> using basic_memory_buffer< T, SIZE, Allocator >::const_reference = const T&
value_type
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = detail::allocator<T>> using basic_memory_buffer< T, SIZE, Allocator >::value_type = T
Constructor & Destructor Documentation
basic_memory_buffer() [1/2]
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = detail::allocator<T>> FMT_CONSTEXPR basic_memory_buffer< T, SIZE, Allocator >::basic_memory_buffer (const Allocator & alloc = Allocator()) inline explicit
Referenced by detail::digit_grouping< Char >::apply(), formatter< std::error_code >::format(), detail::tm_writer< OutputIt, Char, Duration >::on_second(), detail::duration_formatter< Char, Rep, Period >::on_second(), print(), print(), vformat(), vformat(), vformat(), vformat(), vprint(), vprint(), vprint(), vprint(), vprint_buffered(), vprintln(), detail::write_int(), and detail::write_significand().
~basic_memory_buffer()
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = detail::allocator<T>> FMT_CONSTEXPR20 basic_memory_buffer< T, SIZE, Allocator >::~basic_memory_buffer () inline
basic_memory_buffer() [2/2]
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = detail::allocator<T>> FMT_CONSTEXPR20 basic_memory_buffer< T, SIZE, Allocator >::basic_memory_buffer (basic_memory_buffer< T, SIZE, Allocator > && other) inline noexcept
Constructs a basic_memory_buffer object moving the content of the other object to it.
Referenced by detail::bigint::square().
Member Function Documentation
append()
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = detail::allocator<T>> template<typename ContiguousRange > FMT_CONSTEXPR20 void basic_memory_buffer< T, SIZE, Allocator >::append (const ContiguousRange & range) inline
deallocate()
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = detail::allocator<T>> FMT_CONSTEXPR20 void basic_memory_buffer< T, SIZE, Allocator >::deallocate () inline private
Referenced by basic_memory_buffer< T, SIZE, Allocator >::operator=(), and basic_memory_buffer< T, SIZE, Allocator >::~basic_memory_buffer().
get_allocator()
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = detail::allocator<T>> auto basic_memory_buffer< T, SIZE, Allocator >::get_allocator () const -> Allocator inline
grow()
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = detail::allocator<T>> static FMT_CONSTEXPR20 void basic_memory_buffer< T, SIZE, Allocator >::grow (detail::buffer< T > & buf, size_t size) inline static private
Referenced by basic_memory_buffer< T, SIZE, Allocator >::basic_memory_buffer(), and basic_memory_buffer< T, SIZE, Allocator >::basic_memory_buffer().
move()
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = detail::allocator<T>> FMT_CONSTEXPR20 void basic_memory_buffer< T, SIZE, Allocator >::move (basic_memory_buffer< T, SIZE, Allocator > & other) inline private
Referenced by basic_memory_buffer< T, SIZE, Allocator >::basic_memory_buffer(), and basic_memory_buffer< T, SIZE, Allocator >::operator=().
move_alloc() [1/2]
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = detail::allocator<T>> template<typename Alloc = Allocator, FMT_ENABLE_IF(std::allocator_traits< Alloc >:: propagate_on_container_move_assignment::value) > FMT_CONSTEXPR20 auto basic_memory_buffer< T, SIZE, Allocator >::move_alloc (basic_memory_buffer< T, SIZE, Allocator > & other) -> bool inline private
move_alloc() [2/2]
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = detail::allocator<T>> template<typename Alloc = Allocator, FMT_ENABLE_IF(!std::allocator_traits< Alloc >:: propagate_on_container_move_assignment::value) > FMT_CONSTEXPR20 auto basic_memory_buffer< T, SIZE, Allocator >::move_alloc (basic_memory_buffer< T, SIZE, Allocator > & other) -> bool inline private
operator=()
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = detail::allocator<T>> auto basic_memory_buffer< T, SIZE, Allocator >::operator= (basic_memory_buffer< T, SIZE, Allocator > && other) -> basic_memory_buffer& inline noexcept
Moves the content of the other basic_memory_buffer object to this one.
reserve()
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = detail::allocator<T>> void basic_memory_buffer< T, SIZE, Allocator >::reserve (size_t new_capacity) inline
Increases the buffer capacity to new_capacity.
resize()
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = detail::allocator<T>> FMT_CONSTEXPR void basic_memory_buffer< T, SIZE, Allocator >::resize (size_t count) inline
Resizes the buffer to contain count elements. If T is a POD type new elements may not be initialized.
Referenced by detail::bigint::align(), detail::bigint::assign(), detail::bigint::assign(), detail::bigint::remove_leading_zeros(), and detail::bigint::square().
Member Data Documentation
alloc_
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = detail::allocator<T>> FMT_NO_UNIQUE_ADDRESS Allocator basic_memory_buffer< T, SIZE, Allocator >::alloc_ private
Referenced by basic_memory_buffer< T, SIZE, Allocator >::basic_memory_buffer(), basic_memory_buffer< T, SIZE, Allocator >::deallocate(), basic_memory_buffer< T, SIZE, Allocator >::get_allocator(), and basic_memory_buffer< T, SIZE, Allocator >::move_alloc().
store_
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = detail::allocator<T>> T basic_memory_buffer< T, SIZE, Allocator >::store_[SIZE] private
Referenced by basic_memory_buffer< T, SIZE, Allocator >::basic_memory_buffer(), basic_memory_buffer< T, SIZE, Allocator >::deallocate(), and basic_memory_buffer< T, SIZE, Allocator >::move().
The documentation for this class was generated from the following file:
thirdparty/fmt/include/fmt/format.h