CHRONOS-LoRa: detail::glibc_file< F > Class Template Reference
detail::glibc_file< F > Class Template Reference
#include <format-inl.h>
Public Member Functions
auto is_buffered () const -> bool
void init_buffer ()
auto get_read_buffer () const -> span< const char >
auto get_write_buffer () const -> span< char >
void advance_write_buffer (size_t size)
auto needs_flush () const -> bool
void flush ()
Public Member Functions inherited from detail::file_base< F >
file_base (F *file)
operator F* () const
auto get () -> int
void unget (char c)
void flush ()
Private Types
enum { line_buffered = 0x200 , unbuffered = 2 }
Additional Inherited Members
Public Attributes inherited from detail::file_base< F >
F * file_
Member Enumeration Documentation
anonymous enum
template<typename F > anonymous enum private
Enumerator
line_buffered
unbuffered
Member Function Documentation
advance_write_buffer()
template<typename F > void detail::glibc_file< F >::advance_write_buffer (size_t size) inline
Referenced by detail::file_print_buffer< F, enable_if_t< has_flockfile< F >::value > >::~file_print_buffer().
flush()
template<typename F > void detail::glibc_file< F >::flush () inline
get_read_buffer()
template<typename F > auto detail::glibc_file< F >::get_read_buffer () const -> span<const char> inline
get_write_buffer()
template<typename F > auto detail::glibc_file< F >::get_write_buffer () const -> span<char> inline
Referenced by detail::file_print_buffer< F, enable_if_t< has_flockfile< F >::value > >::file_print_buffer().
init_buffer()
template<typename F > void detail::glibc_file< F >::init_buffer () inline
Referenced by detail::file_print_buffer< F, enable_if_t< has_flockfile< F >::value > >::file_print_buffer().
is_buffered()
template<typename F > auto detail::glibc_file< F >::is_buffered () const -> bool inline
Referenced by vprint().
needs_flush()
template<typename F > auto detail::glibc_file< F >::needs_flush () const -> bool inline
Referenced by detail::file_print_buffer< F, enable_if_t< has_flockfile< F >::value > >::~file_print_buffer().
The documentation for this class was generated from the following file:
thirdparty/fmt/include/fmt/format-inl.h