CHRONOS-LoRa: detail::iterator_buffer< T *, T, fixed_buffer_traits > Class Template Reference
detail::iterator_buffer< T *, T, fixed_buffer_traits > Class Template Reference
#include <base.h>
Public Member Functions
iterator_buffer (T *out, size_t n=buffer_size)
iterator_buffer (iterator_buffer &&other) noexcept
~iterator_buffer ()
auto out () -> T *
auto count () const -> size_t
Public Member Functions inherited from detail::fixed_buffer_traits
constexpr fixed_buffer_traits (size_t limit)
constexpr auto count () const -> size_t
FMT_CONSTEXPR auto limit (size_t size) -> size_t
Public Member Functions inherited from detail::buffer< T >
buffer (const buffer &)=delete
void operator= (const buffer &)=delete
auto begin () noexcept -> T *
auto end () noexcept -> T *
auto begin () const noexcept -> const T *
auto end () const noexcept -> const T *
constexpr auto size () const noexcept -> size_t
Returns the size of this buffer.
constexpr auto capacity () const noexcept -> size_t
Returns the capacity of this buffer.
FMT_CONSTEXPR auto data () noexcept -> T *
Returns a pointer to the buffer data (not null-terminated).
FMT_CONSTEXPR auto data () const noexcept -> const T *
FMT_CONSTEXPR void clear ()
Clears this buffer.
FMT_CONSTEXPR void try_resize (size_t count)
FMT_CONSTEXPR void try_reserve (size_t new_capacity)
FMT_CONSTEXPR void push_back (const T &value)
template<typename U >
FMT_CONSTEXPR20 void append (const U *begin, const U *end)
Appends data to the end of the buffer.
template<typename Idx >
FMT_CONSTEXPR auto operator[] (Idx index) -> T &
template<typename Idx >
constexpr auto operator[] (Idx index) const -> const T &
Private Types
enum { buffer_size = 256 }
Private Member Functions
void flush ()
Static Private Member Functions
static FMT_CONSTEXPR void grow (buffer< T > &buf, size_t)
Private Attributes
T * out_
T data_ [buffer_size]
Additional Inherited Members
Public Types inherited from detail::buffer< T >
using value_type = T
using const_reference = const T &
Protected Member Functions inherited from detail::buffer< T >
FMT_CONSTEXPR buffer (grow_fun grow, size_t sz) noexcept
constexpr buffer (grow_fun grow, T *p=nullptr, size_t sz=0, size_t cap=0) noexcept
FMT_CONSTEXPR20 ~buffer ()=default
buffer (buffer &&)=default
FMT_CONSTEXPR void set (T *buf_data, size_t buf_capacity) noexcept
Sets the buffer data and capacity.
Member Enumeration Documentation
anonymous enum
template<typename T > anonymous enum private
Enumerator
buffer_size
Constructor & Destructor Documentation
iterator_buffer() [1/2]
template<typename T > detail::iterator_buffer< T *, T, fixed_buffer_traits >::iterator_buffer (T * out, size_t n = buffer_size) inline explicit
iterator_buffer() [2/2]
template<typename T > detail::iterator_buffer< T *, T, fixed_buffer_traits >::iterator_buffer (iterator_buffer< T *, T, fixed_buffer_traits > && other) inline noexcept
~iterator_buffer()
template<typename T > detail::iterator_buffer< T *, T, fixed_buffer_traits >::~iterator_buffer () inline
Member Function Documentation
count()
template<typename T > auto detail::iterator_buffer< T *, T, fixed_buffer_traits >::count () const -> size_t inline
flush()
template<typename T > void detail::iterator_buffer< T *, T, fixed_buffer_traits >::flush () inline private
Referenced by out(), and ~iterator_buffer().
grow()
template<typename T > static FMT_CONSTEXPR void detail::iterator_buffer< T *, T, fixed_buffer_traits >::grow (buffer< T > & buf, size_t) inline static private
Referenced by iterator_buffer().
out()
template<typename T > auto detail::iterator_buffer< T *, T, fixed_buffer_traits >::out () -> T* inline
Member Data Documentation
data_
template<typename T > T detail::iterator_buffer< T *, T, fixed_buffer_traits >::data_[buffer_size] private
Referenced by flush(), and iterator_buffer().
out_
template<typename T > T* detail::iterator_buffer< T *, T, fixed_buffer_traits >::out_ private
Referenced by flush(), iterator_buffer(), iterator_buffer(), and out().
The documentation for this class was generated from the following file:
thirdparty/fmt/include/fmt/base.h