CHRONOS-LoRa: detail::bigint Class Reference
detail::bigint Class Reference
#include <format.h>
Public Member Functions
FMT_CONSTEXPR bigint ()
bigint (uint64_t n)
bigint (const bigint &)=delete
void operator= (const bigint &)=delete
FMT_CONSTEXPR void assign (const bigint &other)
template<typename Int >
FMT_CONSTEXPR void operator= (Int n)
FMT_CONSTEXPR auto num_bigits () const -> int
FMT_CONSTEXPR auto operator<<= (int shift) -> bigint &
template<typename Int >
FMT_CONSTEXPR auto operator*= (Int value) -> bigint &
FMT_CONSTEXPR20 void assign_pow10 (int exp)
FMT_CONSTEXPR20 void square ()
FMT_CONSTEXPR void align (const bigint &other)
FMT_CONSTEXPR auto divmod_assign (const bigint &divisor) -> int
Private Types
enum { bigit_bits = num_bits<bigit>() }
enum { bigits_capacity = 32 }
using bigit = uint32_t
using double_bigit = uint64_t
Private Member Functions
FMT_CONSTEXPR auto get_bigit (int i) const -> bigit
FMT_CONSTEXPR void subtract_bigits (int index, bigit other, bigit &borrow)
FMT_CONSTEXPR void remove_leading_zeros ()
FMT_CONSTEXPR void subtract_aligned (const bigint &other)
FMT_CONSTEXPR void multiply (uint32_t value)
template<typename UInt , FMT_ENABLE_IF(std::is_same< UInt, uint64_t >::value|| std::is_same< UInt, uint128_t >::value) >
FMT_CONSTEXPR void multiply (UInt value)
template<typename UInt , FMT_ENABLE_IF(std::is_same< UInt, uint64_t >::value|| std::is_same< UInt, uint128_t >::value) >
FMT_CONSTEXPR void assign (UInt n)
Private Attributes
basic_memory_buffer< bigit, bigits_capacity > bigits_
int exp_
Friends
struct formatter< bigint >
FMT_CONSTEXPR auto compare (const bigint &b1, const bigint &b2) -> int
FMT_CONSTEXPR auto add_compare (const bigint &lhs1, const bigint &lhs2, const bigint &rhs) -> int
Member Typedef Documentation
bigit
using detail::bigint::bigit = uint32_t private
double_bigit
using detail::bigint::double_bigit = uint64_t private
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
bigit_bits
anonymous enum
anonymous enum private
Enumerator
bigits_capacity
Constructor & Destructor Documentation
bigint() [1/3]
FMT_CONSTEXPR detail::bigint::bigint () inline
bigint() [2/3]
detail::bigint::bigint (uint64_t n) inline explicit
bigint() [3/3]
detail::bigint::bigint (const bigint &) delete
Member Function Documentation
align()
FMT_CONSTEXPR void detail::bigint::align (const bigint & other) inline
Referenced by divmod_assign().
assign() [1/2]
FMT_CONSTEXPR void detail::bigint::assign (const bigint & other) inline
Referenced by detail::format_dragon().
assign() [2/2]
template<typename UInt , FMT_ENABLE_IF(std::is_same< UInt, uint64_t >::value|| std::is_same< UInt, uint128_t >::value) > FMT_CONSTEXPR void detail::bigint::assign (UInt n) inline private
Referenced by bigint().
assign_pow10()
FMT_CONSTEXPR20 void detail::bigint::assign_pow10 (int exp) inline
Referenced by detail::format_dragon().
divmod_assign()
FMT_CONSTEXPR auto detail::bigint::divmod_assign (const bigint & divisor) -> int inline
Referenced by detail::format_dragon().
get_bigit()
FMT_CONSTEXPR auto detail::bigint::get_bigit (int i) const -> bigit inline private
multiply() [1/2]
template<typename UInt , FMT_ENABLE_IF(std::is_same< UInt, uint64_t >::value|| std::is_same< UInt, uint128_t >::value) > FMT_CONSTEXPR void detail::bigint::multiply (UInt value) inline private
multiply() [2/2]
FMT_CONSTEXPR void detail::bigint::multiply (uint32_t value) inline private
num_bigits()
FMT_CONSTEXPR auto detail::bigint::num_bigits () const -> int inline
Referenced by get_bigit().
operator*=()
template<typename Int > FMT_CONSTEXPR auto detail::bigint::operator*= (Int value) -> bigint& inline
Referenced by assign_pow10(), and detail::format_dragon().
operator<<=()
FMT_CONSTEXPR auto detail::bigint::operator<<= (int shift) -> bigint& inline
Referenced by assign_pow10(), and detail::format_dragon().
operator=() [1/2]
void detail::bigint::operator= (const bigint &) delete
operator=() [2/2]
template<typename Int > FMT_CONSTEXPR void detail::bigint::operator= (Int n) inline
Referenced by assign_pow10(), and detail::format_dragon().
remove_leading_zeros()
FMT_CONSTEXPR void detail::bigint::remove_leading_zeros () inline private
Referenced by square(), and subtract_aligned().
square()
FMT_CONSTEXPR20 void detail::bigint::square () inline
Referenced by assign_pow10().
subtract_aligned()
FMT_CONSTEXPR void detail::bigint::subtract_aligned (const bigint & other) inline private
Referenced by divmod_assign().
subtract_bigits()
FMT_CONSTEXPR void detail::bigint::subtract_bigits (int index, bigit other, bigit & borrow) inline private
Referenced by subtract_aligned().
Friends And Related Symbol Documentation
add_compare
FMT_CONSTEXPR auto add_compare (const bigint & lhs1, const bigint & lhs2, const bigint & rhs) -> int friend
Referenced by detail::format_dragon().
compare
FMT_CONSTEXPR auto compare (const bigint & b1, const bigint & b2) -> int friend
Referenced by divmod_assign(), detail::format_dragon(), and subtract_aligned().
formatter< bigint >
friend struct formatter< bigint > friend
Member Data Documentation
bigits_
basic_memory_buffer<bigit, bigits_capacity> detail::bigint::bigits_ private
Referenced by align(), assign(), assign(), divmod_assign(), formatter< detail::bigint >::format(), get_bigit(), multiply(), multiply(), num_bigits(), operator<<=(), remove_leading_zeros(), square(), subtract_aligned(), and subtract_bigits().
exp_
int detail::bigint::exp_ private
Referenced by align(), assign(), assign(), bigint(), formatter< detail::bigint >::format(), get_bigit(), num_bigits(), operator<<=(), square(), and subtract_aligned().
The documentation for this class was generated from the following file:
thirdparty/fmt/include/fmt/format.h