CHRONOS-LoRa: cxxopts::OptionAdder Class Reference
cxxopts::OptionAdder Class Reference
#include <cxxopts.hpp>
Public Member Functions
OptionAdder (Options &options, std::string group)
OptionAdder & operator() (const std::string &opts, const std::string &desc, const std::shared_ptr< const Value > &value=::cxxopts::value< bool >(), std::string arg_help="")
Private Attributes
Options & m_options
std::string m_group
Constructor & Destructor Documentation
OptionAdder()
cxxopts::OptionAdder::OptionAdder (Options & options, std::string group) inline
Referenced by cxxopts::Options::add_options(), and cxxopts::Options::add_options().
Member Function Documentation
operator()()
OptionAdder & cxxopts::OptionAdder::operator() (const std::string & opts, const std::string & desc, const std::shared_ptr< const Value > & value = ::cxxopts::value<bool>(), std::string arg_help = "") inline
Referenced by cxxopts::Options::add_options(), and main().
Member Data Documentation
m_group
std::string cxxopts::OptionAdder::m_group private
Referenced by operator()(), and OptionAdder().
m_options
Options& cxxopts::OptionAdder::m_options private
Referenced by operator()(), and OptionAdder().
The documentation for this class was generated from the following file:
thirdparty/libcxxopts-dev/cxxopts.hpp