CHRONOS-LoRa: basic_appender< T > Class Template Reference
basic_appender< T > Class Template Reference
#include <base.h>
Public Types
using container_type = detail::buffer< T >
Public Member Functions
constexpr basic_appender (detail::buffer< T > &buf)
FMT_CONSTEXPR auto operator= (T c) -> basic_appender &
FMT_CONSTEXPR auto operator* () -> basic_appender &
FMT_CONSTEXPR auto operator++ () -> basic_appender &
FMT_CONSTEXPR auto operator++ (int) -> basic_appender
Protected Attributes
detail::buffer< T > * container
Member Typedef Documentation
container_type
template<typename T > using basic_appender< T >::container_type = detail::buffer<T>
Constructor & Destructor Documentation
basic_appender()
template<typename T > constexpr basic_appender< T >::basic_appender (detail::buffer< T > & buf) inline constexpr
Referenced by formatter< std::error_code >::format(), detail::format_error_code(), detail::format_hexfloat(), format_system_error(), formatted_size(), writer::print(), print(), detail::vformat_to(), detail::write(), detail::write_int(), and detail::write_significand().
Member Function Documentation
operator*()
template<typename T > FMT_CONSTEXPR auto basic_appender< T >::operator* () -> basic_appender& inline
operator++() [1/2]
template<typename T > FMT_CONSTEXPR auto basic_appender< T >::operator++ () -> basic_appender& inline
operator++() [2/2]
template<typename T > FMT_CONSTEXPR auto basic_appender< T >::operator++ (int) -> basic_appender inline
operator=()
template<typename T > FMT_CONSTEXPR auto basic_appender< T >::operator= (T c) -> basic_appender& inline
Member Data Documentation
container
template<typename T > detail::buffer<T>* basic_appender< T >::container protected
Referenced by basic_appender< T >::basic_appender(), and basic_appender< T >::operator=().
The documentation for this class was generated from the following file:
thirdparty/fmt/include/fmt/base.h