CHRONOS-LoRa: format_facet< Locale > Class Template Reference
format_facet< Locale > Class Template Reference
#include <format.h>
Public Member Functions
format_facet (Locale &loc)
format_facet (string_view sep="", std::string grouping="\3", std::string decimal_point=".")
auto put (appender out, loc_value val, const format_specs &specs) const -> bool
Static Public Attributes
static FMT_API Locale::id id
Protected Member Functions
virtual auto do_put (appender out, loc_value val, const format_specs &specs) const -> bool
FMT_API FMT_FUNC auto do_put (appender out, loc_value val, const format_specs &specs) const -> bool
Private Attributes
std::string separator_
std::string grouping_
std::string decimal_point_
Constructor & Destructor Documentation
format_facet() [1/2]
template<typename Locale > format_facet< Locale >::format_facet (Locale & loc) explicit
Referenced by detail::write_loc().
format_facet() [2/2]
template<typename Locale > format_facet< Locale >::format_facet (string_view sep = "", std::string grouping = "\3", std::string decimal_point = ".") inline explicit
Member Function Documentation
do_put() [1/2]
FMT_API FMT_FUNC auto format_facet< std::locale >::do_put (appender out, loc_value val, const format_specs & specs) const -> bool protected
do_put() [2/2]
template<typename Locale > virtual auto format_facet< Locale >::do_put (appender out, loc_value val, const format_specs & specs) const -> bool protected virtual
Referenced by format_facet< Locale >::put().
put()
template<typename Locale > auto format_facet< Locale >::put (appender out, loc_value val, const format_specs & specs) const -> bool inline
Referenced by detail::write_loc().
Member Data Documentation
decimal_point_
template<typename Locale > std::string format_facet< Locale >::decimal_point_ private
Referenced by format_facet< Locale >::format_facet().
grouping_
template<typename Locale > std::string format_facet< Locale >::grouping_ private
Referenced by format_facet< Locale >::format_facet(), and format_facet< Locale >::format_facet().
id
template<typename Locale > Locale::id format_facet< Locale >::id static
separator_
template<typename Locale > std::string format_facet< Locale >::separator_ private
Referenced by format_facet< Locale >::format_facet(), and format_facet< Locale >::format_facet().
The documentation for this class was generated from the following files:
thirdparty/fmt/include/fmt/format.h
thirdparty/fmt/include/fmt/format-inl.h