CHRONOS-LoRa: cxxopts::OptionValue Class Reference
cxxopts::OptionValue Class Reference
#include <cxxopts.hpp>
Public Member Functions
void add (const std::shared_ptr< const OptionDetails > &details, const std::string &text)
void parse (const std::shared_ptr< const OptionDetails > &details, const std::string &text)
void parse_default (const std::shared_ptr< const OptionDetails > &details)
void parse_no_value (const std::shared_ptr< const OptionDetails > &details)
CXXOPTS_NODISCARD std::size_t count () const noexcept
CXXOPTS_NODISCARD bool has_default () const noexcept
template<typename T >
const T & as () const
Private Member Functions
void ensure_value (const std::shared_ptr< const OptionDetails > &details)
Private Attributes
const OptionNames * m_long_names = nullptr
std::shared_ptr< Value > m_value {}
std::size_t m_count = 0
bool m_default = false
Member Function Documentation
add()
void cxxopts::OptionValue::add (const std::shared_ptr< const OptionDetails > & details, const std::string & text) inline
Referenced by cxxopts::OptionParser::add_to_option().
as()
template<typename T > const T & cxxopts::OptionValue::as () const inline
count()
CXXOPTS_NODISCARD std::size_t cxxopts::OptionValue::count () const inline noexcept
Referenced by cxxopts::OptionParser::consume_positional(), cxxopts::ParseResult::count(), and cxxopts::OptionParser::parse().
ensure_value()
void cxxopts::OptionValue::ensure_value (const std::shared_ptr< const OptionDetails > & details) inline private
Referenced by add(), parse(), and parse_default().
has_default()
CXXOPTS_NODISCARD bool cxxopts::OptionValue::has_default () const inline noexcept
Referenced by cxxopts::OptionParser::parse().
parse()
void cxxopts::OptionValue::parse (const std::shared_ptr< const OptionDetails > & details, const std::string & text) inline
Referenced by cxxopts::OptionParser::parse_option().
parse_default()
void cxxopts::OptionValue::parse_default (const std::shared_ptr< const OptionDetails > & details) inline
Referenced by cxxopts::OptionParser::parse_default().
parse_no_value()
void cxxopts::OptionValue::parse_no_value (const std::shared_ptr< const OptionDetails > & details) inline
Referenced by cxxopts::OptionParser::parse_no_value().
Member Data Documentation
m_count
std::size_t cxxopts::OptionValue::m_count = 0 private
Referenced by add(), count(), and parse().
m_default
bool cxxopts::OptionValue::m_default = false private
Referenced by has_default(), and parse_default().
m_long_names
const OptionNames* cxxopts::OptionValue::m_long_names = nullptr private
Referenced by add(), as(), parse(), parse_default(), and parse_no_value().
m_value
std::shared_ptr<Value> cxxopts::OptionValue::m_value {} private
Referenced by add(), as(), ensure_value(), parse(), and parse_default().
The documentation for this class was generated from the following file:
thirdparty/libcxxopts-dev/cxxopts.hpp