CHRONOS-LoRa: locale_ref Class Reference
locale_ref Class Reference
#include <base.h>
Public Member Functions
constexpr locale_ref ()
template<typename Locale , FMT_ENABLE_IF(sizeof(Locale::collate) !=0) >
locale_ref (const Locale &loc)
operator bool () const noexcept
template<typename Locale >
auto get () const -> Locale
Private Attributes
const void * locale_
Constructor & Destructor Documentation
locale_ref() [1/2]
constexpr locale_ref::locale_ref () inline constexpr
Referenced by context::context(), formatter< std::tm, Char >::do_format(), generic_context< OutputIt, Char >::generic_context(), basic_printf_context< Char >::locale(), detail::make_arg_formatter(), detail::vformat_to(), detail::write(), detail::write(), and detail::write_fixed().
locale_ref() [2/2]
template<typename Locale , FMT_ENABLE_IF(sizeof(Locale::collate) !=0) > locale_ref::locale_ref (const Locale & loc) inline
Member Function Documentation
get()
template<typename Locale > auto locale_ref::get () const -> Locale
Referenced by detail::decimal_point_impl(), detail::get_locale::get_locale(), detail::thousands_sep_impl(), detail::write_loc(), and detail::write_loc().
operator bool()
locale_ref::operator bool () const inline explicit noexcept
Member Data Documentation
locale_
const void* locale_ref::locale_ private
Referenced by get(), locale_ref(), locale_ref(), and operator bool().
The documentation for this class was generated from the following files:
thirdparty/fmt/include/fmt/base.h
thirdparty/fmt/include/fmt/format-inl.h