CHRONOS-LoRa: Magick::Image Class Reference
Magick::Image Class Reference
#include <Image.h>
Public Member Functions
Image (const std::string &imageSpec_)
Image (const Geometry &size_, const Color &color_)
Image (const Blob &blob_)
Image (const Blob &blob_, const Geometry &size_)
Image (const Blob &blob_, const Geometry &size, const unsigned int depth)
Image (const Blob &blob_, const Geometry &size, const unsigned int depth_, const std::string &magick_)
Image (const Blob &blob_, const Geometry &size, const std::string &magick_)
Image (const unsigned int width_, const unsigned int height_, const std::string &map_, const StorageType type_, const void *pixels_)
Image (void)
virtual ~Image ()
Image (const Image &image_)
Copy constructor.
Image & operator= (const Image &image_)
void adaptiveThreshold (const unsigned int width, const unsigned int height, const double offset=0.0)
void adaptiveThreshold (const unsigned int width, const unsigned int height, const unsigned int offset) MAGICK_FUNC_DEPRECATED
void addNoise (const NoiseType noiseType_)
void addNoiseChannel (const ChannelType channel_, const NoiseType noiseType_)
void affineTransform (const DrawableAffine &affine)
void annotate (const std::string &text_, const Geometry &location_)
void annotate (const std::string &text_, const Geometry &boundingArea_, const GravityType gravity_)
void annotate (const std::string &text_, const Geometry &boundingArea_, const GravityType gravity_, const double degrees_)
void annotate (const std::string &text_, const GravityType gravity_)
void autoOrient (void)
void blur (const double radius_=0.0, const double sigma_=1.0)
void blurChannel (const ChannelType channel_, const double radius_=0.0, const double sigma_=1.0)
void border (const Geometry &geometry_=borderGeometryDefault)
void cdl (const std::string &cdl_)
void channel (const ChannelType channel_)
void channelDepth (const ChannelType channel_, const unsigned int depth_)
unsigned int channelDepth (const ChannelType channel_)
void charcoal (const double radius_=0.0, const double sigma_=1.0)
void chop (const Geometry &geometry_)
void colorize (const unsigned int opacityRed_, const unsigned int opacityGreen_, const unsigned int opacityBlue_, const Color &penColor_)
void colorize (const unsigned int opacity_, const Color &penColor_)
void colorMatrix (const unsigned int order_, const double *color_matrix_)
void comment (const std::string &comment_)
bool compare (const Image &reference_)
void composite (const Image &compositeImage_, const int xOffset_, const int yOffset_, const CompositeOperator compose_=InCompositeOp)
void composite (const Image &compositeImage_, const Geometry &offset_, const CompositeOperator compose_=InCompositeOp)
void composite (const Image &compositeImage_, const GravityType gravity_, const CompositeOperator compose_=InCompositeOp)
void contrast (const unsigned int sharpen_)
void convolve (const unsigned int order_, const double *kernel_)
void crop (const Geometry &geometry_)
void cycleColormap (const int amount_)
void despeckle (void)
void display (void)
void draw (const Drawable &drawable_)
void draw (const std::list< Magick::Drawable > &drawable_)
void edge (const double radius_=0.0)
void emboss (const double radius_=0.0, const double sigma_=1.0)
void enhance (void)
void equalize (void)
void erase (void)
void extent (const Geometry &geometry_)
void extent (const Geometry &geometry_, const GravityType &gravity_)
void extent (const Geometry &geometry_, const Color &backgroundColor_)
void extent (const Geometry &geometry_, const Color &backgroundColor_, const GravityType &gravity_)
void flip (void)
void floodFillColor (const unsigned int x_, const unsigned int y_, const Color &fillColor_)
void floodFillColor (const Geometry &point_, const Color &fillColor_)
void floodFillColor (const unsigned int x_, const unsigned int y_, const Color &fillColor_, const Color &borderColor_)
void floodFillColor (const Geometry &point_, const Color &fillColor_, const Color &borderColor_)
void floodFillOpacity (const unsigned int x_, const unsigned int y_, const unsigned int opacity_, const PaintMethod method_)
void floodFillTexture (const unsigned int x_, const unsigned int y_, const Image &texture_)
void floodFillTexture (const Geometry &point_, const Image &texture_)
void floodFillTexture (const unsigned int x_, const unsigned int y_, const Image &texture_, const Color &borderColor_)
void floodFillTexture (const Geometry &point_, const Image &texture_, const Color &borderColor_)
void flop (void)
void frame (const Geometry &geometry_=frameGeometryDefault)
void frame (const unsigned int width_, const unsigned int height_, const int innerBevel_=6, const int outerBevel_=6)
void gamma (const double gamma_)
void gamma (const double gammaRed_, const double gammaGreen_, const double gammaBlue_)
void gaussianBlur (const double width_, const double sigma_)
void gaussianBlurChannel (const ChannelType channel_, const double width_, const double sigma_)
void implode (const double factor_)
void haldClut (const Image &clutImage_)
void label (const std::string &label_)
void level (const double black_point, const double white_point, const double mid_point=1.0)
void levelChannel (const ChannelType channel, const double black_point, const double white_point, const double mid_point=1.0)
void magnify (void)
void map (const Image &mapImage_, const bool dither_=false)
void matteFloodfill (const Color &target_, const unsigned int opacity_, const int x_, const int y_, const PaintMethod method_)
void medianFilter (const double radius_=0.0)
void minify (void)
void modulate (const double brightness_, const double saturation_, const double hue_)
void motionBlur (const double radius_, const double sigma_, const double angle_)
void negate (const bool grayscale_=false)
void normalize (void)
void oilPaint (const double radius_=3.0)
void opacity (const unsigned int opacity_)
void opaque (const Color &opaqueColor_, const Color &penColor_)
void ping (const std::string &imageSpec_)
void ping (const Blob &blob_)
void quantize (const bool measureError_=false)
void quantumOperator (const ChannelType channel_, const QuantumOperator operator_, Quantum rvalue_) MAGICK_FUNC_DEPRECATED
void quantumOperator (const ChannelType channel_, const QuantumOperator operator_, double rvalue_)
void quantumOperator (const int x_, const int y_, const unsigned int columns_, const unsigned int rows_, const ChannelType channel_, const QuantumOperator operator_, const Quantum rvalue_) MAGICK_FUNC_DEPRECATED
void quantumOperator (const int x_, const int y_, const unsigned int columns_, const unsigned int rows_, const ChannelType channel_, const QuantumOperator operator_, const double rvalue_)
void process (std::string name_, const int argc_, char **argv_)
void raise (const Geometry &geometry_=raiseGeometryDefault, const bool raisedFlag_=false)
void randomThreshold (const Geometry &thresholds_)
void randomThresholdChannel (const Geometry &thresholds_, const ChannelType channel_)
void read (const std::string &imageSpec_)
void read (const Geometry &size_, const std::string &imageSpec_)
void read (const Blob &blob_)
void read (const Blob &blob_, const Geometry &size_)
void read (const Blob &blob_, const Geometry &size_, const unsigned int depth_)
void read (const Blob &blob_, const Geometry &size_, const unsigned int depth_, const std::string &magick_)
void read (const Blob &blob_, const Geometry &size_, const std::string &magick_)
void read (const unsigned int width_, const unsigned int height_, const std::string &map_, const StorageType type_, const void *pixels_)
void reduceNoise (void)
void reduceNoise (const double order_)
void repage ()
void resize (const Geometry &geometry_, const FilterTypes filterType_, const double blur_)
void resize (const Geometry &geometry_, const FilterTypes filterType_)
void resize (const Geometry &geometry_)
void roll (const Geometry &roll_)
void roll (const unsigned int columns_, const unsigned int rows_)
void rotate (const double degrees_)
void sample (const Geometry &geometry_)
void scale (const Geometry &geometry_)
void thumbnail (const Geometry &geometry_)
void segment (const double clusterThreshold_=1.0, const double smoothingThreshold_=1.5)
void shade (const double azimuth_=30, const double elevation_=30, const bool colorShading_=false)
void sharpen (const double radius_=0.0, const double sigma_=1.0)
void sharpenChannel (const ChannelType channel_, const double radius_=0.0, const double sigma_=1.0)
void shave (const Geometry &geometry_)
void shear (const double xShearAngle_, const double yShearAngle_)
void solarize (const double factor_=50.0)
void spread (const unsigned int amount_=3)
void stegano (const Image &watermark_)
void stereo (const Image &rightImage_)
void strip (void)
void swirl (const double degrees_)
void texture (const Image &texture_)
void threshold (const double threshold_)
void transform (const Geometry &imageGeometry_)
void transform (const Geometry &imageGeometry_, const Geometry &cropGeometry_)
void transparent (const Color &color_)
void trim (void)
void type (const ImageType type_)
void unsharpmask (const double radius_, const double sigma_, const double amount_, const double threshold_)
void unsharpmaskChannel (const ChannelType channel_, const double radius_, const double sigma_, const double amount_, const double threshold_)
void wave (const double amplitude_=25.0, const double wavelength_=150.0)
void write (const std::string &imageSpec_)
void write (Blob *blob_)
void write (Blob *blob_, const std::string &magick_)
void write (Blob *blob_, const std::string &magick_, const unsigned int depth_)
void write (const int x_, const int y_, const unsigned int columns_, const unsigned int rows_, const std::string &map_, const StorageType type_, void *pixels_)
void zoom (const Geometry &geometry_)
void adjoin (const bool flag_)
bool adjoin (void) const
void antiAlias (const bool flag_)
bool antiAlias (void)
void animationDelay (const unsigned int delay_)
unsigned int animationDelay (void) const
void animationIterations (const unsigned int iterations_)
unsigned int animationIterations (void) const
void attribute (const std::string name_, const char *value_)
void attribute (const std::string name_, const std::string value_)
std::string attribute (const std::string name_)
void backgroundColor (const Color &color_)
Color backgroundColor (void) const
void backgroundTexture (const std::string &backgroundTexture_)
std::string backgroundTexture (void) const
unsigned int baseColumns (void) const
std::string baseFilename (void) const
unsigned int baseRows (void) const
void borderColor (const Color &color_)
Color borderColor (void) const
Geometry boundingBox (void) const
void boxColor (const Color &boxColor_)
Color boxColor (void) const
void chromaBluePrimary (const double x_, const double y_)
void chromaBluePrimary (double *x_, double *y_) const
void chromaGreenPrimary (const double x_, const double y_)
void chromaGreenPrimary (double *x_, double *y_) const
void chromaRedPrimary (const double x_, const double y_)
void chromaRedPrimary (double *x_, double *y_) const
void chromaWhitePoint (const double x_, const double y_)
void chromaWhitePoint (double *x_, double *y_) const
void classType (const ClassType class_)
ClassType classType (void) const
void clipMask (const Image &clipMask_)
Image clipMask (void) const
void colorFuzz (const double fuzz_)
double colorFuzz (void) const
void colorMap (const unsigned int index_, const Color &color_)
Color colorMap (const unsigned int index_) const
void colorMapSize (const unsigned int entries_)
unsigned int colorMapSize (void) const
unsigned int colorMapSize (void)
void colorSpace (const ColorspaceType colorSpace_)
ColorspaceType colorSpace (void) const
unsigned int columns (void) const
std::string comment (void) const
void compose (const CompositeOperator compose_)
CompositeOperator compose (void) const
void compressType (const CompressionType compressType_)
CompressionType compressType (void) const
void debug (const bool flag_)
bool debug (void) const
void defineValue (const std::string &magick_, const std::string &key_, const std::string &value_)
std::string defineValue (const std::string &magick_, const std::string &key_) const
void defineSet (const std::string &magick_, const std::string &key_, bool flag_)
bool defineSet (const std::string &magick_, const std::string &key_) const
void density (const Geometry &geomery_)
Geometry density (void) const
void depth (const unsigned int depth_)
unsigned int depth (void) const
std::string directory (void) const
void endian (const EndianType endian_)
EndianType endian (void) const
void fileName (const std::string &fileName_)
std::string fileName (void) const
off_t fileSize (void) const
void fillColor (const Color &fillColor_)
Color fillColor (void) const
void fillRule (const FillRule &fillRule_)
FillRule fillRule (void) const
void fillPattern (const Image &fillPattern_)
Image fillPattern (void) const
void filterType (const FilterTypes filterType_)
FilterTypes filterType (void) const
void font (const std::string &font_)
std::string font (void) const
void fontPointsize (const double pointSize_)
double fontPointsize (void) const
void fontTypeMetrics (const std::string &text_, TypeMetric *metrics)
std::string format (void) const
std::string formatExpression (const std::string expression)
double gamma (void) const
Geometry geometry (void) const
void gifDisposeMethod (const unsigned int disposeMethod_)
unsigned int gifDisposeMethod (void) const
void iccColorProfile (const Blob &colorProfile_)
Blob iccColorProfile (void) const
void interlaceType (const InterlaceType interlace_)
InterlaceType interlaceType (void) const
void iptcProfile (const Blob &iptcProfile_)
Blob iptcProfile (void) const
void isValid (const bool isValid_)
bool isValid (void) const
std::string label (void) const
void lineWidth (const double lineWidth_)
double lineWidth (void) const
void magick (const std::string &magick_)
std::string magick (void) const
void matte (const bool matteFlag_)
bool matte (void) const
void matteColor (const Color &matteColor_)
Color matteColor (void) const
double meanErrorPerPixel (void) const
void modulusDepth (const unsigned int modulusDepth_)
unsigned int modulusDepth (void) const
Geometry montageGeometry (void) const
void monochrome (const bool monochromeFlag_)
bool monochrome (void) const
double normalizedMaxError (void) const
double normalizedMeanError (void) const
void orientation (const OrientationType orientation_)
OrientationType orientation (void) const
void page (const Geometry &pageSize_)
Geometry page (void) const
void penColor (const Color &penColor_)
Color penColor (void) const
void penTexture (const Image &penTexture_)
Image penTexture (void) const
void pixelColor (const unsigned int x_, const unsigned int y_, const Color &color_)
Color pixelColor (const unsigned int x_, const unsigned int y_) const
void profile (const std::string name_, const Blob &colorProfile_)
Blob profile (const std::string name_) const
void quality (const unsigned int quality_)
unsigned int quality (void) const
void quantizeColors (const unsigned int colors_)
unsigned int quantizeColors (void) const
void quantizeColorSpace (const ColorspaceType colorSpace_)
ColorspaceType quantizeColorSpace (void) const
void quantizeDither (const bool ditherFlag_)
bool quantizeDither (void) const
void quantizeTreeDepth (const unsigned int treeDepth_)
unsigned int quantizeTreeDepth (void) const
void quiet (const bool quiet_)
bool quiet (void) const
void renderingIntent (const RenderingIntent renderingIntent_)
RenderingIntent renderingIntent (void) const
void resolutionUnits (const ResolutionType resolutionUnits_)
ResolutionType resolutionUnits (void) const
unsigned int rows (void) const
void scene (const unsigned int scene_)
unsigned int scene (void) const
std::string signature (const bool force_=false) const
void size (const Geometry &geometry_)
Geometry size (void) const
void statistics (ImageStatistics *statistics) const
void strokeAntiAlias (const bool flag_)
bool strokeAntiAlias (void) const
void strokeColor (const Color &strokeColor_)
Color strokeColor (void) const
void strokeDashArray (const double *strokeDashArray_)
const double * strokeDashArray (void) const
void strokeDashOffset (const double strokeDashOffset_)
double strokeDashOffset (void) const
void strokeLineCap (const LineCap lineCap_)
LineCap strokeLineCap (void) const
void strokeLineJoin (const LineJoin lineJoin_)
LineJoin strokeLineJoin (void) const
void strokeMiterLimit (const unsigned int miterLimit_)
unsigned int strokeMiterLimit (void) const
void strokePattern (const Image &strokePattern_)
Image strokePattern (void) const
void strokeWidth (const double strokeWidth_)
double strokeWidth (void) const
void subImage (const unsigned int subImage_)
unsigned int subImage (void) const
void subRange (const unsigned int subRange_)
unsigned int subRange (void) const
void textEncoding (const std::string &encoding_)
std::string textEncoding (void) const
void tileName (const std::string &tileName_)
std::string tileName (void) const
unsigned long totalColors (void)
void transformOrigin (const double x_, const double y_)
void transformRotation (const double angle_)
void transformReset (void)
void transformScale (const double sx_, const double sy_)
void transformSkewX (const double skewx_)
void transformSkewY (const double skewy_)
ImageType type (void) const
void verbose (const bool verboseFlag_)
bool verbose (void) const
void view (const std::string &view_)
std::string view (void) const
void x11Display (const std::string &display_)
std::string x11Display (void) const
void xResolution (const double x_resolution)
double xResolution (void) const
void yResolution (const double y_resolution)
double yResolution (void) const
const PixelPacket * getConstPixels (const int x_, const int y_, const unsigned int columns_, const unsigned int rows_) const
IndexPacket * getIndexes (void)
const IndexPacket * getConstIndexes (void) const
PixelPacket * getPixels (const int x_, const int y_, const unsigned int columns_, const unsigned int rows_)
PixelPacket * setPixels (const int x_, const int y_, const unsigned int columns_, const unsigned int rows_)
void syncPixels (void)
void readPixels (const QuantumType quantum_, const unsigned char *source_)
void writePixels (const QuantumType quantum_, unsigned char *destination_)
Image (MagickLib::Image *image_)
MagickLib::Image *& image (void)
const MagickLib::Image * constImage (void) const
Options * options (void)
const Options * constOptions (void) const
MagickLib::ImageInfo * imageInfo (void)
const MagickLib::ImageInfo * constImageInfo (void) const
MagickLib::QuantizeInfo * quantizeInfo (void)
const MagickLib::QuantizeInfo * constQuantizeInfo (void) const
MagickLib::Image * replaceImage (MagickLib::Image *replacement_)
void modifyImage (void)
void throwImageException (void) const
long registerId (void)
void unregisterId (void)
Static Public Member Functions
static void cacheThreshold (const unsigned int threshold_)
Private Member Functions
void throwImageException (MagickLib::ExceptionInfo &exception_) const
Private Attributes
ImageRef * _imgRef
Constructor & Destructor Documentation
Image() [1/11]
Magick::Image::Image (const std::string & imageSpec_)
Image() [2/11]
Magick::Image::Image (const Geometry & size_, const Color & color_)
Image() [3/11]
Magick::Image::Image (const Blob & blob_)
Image() [4/11]
Magick::Image::Image (const Blob & blob_, const Geometry & size_)
Image() [5/11]
Magick::Image::Image (const Blob & blob_, const Geometry & size, const unsigned int depth)
Image() [6/11]
Magick::Image::Image (const Blob & blob_, const Geometry & size, const unsigned int depth_, const std::string & magick_)
Image() [7/11]
Magick::Image::Image (const Blob & blob_, const Geometry & size, const std::string & magick_)
Image() [8/11]
Magick::Image::Image (const unsigned int width_, const unsigned int height_, const std::string & map_, const StorageType type_, const void * pixels_)
Image() [9/11]
Magick::Image::Image (void)
~Image()
virtual Magick::Image::~Image () virtual
Image() [10/11]
Magick::Image::Image (const Image & image_)
Copy constructor.
Image() [11/11]
Magick::Image::Image (MagickLib::Image * image_)
Member Function Documentation
adaptiveThreshold() [1/2]
void Magick::Image::adaptiveThreshold (const unsigned int width, const unsigned int height, const double offset = 0.0)
adaptiveThreshold() [2/2]
void Magick::Image::adaptiveThreshold (const unsigned int width, const unsigned int height, const unsigned int offset)
addNoise()
void Magick::Image::addNoise (const NoiseType noiseType_)
addNoiseChannel()
void Magick::Image::addNoiseChannel (const ChannelType channel_, const NoiseType noiseType_)
adjoin() [1/2]
void Magick::Image::adjoin (const bool flag_)
adjoin() [2/2]
bool Magick::Image::adjoin (void) const
affineTransform()
void Magick::Image::affineTransform (const DrawableAffine & affine)
animationDelay() [1/2]
void Magick::Image::animationDelay (const unsigned int delay_)
animationDelay() [2/2]
unsigned int Magick::Image::animationDelay (void) const
animationIterations() [1/2]
void Magick::Image::animationIterations (const unsigned int iterations_)
animationIterations() [2/2]
unsigned int Magick::Image::animationIterations (void) const
annotate() [1/4]
void Magick::Image::annotate (const std::string & text_, const Geometry & boundingArea_, const GravityType gravity_)
annotate() [2/4]
void Magick::Image::annotate (const std::string & text_, const Geometry & boundingArea_, const GravityType gravity_, const double degrees_)
annotate() [3/4]
void Magick::Image::annotate (const std::string & text_, const Geometry & location_)
annotate() [4/4]
void Magick::Image::annotate (const std::string & text_, const GravityType gravity_)
antiAlias() [1/2]
void Magick::Image::antiAlias (const bool flag_)
antiAlias() [2/2]
bool Magick::Image::antiAlias (void)
attribute() [1/3]
std::string Magick::Image::attribute (const std::string name_)
attribute() [2/3]
void Magick::Image::attribute (const std::string name_, const char * value_)
attribute() [3/3]
void Magick::Image::attribute (const std::string name_, const std::string value_)
autoOrient()
void Magick::Image::autoOrient (void)
backgroundColor() [1/2]
void Magick::Image::backgroundColor (const Color & color_)
backgroundColor() [2/2]
Color Magick::Image::backgroundColor (void) const
backgroundTexture() [1/2]
void Magick::Image::backgroundTexture (const std::string & backgroundTexture_)
backgroundTexture() [2/2]
std::string Magick::Image::backgroundTexture (void) const
baseColumns()
unsigned int Magick::Image::baseColumns (void) const
baseFilename()
std::string Magick::Image::baseFilename (void) const
baseRows()
unsigned int Magick::Image::baseRows (void) const
blur()
void Magick::Image::blur (const double radius_ = 0.0, const double sigma_ = 1.0)
blurChannel()
void Magick::Image::blurChannel (const ChannelType channel_, const double radius_ = 0.0, const double sigma_ = 1.0)
border()
void Magick::Image::border (const Geometry & geometry_ = borderGeometryDefault)
borderColor() [1/2]
void Magick::Image::borderColor (const Color & color_)
borderColor() [2/2]
Color Magick::Image::borderColor (void) const
boundingBox()
Geometry Magick::Image::boundingBox (void) const
boxColor() [1/2]
void Magick::Image::boxColor (const Color & boxColor_)
boxColor() [2/2]
Color Magick::Image::boxColor (void) const
cacheThreshold()
static void Magick::Image::cacheThreshold (const unsigned int threshold_) static
cdl()
void Magick::Image::cdl (const std::string & cdl_)
channel()
void Magick::Image::channel (const ChannelType channel_)
channelDepth() [1/2]
unsigned int Magick::Image::channelDepth (const ChannelType channel_)
channelDepth() [2/2]
void Magick::Image::channelDepth (const ChannelType channel_, const unsigned int depth_)
charcoal()
void Magick::Image::charcoal (const double radius_ = 0.0, const double sigma_ = 1.0)
chop()
void Magick::Image::chop (const Geometry & geometry_)
chromaBluePrimary() [1/2]
void Magick::Image::chromaBluePrimary (const double x_, const double y_)
chromaBluePrimary() [2/2]
void Magick::Image::chromaBluePrimary (double * x_, double * y_) const
chromaGreenPrimary() [1/2]
void Magick::Image::chromaGreenPrimary (const double x_, const double y_)
chromaGreenPrimary() [2/2]
void Magick::Image::chromaGreenPrimary (double * x_, double * y_) const
chromaRedPrimary() [1/2]
void Magick::Image::chromaRedPrimary (const double x_, const double y_)
chromaRedPrimary() [2/2]
void Magick::Image::chromaRedPrimary (double * x_, double * y_) const
chromaWhitePoint() [1/2]
void Magick::Image::chromaWhitePoint (const double x_, const double y_)
chromaWhitePoint() [2/2]
void Magick::Image::chromaWhitePoint (double * x_, double * y_) const
classType() [1/2]
void Magick::Image::classType (const ClassType class_)
classType() [2/2]
Magick::ClassType Magick::Image::classType (void) const inline
clipMask() [1/2]
void Magick::Image::clipMask (const Image & clipMask_)
clipMask() [2/2]
Image Magick::Image::clipMask (void) const
colorFuzz() [1/2]
void Magick::Image::colorFuzz (const double fuzz_)
colorFuzz() [2/2]
double Magick::Image::colorFuzz (void) const
colorize() [1/2]
void Magick::Image::colorize (const unsigned int opacity_, const Color & penColor_)
colorize() [2/2]
void Magick::Image::colorize (const unsigned int opacityRed_, const unsigned int opacityGreen_, const unsigned int opacityBlue_, const Color & penColor_)
colorMap() [1/2]
Color Magick::Image::colorMap (const unsigned int index_) const
colorMap() [2/2]
void Magick::Image::colorMap (const unsigned int index_, const Color & color_)
colorMapSize() [1/3]
void Magick::Image::colorMapSize (const unsigned int entries_)
colorMapSize() [2/3]
unsigned int Magick::Image::colorMapSize (void)
colorMapSize() [3/3]
unsigned int Magick::Image::colorMapSize (void) const
colorMatrix()
void Magick::Image::colorMatrix (const unsigned int order_, const double * color_matrix_)
colorSpace() [1/2]
void Magick::Image::colorSpace (const ColorspaceType colorSpace_)
colorSpace() [2/2]
ColorspaceType Magick::Image::colorSpace (void) const
columns()
unsigned int Magick::Image::columns (void) const inline
comment() [1/2]
void Magick::Image::comment (const std::string & comment_)
comment() [2/2]
std::string Magick::Image::comment (void) const
compare()
bool Magick::Image::compare (const Image & reference_)
compose() [1/2]
void Magick::Image::compose (const CompositeOperator compose_)
compose() [2/2]
CompositeOperator Magick::Image::compose (void) const
composite() [1/3]
void Magick::Image::composite (const Image & compositeImage_, const Geometry & offset_, const CompositeOperator compose_ = InCompositeOp)
composite() [2/3]
void Magick::Image::composite (const Image & compositeImage_, const GravityType gravity_, const CompositeOperator compose_ = InCompositeOp)
composite() [3/3]
void Magick::Image::composite (const Image & compositeImage_, const int xOffset_, const int yOffset_, const CompositeOperator compose_ = InCompositeOp)
compressType() [1/2]
void Magick::Image::compressType (const CompressionType compressType_)
compressType() [2/2]
CompressionType Magick::Image::compressType (void) const
constImage()
const MagickLib::Image * Magick::Image::constImage (void) const
Referenced by classType(), columns(), and rows().
constImageInfo()
const MagickLib::ImageInfo * Magick::Image::constImageInfo (void) const
constOptions()
const Options * Magick::Image::constOptions (void) const
constQuantizeInfo()
const MagickLib::QuantizeInfo * Magick::Image::constQuantizeInfo (void) const
contrast()
void Magick::Image::contrast (const unsigned int sharpen_)
convolve()
void Magick::Image::convolve (const unsigned int order_, const double * kernel_)
crop()
void Magick::Image::crop (const Geometry & geometry_)
cycleColormap()
void Magick::Image::cycleColormap (const int amount_)
debug() [1/2]
void Magick::Image::debug (const bool flag_)
debug() [2/2]
bool Magick::Image::debug (void) const
defineSet() [1/2]
bool Magick::Image::defineSet (const std::string & magick_, const std::string & key_) const
defineSet() [2/2]
void Magick::Image::defineSet (const std::string & magick_, const std::string & key_, bool flag_)
defineValue() [1/2]
std::string Magick::Image::defineValue (const std::string & magick_, const std::string & key_) const
defineValue() [2/2]
void Magick::Image::defineValue (const std::string & magick_, const std::string & key_, const std::string & value_)
density() [1/2]
void Magick::Image::density (const Geometry & geomery_)
density() [2/2]
Geometry Magick::Image::density (void) const
depth() [1/2]
void Magick::Image::depth (const unsigned int depth_)
depth() [2/2]
unsigned int Magick::Image::depth (void) const
despeckle()
void Magick::Image::despeckle (void)
directory()
std::string Magick::Image::directory (void) const
display()
void Magick::Image::display (void)
draw() [1/2]
void Magick::Image::draw (const Drawable & drawable_)
draw() [2/2]
void Magick::Image::draw (const std::list< Magick::Drawable > & drawable_)
edge()
void Magick::Image::edge (const double radius_ = 0.0)
emboss()
void Magick::Image::emboss (const double radius_ = 0.0, const double sigma_ = 1.0)
endian() [1/2]
void Magick::Image::endian (const EndianType endian_)
endian() [2/2]
EndianType Magick::Image::endian (void) const
enhance()
void Magick::Image::enhance (void)
equalize()
void Magick::Image::equalize (void)
erase()
void Magick::Image::erase (void)
extent() [1/4]
void Magick::Image::extent (const Geometry & geometry_)
extent() [2/4]
void Magick::Image::extent (const Geometry & geometry_, const Color & backgroundColor_)
extent() [3/4]
void Magick::Image::extent (const Geometry & geometry_, const Color & backgroundColor_, const GravityType & gravity_)
extent() [4/4]
void Magick::Image::extent (const Geometry & geometry_, const GravityType & gravity_)
fileName() [1/2]
void Magick::Image::fileName (const std::string & fileName_)
fileName() [2/2]
std::string Magick::Image::fileName (void) const
fileSize()
off_t Magick::Image::fileSize (void) const
fillColor() [1/2]
void Magick::Image::fillColor (const Color & fillColor_)
fillColor() [2/2]
Color Magick::Image::fillColor (void) const
fillPattern() [1/2]
void Magick::Image::fillPattern (const Image & fillPattern_)
fillPattern() [2/2]
Image Magick::Image::fillPattern (void) const
fillRule() [1/2]
void Magick::Image::fillRule (const FillRule & fillRule_)
fillRule() [2/2]
FillRule Magick::Image::fillRule (void) const
filterType() [1/2]
void Magick::Image::filterType (const FilterTypes filterType_)
filterType() [2/2]
FilterTypes Magick::Image::filterType (void) const
flip()
void Magick::Image::flip (void)
floodFillColor() [1/4]
void Magick::Image::floodFillColor (const Geometry & point_, const Color & fillColor_)
floodFillColor() [2/4]
void Magick::Image::floodFillColor (const Geometry & point_, const Color & fillColor_, const Color & borderColor_)
floodFillColor() [3/4]
void Magick::Image::floodFillColor (const unsigned int x_, const unsigned int y_, const Color & fillColor_)
floodFillColor() [4/4]
void Magick::Image::floodFillColor (const unsigned int x_, const unsigned int y_, const Color & fillColor_, const Color & borderColor_)
floodFillOpacity()
void Magick::Image::floodFillOpacity (const unsigned int x_, const unsigned int y_, const unsigned int opacity_, const PaintMethod method_)
floodFillTexture() [1/4]
void Magick::Image::floodFillTexture (const Geometry & point_, const Image & texture_)
floodFillTexture() [2/4]
void Magick::Image::floodFillTexture (const Geometry & point_, const Image & texture_, const Color & borderColor_)
floodFillTexture() [3/4]
void Magick::Image::floodFillTexture (const unsigned int x_, const unsigned int y_, const Image & texture_)
floodFillTexture() [4/4]
void Magick::Image::floodFillTexture (const unsigned int x_, const unsigned int y_, const Image & texture_, const Color & borderColor_)
flop()
void Magick::Image::flop (void)
font() [1/2]
void Magick::Image::font (const std::string & font_)
font() [2/2]
std::string Magick::Image::font (void) const
fontPointsize() [1/2]
void Magick::Image::fontPointsize (const double pointSize_)
fontPointsize() [2/2]
double Magick::Image::fontPointsize (void) const
fontTypeMetrics()
void Magick::Image::fontTypeMetrics (const std::string & text_, TypeMetric * metrics)
format()
std::string Magick::Image::format (void) const
formatExpression()
std::string Magick::Image::formatExpression (const std::string expression)
frame() [1/2]
void Magick::Image::frame (const Geometry & geometry_ = frameGeometryDefault)
frame() [2/2]
void Magick::Image::frame (const unsigned int width_, const unsigned int height_, const int innerBevel_ = 6, const int outerBevel_ = 6)
gamma() [1/3]
void Magick::Image::gamma (const double gamma_)
gamma() [2/3]
void Magick::Image::gamma (const double gammaRed_, const double gammaGreen_, const double gammaBlue_)
gamma() [3/3]
double Magick::Image::gamma (void) const
gaussianBlur()
void Magick::Image::gaussianBlur (const double width_, const double sigma_)
gaussianBlurChannel()
void Magick::Image::gaussianBlurChannel (const ChannelType channel_, const double width_, const double sigma_)
geometry()
Geometry Magick::Image::geometry (void) const
getConstIndexes()
const IndexPacket * Magick::Image::getConstIndexes (void) const
getConstPixels()
const PixelPacket * Magick::Image::getConstPixels (const int x_, const int y_, const unsigned int columns_, const unsigned int rows_) const
getIndexes()
IndexPacket * Magick::Image::getIndexes (void)
getPixels()
PixelPacket * Magick::Image::getPixels (const int x_, const int y_, const unsigned int columns_, const unsigned int rows_)
gifDisposeMethod() [1/2]
void Magick::Image::gifDisposeMethod (const unsigned int disposeMethod_)
gifDisposeMethod() [2/2]
unsigned int Magick::Image::gifDisposeMethod (void) const
haldClut()
void Magick::Image::haldClut (const Image & clutImage_)
iccColorProfile() [1/2]
void Magick::Image::iccColorProfile (const Blob & colorProfile_)
iccColorProfile() [2/2]
Blob Magick::Image::iccColorProfile (void) const
image()
MagickLib::Image *& Magick::Image::image (void)
imageInfo()
MagickLib::ImageInfo * Magick::Image::imageInfo (void)
implode()
void Magick::Image::implode (const double factor_)
interlaceType() [1/2]
void Magick::Image::interlaceType (const InterlaceType interlace_)
interlaceType() [2/2]
InterlaceType Magick::Image::interlaceType (void) const
iptcProfile() [1/2]
void Magick::Image::iptcProfile (const Blob & iptcProfile_)
iptcProfile() [2/2]
Blob Magick::Image::iptcProfile (void) const
isValid() [1/2]
void Magick::Image::isValid (const bool isValid_)
isValid() [2/2]
bool Magick::Image::isValid (void) const
label() [1/2]
void Magick::Image::label (const std::string & label_)
label() [2/2]
std::string Magick::Image::label (void) const
level()
void Magick::Image::level (const double black_point, const double white_point, const double mid_point = 1.0)
levelChannel()
void Magick::Image::levelChannel (const ChannelType channel, const double black_point, const double white_point, const double mid_point = 1.0)
lineWidth() [1/2]
void Magick::Image::lineWidth (const double lineWidth_) inline
lineWidth() [2/2]
double Magick::Image::lineWidth (void) const inline
magick() [1/2]
void Magick::Image::magick (const std::string & magick_)
magick() [2/2]
std::string Magick::Image::magick (void) const
magnify()
void Magick::Image::magnify (void)
map()
void Magick::Image::map (const Image & mapImage_, const bool dither_ = false)
matte() [1/2]
void Magick::Image::matte (const bool matteFlag_)
matte() [2/2]
bool Magick::Image::matte (void) const
matteColor() [1/2]
void Magick::Image::matteColor (const Color & matteColor_)
matteColor() [2/2]
Color Magick::Image::matteColor (void) const
matteFloodfill()
void Magick::Image::matteFloodfill (const Color & target_, const unsigned int opacity_, const int x_, const int y_, const PaintMethod method_)
meanErrorPerPixel()
double Magick::Image::meanErrorPerPixel (void) const
medianFilter()
void Magick::Image::medianFilter (const double radius_ = 0.0)
minify()
void Magick::Image::minify (void)
modifyImage()
void Magick::Image::modifyImage (void)
modulate()
void Magick::Image::modulate (const double brightness_, const double saturation_, const double hue_)
modulusDepth() [1/2]
void Magick::Image::modulusDepth (const unsigned int modulusDepth_)
modulusDepth() [2/2]
unsigned int Magick::Image::modulusDepth (void) const
monochrome() [1/2]
void Magick::Image::monochrome (const bool monochromeFlag_)
monochrome() [2/2]
bool Magick::Image::monochrome (void) const
montageGeometry()
Geometry Magick::Image::montageGeometry (void) const
motionBlur()
void Magick::Image::motionBlur (const double radius_, const double sigma_, const double angle_)
negate()
void Magick::Image::negate (const bool grayscale_ = false)
normalize()
void Magick::Image::normalize (void)
normalizedMaxError()
double Magick::Image::normalizedMaxError (void) const
normalizedMeanError()
double Magick::Image::normalizedMeanError (void) const
oilPaint()
void Magick::Image::oilPaint (const double radius_ = 3.0)
opacity()
void Magick::Image::opacity (const unsigned int opacity_)
opaque()
void Magick::Image::opaque (const Color & opaqueColor_, const Color & penColor_)
operator=()
Image & Magick::Image::operator= (const Image & image_)
options()
Options * Magick::Image::options (void)
orientation() [1/2]
void Magick::Image::orientation (const OrientationType orientation_)
orientation() [2/2]
OrientationType Magick::Image::orientation (void) const
page() [1/2]
void Magick::Image::page (const Geometry & pageSize_)
page() [2/2]
Geometry Magick::Image::page (void) const
penColor() [1/2]
void Magick::Image::penColor (const Color & penColor_)
penColor() [2/2]
Color Magick::Image::penColor (void) const
penTexture() [1/2]
void Magick::Image::penTexture (const Image & penTexture_)
penTexture() [2/2]
Image Magick::Image::penTexture (void) const
ping() [1/2]
void Magick::Image::ping (const Blob & blob_)
ping() [2/2]
void Magick::Image::ping (const std::string & imageSpec_)
pixelColor() [1/2]
Color Magick::Image::pixelColor (const unsigned int x_, const unsigned int y_) const
pixelColor() [2/2]
void Magick::Image::pixelColor (const unsigned int x_, const unsigned int y_, const Color & color_)
process()
void Magick::Image::process (std::string name_, const int argc_, char ** argv_)
profile() [1/2]
Blob Magick::Image::profile (const std::string name_) const
profile() [2/2]
void Magick::Image::profile (const std::string name_, const Blob & colorProfile_)
quality() [1/2]
void Magick::Image::quality (const unsigned int quality_)
quality() [2/2]
unsigned int Magick::Image::quality (void) const
quantize()
void Magick::Image::quantize (const bool measureError_ = false)
quantizeColors() [1/2]
void Magick::Image::quantizeColors (const unsigned int colors_)
quantizeColors() [2/2]
unsigned int Magick::Image::quantizeColors (void) const
quantizeColorSpace() [1/2]
void Magick::Image::quantizeColorSpace (const ColorspaceType colorSpace_)
quantizeColorSpace() [2/2]
ColorspaceType Magick::Image::quantizeColorSpace (void) const
quantizeDither() [1/2]
void Magick::Image::quantizeDither (const bool ditherFlag_)
quantizeDither() [2/2]
bool Magick::Image::quantizeDither (void) const
quantizeInfo()
MagickLib::QuantizeInfo * Magick::Image::quantizeInfo (void)
quantizeTreeDepth() [1/2]
void Magick::Image::quantizeTreeDepth (const unsigned int treeDepth_)
quantizeTreeDepth() [2/2]
unsigned int Magick::Image::quantizeTreeDepth (void) const
quantumOperator() [1/4]
void Magick::Image::quantumOperator (const ChannelType channel_, const QuantumOperator operator_, double rvalue_)
quantumOperator() [2/4]
void Magick::Image::quantumOperator (const ChannelType channel_, const QuantumOperator operator_, Quantum rvalue_)
quantumOperator() [3/4]
void Magick::Image::quantumOperator (const int x_, const int y_, const unsigned int columns_, const unsigned int rows_, const ChannelType channel_, const QuantumOperator operator_, const double rvalue_)
quantumOperator() [4/4]
void Magick::Image::quantumOperator (const int x_, const int y_, const unsigned int columns_, const unsigned int rows_, const ChannelType channel_, const QuantumOperator operator_, const Quantum rvalue_)
quiet() [1/2]
void Magick::Image::quiet (const bool quiet_)
quiet() [2/2]
bool Magick::Image::quiet (void) const
raise()
void Magick::Image::raise (const Geometry & geometry_ = raiseGeometryDefault, const bool raisedFlag_ = false)
randomThreshold()
void Magick::Image::randomThreshold (const Geometry & thresholds_)
randomThresholdChannel()
void Magick::Image::randomThresholdChannel (const Geometry & thresholds_, const ChannelType channel_)
read() [1/8]
void Magick::Image::read (const Blob & blob_)
read() [2/8]
void Magick::Image::read (const Blob & blob_, const Geometry & size_)
read() [3/8]
void Magick::Image::read (const Blob & blob_, const Geometry & size_, const std::string & magick_)
read() [4/8]
void Magick::Image::read (const Blob & blob_, const Geometry & size_, const unsigned int depth_)
read() [5/8]
void Magick::Image::read (const Blob & blob_, const Geometry & size_, const unsigned int depth_, const std::string & magick_)
read() [6/8]
void Magick::Image::read (const Geometry & size_, const std::string & imageSpec_)
read() [7/8]
void Magick::Image::read (const std::string & imageSpec_)
read() [8/8]
void Magick::Image::read (const unsigned int width_, const unsigned int height_, const std::string & map_, const StorageType type_, const void * pixels_)
readPixels()
void Magick::Image::readPixels (const QuantumType quantum_, const unsigned char * source_)
reduceNoise() [1/2]
void Magick::Image::reduceNoise (const double order_)
Referenced by reduceNoise().
reduceNoise() [2/2]
void Magick::Image::reduceNoise (void) inline
registerId()
long Magick::Image::registerId (void)
renderingIntent() [1/2]
void Magick::Image::renderingIntent (const RenderingIntent renderingIntent_)
renderingIntent() [2/2]
RenderingIntent Magick::Image::renderingIntent (void) const
repage()
void Magick::Image::repage ()
replaceImage()
MagickLib::Image * Magick::Image::replaceImage (MagickLib::Image * replacement_)
resize() [1/3]
void Magick::Image::resize (const Geometry & geometry_)
resize() [2/3]
void Magick::Image::resize (const Geometry & geometry_, const FilterTypes filterType_)
resize() [3/3]
void Magick::Image::resize (const Geometry & geometry_, const FilterTypes filterType_, const double blur_)
resolutionUnits() [1/2]
void Magick::Image::resolutionUnits (const ResolutionType resolutionUnits_)
resolutionUnits() [2/2]
ResolutionType Magick::Image::resolutionUnits (void) const
roll() [1/2]
void Magick::Image::roll (const Geometry & roll_)
roll() [2/2]
void Magick::Image::roll (const unsigned int columns_, const unsigned int rows_)
rotate()
void Magick::Image::rotate (const double degrees_)
rows()
unsigned int Magick::Image::rows (void) const inline
sample()
void Magick::Image::sample (const Geometry & geometry_)
scale()
void Magick::Image::scale (const Geometry & geometry_)
scene() [1/2]
void Magick::Image::scene (const unsigned int scene_)
scene() [2/2]
unsigned int Magick::Image::scene (void) const
segment()
void Magick::Image::segment (const double clusterThreshold_ = 1.0, const double smoothingThreshold_ = 1.5)
setPixels()
PixelPacket * Magick::Image::setPixels (const int x_, const int y_, const unsigned int columns_, const unsigned int rows_)
shade()
void Magick::Image::shade (const double azimuth_ = 30, const double elevation_ = 30, const bool colorShading_ = false)
sharpen()
void Magick::Image::sharpen (const double radius_ = 0.0, const double sigma_ = 1.0)
sharpenChannel()
void Magick::Image::sharpenChannel (const ChannelType channel_, const double radius_ = 0.0, const double sigma_ = 1.0)
shave()
void Magick::Image::shave (const Geometry & geometry_)
shear()
void Magick::Image::shear (const double xShearAngle_, const double yShearAngle_)
signature()
std::string Magick::Image::signature (const bool force_ = false) const
size() [1/2]
void Magick::Image::size (const Geometry & geometry_)
size() [2/2]
Geometry Magick::Image::size (void) const
solarize()
void Magick::Image::solarize (const double factor_ = 50.0)
spread()
void Magick::Image::spread (const unsigned int amount_ = 3)
statistics()
void Magick::Image::statistics (ImageStatistics * statistics) const
stegano()
void Magick::Image::stegano (const Image & watermark_)
stereo()
void Magick::Image::stereo (const Image & rightImage_)
strip()
void Magick::Image::strip (void)
strokeAntiAlias() [1/2]
void Magick::Image::strokeAntiAlias (const bool flag_)
strokeAntiAlias() [2/2]
bool Magick::Image::strokeAntiAlias (void) const
strokeColor() [1/2]
void Magick::Image::strokeColor (const Color & strokeColor_)
strokeColor() [2/2]
Color Magick::Image::strokeColor (void) const
strokeDashArray() [1/2]
void Magick::Image::strokeDashArray (const double * strokeDashArray_)
strokeDashArray() [2/2]
const double * Magick::Image::strokeDashArray (void) const
strokeDashOffset() [1/2]
void Magick::Image::strokeDashOffset (const double strokeDashOffset_)
strokeDashOffset() [2/2]
double Magick::Image::strokeDashOffset (void) const
strokeLineCap() [1/2]
void Magick::Image::strokeLineCap (const LineCap lineCap_)
strokeLineCap() [2/2]
LineCap Magick::Image::strokeLineCap (void) const
strokeLineJoin() [1/2]
void Magick::Image::strokeLineJoin (const LineJoin lineJoin_)
strokeLineJoin() [2/2]
LineJoin Magick::Image::strokeLineJoin (void) const
strokeMiterLimit() [1/2]
void Magick::Image::strokeMiterLimit (const unsigned int miterLimit_)
strokeMiterLimit() [2/2]
unsigned int Magick::Image::strokeMiterLimit (void) const
strokePattern() [1/2]
void Magick::Image::strokePattern (const Image & strokePattern_)
strokePattern() [2/2]
Image Magick::Image::strokePattern (void) const
strokeWidth() [1/2]
void Magick::Image::strokeWidth (const double strokeWidth_)
Referenced by lineWidth().
strokeWidth() [2/2]
double Magick::Image::strokeWidth (void) const
Referenced by lineWidth().
subImage() [1/2]
void Magick::Image::subImage (const unsigned int subImage_)
subImage() [2/2]
unsigned int Magick::Image::subImage (void) const
subRange() [1/2]
void Magick::Image::subRange (const unsigned int subRange_)
subRange() [2/2]
unsigned int Magick::Image::subRange (void) const
swirl()
void Magick::Image::swirl (const double degrees_)
syncPixels()
void Magick::Image::syncPixels (void)
textEncoding() [1/2]
void Magick::Image::textEncoding (const std::string & encoding_)
textEncoding() [2/2]
std::string Magick::Image::textEncoding (void) const
texture()
void Magick::Image::texture (const Image & texture_)
threshold()
void Magick::Image::threshold (const double threshold_)
throwImageException() [1/2]
void Magick::Image::throwImageException (MagickLib::ExceptionInfo & exception_) const private
throwImageException() [2/2]
void Magick::Image::throwImageException (void) const
thumbnail()
void Magick::Image::thumbnail (const Geometry & geometry_)
tileName() [1/2]
void Magick::Image::tileName (const std::string & tileName_)
tileName() [2/2]
std::string Magick::Image::tileName (void) const
totalColors()
unsigned long Magick::Image::totalColors (void)
transform() [1/2]
void Magick::Image::transform (const Geometry & imageGeometry_)
transform() [2/2]
void Magick::Image::transform (const Geometry & imageGeometry_, const Geometry & cropGeometry_)
transformOrigin()
void Magick::Image::transformOrigin (const double x_, const double y_)
transformReset()
void Magick::Image::transformReset (void)
transformRotation()
void Magick::Image::transformRotation (const double angle_)
transformScale()
void Magick::Image::transformScale (const double sx_, const double sy_)
transformSkewX()
void Magick::Image::transformSkewX (const double skewx_)
transformSkewY()
void Magick::Image::transformSkewY (const double skewy_)
transparent()
void Magick::Image::transparent (const Color & color_)
trim()
void Magick::Image::trim (void)
type() [1/2]
void Magick::Image::type (const ImageType type_)
type() [2/2]
ImageType Magick::Image::type (void) const
unregisterId()
void Magick::Image::unregisterId (void)
unsharpmask()
void Magick::Image::unsharpmask (const double radius_, const double sigma_, const double amount_, const double threshold_)
unsharpmaskChannel()
void Magick::Image::unsharpmaskChannel (const ChannelType channel_, const double radius_, const double sigma_, const double amount_, const double threshold_)
verbose() [1/2]
void Magick::Image::verbose (const bool verboseFlag_)
verbose() [2/2]
bool Magick::Image::verbose (void) const
view() [1/2]
void Magick::Image::view (const std::string & view_)
view() [2/2]
std::string Magick::Image::view (void) const
wave()
void Magick::Image::wave (const double amplitude_ = 25.0, const double wavelength_ = 150.0)
write() [1/5]
void Magick::Image::write (Blob * blob_)
write() [2/5]
void Magick::Image::write (Blob * blob_, const std::string & magick_)
write() [3/5]
void Magick::Image::write (Blob * blob_, const std::string & magick_, const unsigned int depth_)
write() [4/5]
void Magick::Image::write (const int x_, const int y_, const unsigned int columns_, const unsigned int rows_, const std::string & map_, const StorageType type_, void * pixels_)
write() [5/5]
void Magick::Image::write (const std::string & imageSpec_)
writePixels()
void Magick::Image::writePixels (const QuantumType quantum_, unsigned char * destination_)
x11Display() [1/2]
void Magick::Image::x11Display (const std::string & display_)
x11Display() [2/2]
std::string Magick::Image::x11Display (void) const
xResolution() [1/2]
void Magick::Image::xResolution (const double x_resolution)
xResolution() [2/2]
double Magick::Image::xResolution (void) const
yResolution() [1/2]
void Magick::Image::yResolution (const double y_resolution)
yResolution() [2/2]
double Magick::Image::yResolution (void) const
zoom()
void Magick::Image::zoom (const Geometry & geometry_)
Member Data Documentation
_imgRef
ImageRef* Magick::Image::_imgRef private
The documentation for this class was generated from the following file:
/usr/include/GraphicsMagick/Magick++/Image.h