CHRONOS-LoRa: detail::to_utf8< WChar, Buffer > Class Template Reference
detail::to_utf8< WChar, Buffer > Class Template Reference
#include <format.h>
Public Member Functions
to_utf8 ()
to_utf8 (basic_string_view< WChar > s, to_utf8_error_policy policy=to_utf8_error_policy::abort)
operator string_view () const
auto size () const -> size_t
auto c_str () const -> const char *
auto str () const -> std::string
auto convert (basic_string_view< WChar > s, to_utf8_error_policy policy=to_utf8_error_policy::abort) -> bool
Static Public Member Functions
static auto convert (Buffer &buf, basic_string_view< WChar > s, to_utf8_error_policy policy=to_utf8_error_policy::abort) -> bool
Private Attributes
Buffer buffer_
Constructor & Destructor Documentation
to_utf8() [1/2]
template<typename WChar , typename Buffer = memory_buffer> detail::to_utf8< WChar, Buffer >::to_utf8 () inline
Referenced by detail::write_encoded_tm_str().
to_utf8() [2/2]
template<typename WChar , typename Buffer = memory_buffer> detail::to_utf8< WChar, Buffer >::to_utf8 (basic_string_view< WChar > s, to_utf8_error_policy policy = to_utf8_error_policy::abort) inline explicit
Member Function Documentation
c_str()
template<typename WChar , typename Buffer = memory_buffer> auto detail::to_utf8< WChar, Buffer >::c_str () const -> const char* inline
Referenced by detail::write_encoded_tm_str().
convert() [1/2]
template<typename WChar , typename Buffer = memory_buffer> auto detail::to_utf8< WChar, Buffer >::convert (basic_string_view< WChar > s, to_utf8_error_policy policy = to_utf8_error_policy::abort) -> bool inline
Referenced by detail::write_encoded_tm_str().
convert() [2/2]
template<typename WChar , typename Buffer = memory_buffer> static auto detail::to_utf8< WChar, Buffer >::convert (Buffer & buf, basic_string_view< WChar > s, to_utf8_error_policy policy = to_utf8_error_policy::abort) -> bool inline static
operator string_view()
template<typename WChar , typename Buffer = memory_buffer> detail::to_utf8< WChar, Buffer >::operator string_view () const inline
size()
template<typename WChar , typename Buffer = memory_buffer> auto detail::to_utf8< WChar, Buffer >::size () const -> size_t inline
Referenced by detail::to_utf8< WChar, Buffer >::operator string_view(), detail::to_utf8< WChar, Buffer >::str(), and detail::write_encoded_tm_str().
str()
template<typename WChar , typename Buffer = memory_buffer> auto detail::to_utf8< WChar, Buffer >::str () const -> std::string inline
Member Data Documentation
buffer_
template<typename WChar , typename Buffer = memory_buffer> Buffer detail::to_utf8< WChar, Buffer >::buffer_ private
Referenced by detail::to_utf8< WChar, Buffer >::c_str(), detail::to_utf8< WChar, Buffer >::convert(), detail::to_utf8< WChar, Buffer >::operator string_view(), detail::to_utf8< WChar, Buffer >::size(), and detail::to_utf8< WChar, Buffer >::str().
The documentation for this class was generated from the following file:
thirdparty/fmt/include/fmt/format.h