CHRONOS-LoRa: detail::utf8_to_utf16 Class Reference
detail::utf8_to_utf16 Class Reference
#include <format.h>
Public Member Functions
FMT_API utf8_to_utf16 (string_view s)
operator basic_string_view< wchar_t > () const
auto size () const -> size_t
auto c_str () const -> const wchar_t *
auto str () const -> std::wstring
Private Attributes
basic_memory_buffer< wchar_t > buffer_
Constructor & Destructor Documentation
utf8_to_utf16()
FMT_FUNC detail::utf8_to_utf16::utf8_to_utf16 (string_view s) explicit
Referenced by detail::copy_unit().
Member Function Documentation
c_str()
auto detail::utf8_to_utf16::c_str () const -> const wchar_t* inline
Referenced by detail::copy_unit().
operator basic_string_view< wchar_t >()
detail::utf8_to_utf16::operator basic_string_view< wchar_t > () const inline
size()
auto detail::utf8_to_utf16::size () const -> size_t inline
Referenced by detail::copy_unit(), operator basic_string_view< wchar_t >(), and str().
str()
auto detail::utf8_to_utf16::str () const -> std::wstring inline
Member Data Documentation
buffer_
basic_memory_buffer<wchar_t> detail::utf8_to_utf16::buffer_ private
Referenced by c_str(), operator basic_string_view< wchar_t >(), size(), str(), and utf8_to_utf16().
The documentation for this class was generated from the following files:
thirdparty/fmt/include/fmt/format.h
thirdparty/fmt/include/fmt/format-inl.h