CHRONOS-LoRa: detail::buffer< T > Class Template Reference
detail::buffer< T > Class Template Reference
#include <base.h>
Public Types
using value_type = T
using const_reference = const T &
Public Member Functions
buffer (const buffer &)=delete
void operator= (const buffer &)=delete
auto begin () noexcept -> T *
auto end () noexcept -> T *
auto begin () const noexcept -> const T *
auto end () const noexcept -> const T *
constexpr auto size () const noexcept -> size_t
Returns the size of this buffer.
constexpr auto capacity () const noexcept -> size_t
Returns the capacity of this buffer.
FMT_CONSTEXPR auto data () noexcept -> T *
Returns a pointer to the buffer data (not null-terminated).
FMT_CONSTEXPR auto data () const noexcept -> const T *
FMT_CONSTEXPR void clear ()
Clears this buffer.
FMT_CONSTEXPR void try_resize (size_t count)
FMT_CONSTEXPR void try_reserve (size_t new_capacity)
FMT_CONSTEXPR void push_back (const T &value)
template<typename U >
FMT_CONSTEXPR20 void append (const U *begin, const U *end)
Appends data to the end of the buffer.
template<typename Idx >
FMT_CONSTEXPR auto operator[] (Idx index) -> T &
template<typename Idx >
constexpr auto operator[] (Idx index) const -> const T &
Protected Member Functions
FMT_CONSTEXPR buffer (grow_fun grow, size_t sz) noexcept
constexpr buffer (grow_fun grow, T *p=nullptr, size_t sz=0, size_t cap=0) noexcept
FMT_CONSTEXPR20 ~buffer ()=default
buffer (buffer &&)=default
FMT_CONSTEXPR void set (T *buf_data, size_t buf_capacity) noexcept
Sets the buffer data and capacity.
Private Types
using grow_fun = void(*)(buffer &buf, size_t capacity)
Private Attributes
T * ptr_
size_t size_
size_t capacity_
grow_fun grow_
Detailed Description
template<typename T>
class detail::buffer< T >
A contiguous memory buffer with an optional growing ability. It is an internal class and shouldn't be used directly, only via memory_buffer.
Member Typedef Documentation
const_reference
template<typename T > using detail::buffer< T >::const_reference = const T&
grow_fun
template<typename T > using detail::buffer< T >::grow_fun = void (*)(buffer& buf, size_t capacity) private
value_type
template<typename T > using detail::buffer< T >::value_type = T
Constructor & Destructor Documentation
buffer() [1/4]
template<typename T > FMT_CONSTEXPR detail::buffer< T >::buffer (grow_fun grow, size_t sz) inline protected noexcept
buffer() [2/4]
template<typename T > constexpr detail::buffer< T >::buffer (grow_fun grow, T * p = nullptr, size_t sz = 0, size_t cap = 0) inline constexpr protected noexcept
~buffer()
template<typename T > FMT_CONSTEXPR20 detail::buffer< T >::~buffer () protected default
buffer() [3/4]
template<typename T > detail::buffer< T >::buffer (buffer< T > &&) protected default
buffer() [4/4]
template<typename T > detail::buffer< T >::buffer (const buffer< T > &) delete
Member Function Documentation
append()
template<typename T > template<typename U > FMT_CONSTEXPR20 void detail::buffer< T >::append (const U * begin, const U * end) inline
Appends data to the end of the buffer.
begin() [1/2]
template<typename T > auto detail::buffer< T >::begin () const -> const T* inline noexcept
begin() [2/2]
template<typename T > auto detail::buffer< T >::begin () -> T* inline noexcept
Referenced by detail::tm_writer< OutputIt, Char, Duration >::on_second(), detail::duration_formatter< Char, Rep, Period >::on_second(), and vprint().
capacity()
template<typename T > constexpr auto detail::buffer< T >::capacity () const -> size_t inline constexpr noexcept
Returns the capacity of this buffer.
clear()
template<typename T > FMT_CONSTEXPR void detail::buffer< T >::clear () inline
Clears this buffer.
data() [1/2]
template<typename T > FMT_CONSTEXPR auto detail::buffer< T >::data () const -> const T* inline noexcept
Referenced by detail::bigint::assign().
data() [2/2]
template<typename T > FMT_CONSTEXPR auto detail::buffer< T >::data () -> T* inline noexcept
Returns a pointer to the buffer data (not null-terminated).
Referenced by detail::bigint::align(), detail::bigint::assign(), detail::do_report_error(), formatter< std::error_code >::format(), detail::format_dragon(), detail::format_float(), print(), vformat(), vformat(), vprint(), vprint_buffered(), vprintln(), detail::write_int(), and detail::write_significand().
end() [1/2]
template<typename T > auto detail::buffer< T >::end () const -> const T* inline noexcept
end() [2/2]
template<typename T > auto detail::buffer< T >::end () -> T* inline noexcept
Referenced by detail::tm_writer< OutputIt, Char, Duration >::on_second(), and detail::duration_formatter< Char, Rep, Period >::on_second().
operator=()
template<typename T > void detail::buffer< T >::operator= (const buffer< T > &) delete
operator[]() [1/2]
template<typename T > template<typename Idx > FMT_CONSTEXPR auto detail::buffer< T >::operator[] (Idx index) -> T& inline
operator[]() [2/2]
template<typename T > template<typename Idx > constexpr auto detail::buffer< T >::operator[] (Idx index) const -> const T& inline constexpr
push_back()
template<typename T > FMT_CONSTEXPR void detail::buffer< T >::push_back (const T & value) inline
Referenced by detail::digit_grouping< Char >::apply(), formatter< std::error_code >::format(), detail::format_dragon(), detail::format_float(), detail::format_hexfloat(), detail::bigint::multiply(), detail::bigint::multiply(), detail::bigint::operator<<=(), detail::to_utf8_3bytes(), detail::utf8_to_utf16::utf8_to_utf16(), vprint(), and vprintln().
set()
template<typename T > FMT_CONSTEXPR void detail::buffer< T >::set (T * buf_data, size_t buf_capacity) inline protected noexcept
Sets the buffer data and capacity.
Referenced by detail::file_print_buffer< F, enable_if_t< has_flockfile< F >::value > >::file_print_buffer().
size()
template<typename T > constexpr auto detail::buffer< T >::size () const -> size_t inline constexpr noexcept
Returns the size of this buffer.
Referenced by detail::bigint::align(), detail::digit_grouping< Char >::apply(), detail::bigint::assign(), detail::bigint::divmod_assign(), detail::do_report_error(), formatter< detail::bigint >::format(), formatter< std::error_code >::format(), detail::format_error_code(), detail::format_float(), detail::bigint::multiply(), detail::bigint::multiply(), detail::bigint::num_bigits(), detail::tm_writer< OutputIt, Char, Duration >::on_second(), detail::duration_formatter< Char, Rep, Period >::on_second(), detail::bigint::operator<<=(), print(), detail::bigint::remove_leading_zeros(), detail::utf8_to_utf16::size(), detail::bigint::square(), detail::bigint::subtract_aligned(), vformat(), vformat(), vprint(), vprint_buffered(), vprintln(), detail::write_int(), detail::write_significand(), and detail::file_print_buffer< F, enable_if_t< has_flockfile< F >::value > >::~file_print_buffer().
try_reserve()
template<typename T > FMT_CONSTEXPR void detail::buffer< T >::try_reserve (size_t new_capacity) inline
Referenced by detail::buffer< T >::push_back(), and detail::buffer< T >::try_resize().
try_resize()
template<typename T > FMT_CONSTEXPR void detail::buffer< T >::try_resize (size_t count) inline
Referenced by detail::format_dragon(), detail::format_error_code(), and detail::format_float().
Member Data Documentation
capacity_
template<typename T > size_t detail::buffer< T >::capacity_ private
Referenced by detail::buffer< T >::append(), detail::buffer< T >::buffer(), detail::buffer< T >::buffer(), detail::buffer< T >::capacity(), detail::buffer< T >::set(), detail::buffer< T >::try_reserve(), and detail::buffer< T >::try_resize().
grow_
template<typename T > grow_fun detail::buffer< T >::grow_ private
Referenced by detail::buffer< T >::append(), detail::buffer< T >::buffer(), detail::buffer< T >::buffer(), and detail::buffer< T >::try_reserve().
ptr_
template<typename T > T* detail::buffer< T >::ptr_ private
Referenced by detail::buffer< T >::append(), detail::buffer< T >::begin(), detail::buffer< T >::begin(), detail::buffer< T >::buffer(), detail::buffer< T >::buffer(), detail::buffer< T >::data(), detail::buffer< T >::data(), detail::buffer< T >::end(), detail::buffer< T >::end(), detail::buffer< T >::operator[](), detail::buffer< T >::operator[](), detail::buffer< T >::push_back(), and detail::buffer< T >::set().
size_
template<typename T > size_t detail::buffer< T >::size_ private
Referenced by detail::buffer< T >::append(), detail::buffer< T >::buffer(), detail::buffer< T >::buffer(), detail::buffer< T >::clear(), detail::buffer< T >::end(), detail::buffer< T >::end(), detail::buffer< T >::push_back(), detail::buffer< T >::size(), and detail::buffer< T >::try_resize().
The documentation for this class was generated from the following file:
thirdparty/fmt/include/fmt/base.h