CHRONOS-LoRa: basic_string_view< Char > Class Template Reference
basic_string_view< Char > Class Template Reference
#include <base.h>
Public Types
using value_type = Char
using iterator = const Char *
Public Member Functions
constexpr basic_string_view () noexcept
constexpr basic_string_view (const Char *s, size_t count) noexcept
FMT_CONSTEXPR basic_string_view (const Char *s)
template<typename S , FMT_ENABLE_IF(detail::is_std_string_like< S >::value && std::is_same< typename S::value_type, Char >::value) >
constexpr basic_string_view (const S &s) noexcept
constexpr auto data () const noexcept -> const Char *
constexpr auto size () const noexcept -> size_t
constexpr auto begin () const noexcept -> iterator
constexpr auto end () const noexcept -> iterator
constexpr auto operator[] (size_t pos) const noexcept -> const Char &
FMT_CONSTEXPR void remove_prefix (size_t n) noexcept
FMT_CONSTEXPR auto starts_with (basic_string_view sv) const noexcept -> bool
FMT_CONSTEXPR auto starts_with (Char c) const noexcept -> bool
FMT_CONSTEXPR auto starts_with (const Char *s) const -> bool
FMT_CONSTEXPR auto compare (basic_string_view other) const -> int
Private Attributes
const Char * data_
size_t size_
Friends
FMT_CONSTEXPR friend auto operator== (basic_string_view lhs, basic_string_view rhs) -> bool
auto operator!= (basic_string_view lhs, basic_string_view rhs) -> bool
auto operator< (basic_string_view lhs, basic_string_view rhs) -> bool
auto operator<= (basic_string_view lhs, basic_string_view rhs) -> bool
auto operator> (basic_string_view lhs, basic_string_view rhs) -> bool
auto operator>= (basic_string_view lhs, basic_string_view rhs) -> bool
Detailed Description
template<typename Char>
class basic_string_view< Char >
An implementation of std::basic_string_view for pre-C++17 providing a subset of the API. fmt::basic_string_view is used in the public API even if std::basic_string_view is available to prevent issues when a library is compiled with a different -std option than the client code (which is not recommended).
Member Typedef Documentation
iterator
template<typename Char > using basic_string_view< Char >::iterator = const Char*
value_type
template<typename Char > using basic_string_view< Char >::value_type = Char
Constructor & Destructor Documentation
basic_string_view() [1/4]
template<typename Char > constexpr basic_string_view< Char >::basic_string_view () inline constexpr noexcept
basic_string_view() [2/4]
template<typename Char > constexpr basic_string_view< Char >::basic_string_view (const Char * s, size_t count) inline constexpr noexcept
Referenced by detail::find_escape(), detail::for_each_codepoint(), formatter< std::error_code >::format(), detail::utf8_to_utf16::operator basic_string_view< wchar_t >(), print(), vprint(), vprint_buffered(), vprintln(), detail::write_encoded_tm_str(), detail::write_int(), and detail::write_significand().
basic_string_view() [3/4]
template<typename Char > FMT_CONSTEXPR basic_string_view< Char >::basic_string_view (const Char * s) inline
Referenced by detail::ansi_color_escape< Char >::ansi_color_escape(), detail::to_utf8< WChar, Buffer >::convert(), formatter< detail::styled_arg< T >, Char >::format(), formatter< std::error_code >::format(), formatter< T, char, typename std::enable_if< std::is_base_of< std::exception, T >::value >::type >::format(), detail::format_duration_unit(), and detail::reset_color().
basic_string_view() [4/4]
template<typename Char > template<typename S , FMT_ENABLE_IF(detail::is_std_string_like< S >::value && std::is_same< typename S::value_type, Char >::value) > constexpr basic_string_view< Char >::basic_string_view (const S & s) inline constexpr noexcept
Member Function Documentation
begin()
template<typename Char > constexpr auto basic_string_view< Char >::begin () const -> iterator inline constexpr noexcept
Referenced by detail::copy_unit(), detail::find_escape(), formatter< detail::styled_arg< T >, Char >::format(), detail::reset_color(), detail::write(), and detail::write_codecvt().
compare()
template<typename Char > FMT_CONSTEXPR auto basic_string_view< Char >::compare (basic_string_view< Char > other) const -> int inline
data()
template<typename Char > constexpr auto basic_string_view< Char >::data () const -> const Char* inline constexpr noexcept
Referenced by detail::for_each_codepoint(), format_facet< Locale >::format_facet(), detail::print(), detail::vformat_to(), and detail::write_encoded_tm_str().
end()
template<typename Char > constexpr auto basic_string_view< Char >::end () const -> iterator inline constexpr noexcept
Referenced by detail::copy_unit(), detail::find_escape(), formatter< detail::styled_arg< T >, Char >::format(), detail::reset_color(), detail::write(), and detail::write_codecvt().
operator[]()
template<typename Char > constexpr auto basic_string_view< Char >::operator[] (size_t pos) const -> const Char& inline constexpr noexcept
remove_prefix()
template<typename Char > FMT_CONSTEXPR void basic_string_view< Char >::remove_prefix (size_t n) inline noexcept
size()
template<typename Char > constexpr auto basic_string_view< Char >::size () const -> size_t inline constexpr noexcept
Referenced by detail::for_each_codepoint(), detail::format_error_code(), format_facet< Locale >::format_facet(), detail::print(), detail::vformat_to(), detail::write(), and detail::write_encoded_tm_str().
starts_with() [1/3]
template<typename Char > FMT_CONSTEXPR auto basic_string_view< Char >::starts_with (basic_string_view< Char > sv) const -> bool inline noexcept
starts_with() [2/3]
template<typename Char > FMT_CONSTEXPR auto basic_string_view< Char >::starts_with (Char c) const -> bool inline noexcept
starts_with() [3/3]
template<typename Char > FMT_CONSTEXPR auto basic_string_view< Char >::starts_with (const Char * s) const -> bool inline
Friends And Related Symbol Documentation
operator!=
template<typename Char > auto operator!= (basic_string_view< Char > lhs, basic_string_view< Char > rhs) -> bool friend
operator<
template<typename Char > auto operator< (basic_string_view< Char > lhs, basic_string_view< Char > rhs) -> bool friend
operator<=
template<typename Char > auto operator<= (basic_string_view< Char > lhs, basic_string_view< Char > rhs) -> bool friend
operator==
template<typename Char > FMT_CONSTEXPR friend auto operator== (basic_string_view< Char > lhs, basic_string_view< Char > rhs) -> bool friend
Referenced by detail::ansi_color_escape< Char >::ansi_color_escape().
operator>
template<typename Char > auto operator> (basic_string_view< Char > lhs, basic_string_view< Char > rhs) -> bool friend
operator>=
template<typename Char > auto operator>= (basic_string_view< Char > lhs, basic_string_view< Char > rhs) -> bool friend
Member Data Documentation
data_
template<typename Char > const Char* basic_string_view< Char >::data_ private
Referenced by basic_string_view< Char >::basic_string_view(), basic_string_view< Char >::basic_string_view(), basic_string_view< Char >::basic_string_view(), basic_string_view< Char >::basic_string_view(), basic_string_view< Char >::begin(), basic_string_view< Char >::compare(), basic_string_view< Char >::data(), basic_string_view< Char >::end(), basic_string_view< Char >::operator[](), basic_string_view< Char >::remove_prefix(), basic_string_view< Char >::starts_with(), and basic_string_view< Char >::starts_with().
size_
template<typename Char > size_t basic_string_view< Char >::size_ private
Referenced by basic_string_view< Char >::basic_string_view(), basic_string_view< Char >::basic_string_view(), basic_string_view< Char >::basic_string_view(), basic_string_view< Char >::basic_string_view(), basic_string_view< Char >::compare(), basic_string_view< Char >::end(), basic_string_view< Char >::remove_prefix(), basic_string_view< Char >::size(), basic_string_view< Char >::starts_with(), and basic_string_view< Char >::starts_with().
The documentation for this class was generated from the following file:
thirdparty/fmt/include/fmt/base.h