CHRONOS-LoRa: format_int Class Reference
format_int Class Reference
A fast integer formatter.
#include <format.h>
Public Member Functions
FMT_CONSTEXPR20 format_int (int value)
FMT_CONSTEXPR20 format_int (long value)
FMT_CONSTEXPR20 format_int (long long value)
FMT_CONSTEXPR20 format_int (unsigned value)
FMT_CONSTEXPR20 format_int (unsigned long value)
FMT_CONSTEXPR20 format_int (ullong value)
FMT_CONSTEXPR20 auto size () const -> size_t
Returns the number of characters written to the output buffer.
FMT_CONSTEXPR20 auto data () const -> const char *
FMT_CONSTEXPR20 auto c_str () const -> const char *
auto str () const -> std::string
Returns the content of the output buffer as an std::string.
Private Types
enum { buffer_size = std::numeric_limits<ullong>::digits10 + 3 }
Private Member Functions
template<typename UInt >
FMT_CONSTEXPR20 auto format_unsigned (UInt value) -> char *
template<typename Int >
FMT_CONSTEXPR20 auto format_signed (Int value) -> char *
Private Attributes
char buffer_ [buffer_size]
char * str_
Detailed Description
A fast integer formatter.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
buffer_size
Constructor & Destructor Documentation
format_int() [1/6]
FMT_CONSTEXPR20 format_int::format_int (int value) inline explicit
format_int() [2/6]
FMT_CONSTEXPR20 format_int::format_int (long value) inline explicit
format_int() [3/6]
FMT_CONSTEXPR20 format_int::format_int (long long value) inline explicit
format_int() [4/6]
FMT_CONSTEXPR20 format_int::format_int (unsigned value) inline explicit
format_int() [5/6]
FMT_CONSTEXPR20 format_int::format_int (unsigned long value) inline explicit
format_int() [6/6]
FMT_CONSTEXPR20 format_int::format_int (ullong value) inline explicit
Member Function Documentation
c_str()
FMT_CONSTEXPR20 auto format_int::c_str () const -> const char* inline
Returns a pointer to the output buffer content with terminating null character appended.
data()
FMT_CONSTEXPR20 auto format_int::data () const -> const char* inline
Returns a pointer to the output buffer content. No terminating null character is appended.
format_signed()
template<typename Int > FMT_CONSTEXPR20 auto format_int::format_signed (Int value) -> char* inline private
Referenced by format_int(), format_int(), and format_int().
format_unsigned()
template<typename UInt > FMT_CONSTEXPR20 auto format_int::format_unsigned (UInt value) -> char* inline private
Referenced by format_int(), format_int(), and format_int().
size()
FMT_CONSTEXPR20 auto format_int::size () const -> size_t inline
Returns the number of characters written to the output buffer.
Referenced by str().
str()
auto format_int::str () const -> std::string inline
Returns the content of the output buffer as an std::string.
Member Data Documentation
buffer_
char format_int::buffer_[buffer_size] mutable private
Referenced by c_str(), format_unsigned(), and size().
str_
char* format_int::str_ private
Referenced by c_str(), data(), format_int(), format_int(), format_int(), format_int(), format_int(), format_int(), size(), and str().
The documentation for this class was generated from the following file:
thirdparty/fmt/include/fmt/format.h