CHRONOS-LoRa: detail::counting_buffer< T > Class Template Reference
detail::counting_buffer< T > Class Template Reference
#include <base.h>
Public Member Functions
constexpr counting_buffer ()
constexpr auto count () const noexcept -> size_t
Public Member Functions inherited from detail::buffer< T >
buffer (const buffer &)=delete
void operator= (const buffer &)=delete
auto begin () noexcept -> T *
auto end () noexcept -> T *
auto begin () const noexcept -> const T *
auto end () const noexcept -> const T *
constexpr auto size () const noexcept -> size_t
Returns the size of this buffer.
constexpr auto capacity () const noexcept -> size_t
Returns the capacity of this buffer.
FMT_CONSTEXPR auto data () noexcept -> T *
Returns a pointer to the buffer data (not null-terminated).
FMT_CONSTEXPR auto data () const noexcept -> const T *
FMT_CONSTEXPR void clear ()
Clears this buffer.
FMT_CONSTEXPR void try_resize (size_t count)
FMT_CONSTEXPR void try_reserve (size_t new_capacity)
FMT_CONSTEXPR void push_back (const T &value)
template<typename U >
FMT_CONSTEXPR20 void append (const U *begin, const U *end)
Appends data to the end of the buffer.
template<typename Idx >
FMT_CONSTEXPR auto operator[] (Idx index) -> T &
template<typename Idx >
constexpr auto operator[] (Idx index) const -> const T &
Private Types
enum { buffer_size = 256 }
Static Private Member Functions
static FMT_CONSTEXPR void grow (buffer< T > &buf, size_t)
Private Attributes
T data_ [buffer_size]
size_t count_ = 0
Additional Inherited Members
Public Types inherited from detail::buffer< T >
using value_type = T
using const_reference = const T &
Protected Member Functions inherited from detail::buffer< T >
FMT_CONSTEXPR buffer (grow_fun grow, size_t sz) noexcept
constexpr buffer (grow_fun grow, T *p=nullptr, size_t sz=0, size_t cap=0) noexcept
FMT_CONSTEXPR20 ~buffer ()=default
buffer (buffer &&)=default
FMT_CONSTEXPR void set (T *buf_data, size_t buf_capacity) noexcept
Sets the buffer data and capacity.
Member Enumeration Documentation
anonymous enum
template<typename T = char> anonymous enum private
Enumerator
buffer_size
Constructor & Destructor Documentation
counting_buffer()
template<typename T = char> constexpr detail::counting_buffer< T >::counting_buffer () inline constexpr
Referenced by formatted_size(), formatted_size(), and formatted_size().
Member Function Documentation
count()
template<typename T = char> constexpr auto detail::counting_buffer< T >::count () const -> size_t inline constexpr noexcept
Referenced by formatted_size(), formatted_size(), formatted_size(), and detail::write().
grow()
template<typename T = char> static FMT_CONSTEXPR void detail::counting_buffer< T >::grow (buffer< T > & buf, size_t) inline static private
Referenced by detail::counting_buffer< T >::counting_buffer().
Member Data Documentation
count_
template<typename T = char> size_t detail::counting_buffer< T >::count_ = 0 private
Referenced by detail::counting_buffer< T >::count().
data_
template<typename T = char> T detail::counting_buffer< T >::data_[buffer_size] private
Referenced by detail::counting_buffer< T >::counting_buffer().
The documentation for this class was generated from the following file:
thirdparty/fmt/include/fmt/base.h