CHRONOS-LoRa: detail::digit_grouping< Char > Class Template Reference
detail::digit_grouping< Char > Class Template Reference
#include <format.h>
Classes
struct next_state
Public Member Functions
digit_grouping (locale_ref loc, bool localized=true)
digit_grouping (std::string grouping, std::basic_string< Char > sep)
auto has_separator () const -> bool
auto count_separators (int num_digits) const -> int
template<typename Out , typename C >
auto apply (Out out, basic_string_view< C > digits) const -> Out
Private Member Functions
auto initial_state () const -> next_state
auto next (next_state &state) const -> int
Private Attributes
std::string grouping_
std::basic_string< Char > thousands_sep_
Constructor & Destructor Documentation
digit_grouping() [1/2]
template<typename Char > detail::digit_grouping< Char >::digit_grouping (locale_ref loc, bool localized = true) inline explicit
digit_grouping() [2/2]
template<typename Char > detail::digit_grouping< Char >::digit_grouping (std::string grouping, std::basic_string< Char > sep) inline
Referenced by formatter< group_digits_view< T > >::format().
Member Function Documentation
apply()
template<typename Char > template<typename Out , typename C > auto detail::digit_grouping< Char >::apply (Out out, basic_string_view< C > digits) const -> Out inline
count_separators()
template<typename Char > auto detail::digit_grouping< Char >::count_separators (int num_digits) const -> int inline
has_separator()
template<typename Char > auto detail::digit_grouping< Char >::has_separator () const -> bool inline
initial_state()
template<typename Char > auto detail::digit_grouping< Char >::initial_state () const -> next_state inline private
Referenced by detail::digit_grouping< Char >::apply(), and detail::digit_grouping< Char >::count_separators().
next()
template<typename Char > auto detail::digit_grouping< Char >::next (next_state & state) const -> int inline private
Referenced by detail::digit_grouping< Char >::apply(), and detail::digit_grouping< Char >::count_separators().
Member Data Documentation
grouping_
template<typename Char > std::string detail::digit_grouping< Char >::grouping_ private
Referenced by detail::digit_grouping< Char >::digit_grouping(), detail::digit_grouping< Char >::digit_grouping(), detail::digit_grouping< Char >::initial_state(), and detail::digit_grouping< Char >::next().
thousands_sep_
template<typename Char > std::basic_string<Char> detail::digit_grouping< Char >::thousands_sep_ private
Referenced by detail::digit_grouping< Char >::apply(), detail::digit_grouping< Char >::digit_grouping(), detail::digit_grouping< Char >::digit_grouping(), detail::digit_grouping< Char >::has_separator(), and detail::digit_grouping< Char >::next().
The documentation for this class was generated from the following file:
thirdparty/fmt/include/fmt/format.h