CHRONOS-LoRa: text_style Class Reference
text_style Class Reference
A text style consisting of foreground and background colors and emphasis.
#include <color.h>
Public Member Functions
FMT_CONSTEXPR text_style (emphasis em=emphasis()) noexcept
FMT_CONSTEXPR auto operator|= (text_style rhs) -> text_style &
FMT_CONSTEXPR auto operator== (text_style rhs) const noexcept -> bool
FMT_CONSTEXPR auto operator!= (text_style rhs) const noexcept -> bool
FMT_CONSTEXPR auto has_foreground () const noexcept -> bool
FMT_CONSTEXPR auto has_background () const noexcept -> bool
FMT_CONSTEXPR auto has_emphasis () const noexcept -> bool
FMT_CONSTEXPR auto get_foreground () const noexcept -> detail::color_type
FMT_CONSTEXPR auto get_background () const noexcept -> detail::color_type
FMT_CONSTEXPR auto get_emphasis () const noexcept -> emphasis
Private Member Functions
FMT_CONSTEXPR text_style (uint64_t style) noexcept
Private Attributes
uint64_t style_ = 0
Friends
FMT_CONSTEXPR auto operator| (text_style lhs, text_style rhs) -> text_style
FMT_CONSTEXPR auto fg (detail::color_type foreground) noexcept -> text_style
Creates a text style from the foreground (text) color.
FMT_CONSTEXPR auto bg (detail::color_type background) noexcept -> text_style
Creates a text style from the background color.
Detailed Description
A text style consisting of foreground and background colors and emphasis.
Constructor & Destructor Documentation
text_style() [1/2]
FMT_CONSTEXPR text_style::text_style (emphasis em = emphasis()) inline noexcept
Referenced by operator|(), and detail::vformat_to().
text_style() [2/2]
FMT_CONSTEXPR text_style::text_style (uint64_t style) inline private noexcept
Member Function Documentation
get_background()
FMT_CONSTEXPR auto text_style::get_background () const -> detail::color_type inline noexcept
Referenced by detail::vformat_to().
get_emphasis()
FMT_CONSTEXPR auto text_style::get_emphasis () const -> emphasis inline noexcept
Referenced by detail::vformat_to().
get_foreground()
FMT_CONSTEXPR auto text_style::get_foreground () const -> detail::color_type inline noexcept
Referenced by detail::vformat_to().
has_background()
FMT_CONSTEXPR auto text_style::has_background () const -> bool inline noexcept
Referenced by get_background(), and detail::vformat_to().
has_emphasis()
FMT_CONSTEXPR auto text_style::has_emphasis () const -> bool inline noexcept
Referenced by get_emphasis(), and detail::vformat_to().
has_foreground()
FMT_CONSTEXPR auto text_style::has_foreground () const -> bool inline noexcept
Referenced by get_foreground(), and detail::vformat_to().
operator!=()
FMT_CONSTEXPR auto text_style::operator!= (text_style rhs) const -> bool inline noexcept
Referenced by detail::vformat_to().
operator==()
FMT_CONSTEXPR auto text_style::operator== (text_style rhs) const -> bool inline noexcept
Referenced by operator!=().
operator|=()
FMT_CONSTEXPR auto text_style::operator|= (text_style rhs) -> text_style& inline
Friends And Related Symbol Documentation
bg
FMT_CONSTEXPR auto bg (detail::color_type background) -> text_style friend
Creates a text style from the background color.
fg
FMT_CONSTEXPR auto fg (detail::color_type foreground) -> text_style friend
Creates a text style from the foreground (text) color.
operator|
FMT_CONSTEXPR auto operator| (text_style lhs, text_style rhs) -> text_style friend
Referenced by operator|().
Member Data Documentation
style_
uint64_t text_style::style_ = 0 private
Referenced by get_background(), get_emphasis(), get_foreground(), has_background(), has_emphasis(), has_foreground(), operator==(), operator|=(), text_style(), and text_style().
The documentation for this class was generated from the following file:
thirdparty/fmt/include/fmt/color.h