CHRONOS-LoRa: basic_specs Class Reference
basic_specs Class Reference
#include <base.h>
Public Member Functions
constexpr auto type () const -> presentation_type
FMT_CONSTEXPR void set_type (presentation_type t)
constexpr auto align () const -> align
FMT_CONSTEXPR void set_align (fmt::align a)
constexpr auto dynamic_width () const -> arg_id_kind
FMT_CONSTEXPR void set_dynamic_width (arg_id_kind w)
FMT_CONSTEXPR auto dynamic_precision () const -> arg_id_kind
FMT_CONSTEXPR void set_dynamic_precision (arg_id_kind p)
constexpr auto dynamic () const -> bool
constexpr auto sign () const -> sign
FMT_CONSTEXPR void set_sign (fmt::sign s)
constexpr auto upper () const -> bool
FMT_CONSTEXPR void set_upper ()
constexpr auto alt () const -> bool
FMT_CONSTEXPR void set_alt ()
FMT_CONSTEXPR void clear_alt ()
constexpr auto localized () const -> bool
FMT_CONSTEXPR void set_localized ()
constexpr auto fill_size () const -> size_t
template<typename Char , FMT_ENABLE_IF(std::is_same< Char, char >::value) >
constexpr auto fill () const -> const Char *
template<typename Char , FMT_ENABLE_IF(!std::is_same< Char, char >::value) >
constexpr auto fill () const -> const Char *
template<typename Char >
constexpr auto fill_unit () const -> Char
FMT_CONSTEXPR void set_fill (char c)
template<typename Char >
FMT_CONSTEXPR void set_fill (basic_string_view< Char > s)
FMT_CONSTEXPR void copy_fill_from (const basic_specs &specs)
Private Types
enum : unsigned {
type_mask = 0x00007 , align_mask = 0x00038 , width_mask = 0x000C0 , precision_mask = 0x00300 ,
sign_mask = 0x00C00 , uppercase_mask = 0x01000 , alternate_mask = 0x02000 , localized_mask = 0x04000 ,
fill_size_mask = 0x38000 , align_shift = 3 , width_shift = 6 , precision_shift = 8 ,
sign_shift = 10 , fill_size_shift = 15 , max_fill_size = 4
}
Private Member Functions
FMT_CONSTEXPR void set_fill_size (size_t size)
Private Attributes
unsigned data_ = 1 << fill_size_shift
char fill_data_ [max_fill_size] = {' '}
Member Enumeration Documentation
anonymous enum
anonymous enum : unsigned private
Enumerator
type_mask
align_mask
width_mask
precision_mask
sign_mask
uppercase_mask
alternate_mask
localized_mask
fill_size_mask
align_shift
width_shift
precision_shift
sign_shift
fill_size_shift
max_fill_size
Member Function Documentation
align()
constexpr auto basic_specs::align () const -> align inline constexpr
Referenced by detail::check_char_specs(), detail::printf_arg_formatter< Char >::operator()(), detail::size_padding::size_padding(), detail::vprintf(), nested_formatter< T, Char >::write_padded(), and detail::write_padded().
alt()
constexpr auto basic_specs::alt () const -> bool inline constexpr
Referenced by detail::check_char_specs(), detail::do_write_float(), detail::format_float(), detail::format_hexfloat(), detail::vprintf(), detail::write_int(), and detail::write_int().
clear_alt()
FMT_CONSTEXPR void basic_specs::clear_alt () inline
Referenced by detail::printf_arg_formatter< Char >::operator()(), and detail::vprintf().
copy_fill_from()
FMT_CONSTEXPR void basic_specs::copy_fill_from (const basic_specs & specs) inline
Referenced by formatter< std::complex< T >, Char >::format(), and nested_formatter< T, Char >::write_padded().
dynamic()
constexpr auto basic_specs::dynamic () const -> bool inline constexpr
dynamic_precision()
FMT_CONSTEXPR auto basic_specs::dynamic_precision () const -> arg_id_kind inline
Referenced by formatter< bytes >::format(), detail::native_formatter< T, Char, TYPE >::format(), formatter< group_digits_view< T > >::format(), and formatter< std::chrono::duration< Rep, Period >, Char >::format().
dynamic_width()
constexpr auto basic_specs::dynamic_width () const -> arg_id_kind inline constexpr
Referenced by formatter< std::tm, Char >::do_format(), formatter< bytes >::format(), formatter< std::error_code >::format(), detail::native_formatter< T, Char, TYPE >::format(), formatter< group_digits_view< T > >::format(), and formatter< std::chrono::duration< Rep, Period >, Char >::format().
fill() [1/2]
template<typename Char , FMT_ENABLE_IF(std::is_same< Char, char >::value) > constexpr auto basic_specs::fill () const -> const Char* inline constexpr
fill() [2/2]
template<typename Char , FMT_ENABLE_IF(!std::is_same< Char, char >::value) > constexpr auto basic_specs::fill () const -> const Char* inline constexpr
fill_size()
constexpr auto basic_specs::fill_size () const -> size_t inline constexpr
Referenced by copy_fill_from(), detail::fill(), detail::write_nonfinite(), and detail::write_padded().
fill_unit()
template<typename Char > constexpr auto basic_specs::fill_unit () const -> Char inline constexpr
localized()
constexpr auto basic_specs::localized () const -> bool inline constexpr
Referenced by formatter< std::tm, Char >::do_format(), detail::do_write_float(), formatter< std::chrono::duration< Rep, Period >, Char >::format(), formatter< std::tm, Char >::localized(), detail::write(), and detail::write().
set_align()
FMT_CONSTEXPR void basic_specs::set_align (fmt::align a) inline
Referenced by formatter< std::complex< T >, Char >::format(), detail::printf_arg_formatter< Char >::operator()(), detail::printf_width_handler::operator()(), detail::parse_flags(), detail::vprintf(), and nested_formatter< T, Char >::write_padded().
set_alt()
FMT_CONSTEXPR void basic_specs::set_alt () inline
Referenced by detail::parse_flags().
set_dynamic_precision()
FMT_CONSTEXPR void basic_specs::set_dynamic_precision (arg_id_kind p) inline
Referenced by detail::parse_precision().
set_dynamic_width()
FMT_CONSTEXPR void basic_specs::set_dynamic_width (arg_id_kind w) inline
Referenced by detail::parse_width().
set_fill() [1/2]
template<typename Char > FMT_CONSTEXPR void basic_specs::set_fill (basic_string_view< Char > s) inline
set_fill() [2/2]
FMT_CONSTEXPR void basic_specs::set_fill (char c) inline
Referenced by detail::printf_arg_formatter< Char >::operator()(), detail::parse_flags(), detail::parse_header(), detail::vprintf(), and detail::write_nonfinite().
set_fill_size()
FMT_CONSTEXPR void basic_specs::set_fill_size (size_t size) inline private
Referenced by copy_fill_from(), set_fill(), and set_fill().
set_localized()
FMT_CONSTEXPR void basic_specs::set_localized () inline
Referenced by formatter< std::tm, Char >::do_parse(), formatter< std::chrono::duration< Rep, Period >, Char >::parse(), and formatter< std::tm, Char >::set_localized().
set_sign()
FMT_CONSTEXPR void basic_specs::set_sign (fmt::sign s) inline
Referenced by detail::printf_arg_formatter< Char >::operator()(), and detail::parse_flags().
set_type()
FMT_CONSTEXPR void basic_specs::set_type (presentation_type t) inline
Referenced by formatter< std::error_code >::parse(), detail::parse_format_specs(), detail::vprintf(), and range_formatter< T, Char, enable_if_t< conjunction< std::is_same< T, remove_cvref_t< T > >, is_formattable< T, Char > >::value > >::write_debug_string().
set_upper()
FMT_CONSTEXPR void basic_specs::set_upper () inline
Referenced by detail::vprintf().
sign()
constexpr auto basic_specs::sign () const -> sign inline constexpr
Referenced by detail::check_char_specs(), formatter< group_digits_view< T > >::format(), detail::loc_writer< Char >::operator()(), detail::parse_flags(), detail::write(), and detail::write().
type()
constexpr auto basic_specs::type () const -> presentation_type inline constexpr
Referenced by detail::check_char_specs(), detail::do_write_float(), formatter< std::error_code >::format(), detail::format_float(), detail::printf_arg_formatter< Char >::operator()(), detail::vprintf(), detail::write(), detail::write(), detail::write_char(), detail::write_int(), and detail::write_int().
upper()
constexpr auto basic_specs::upper () const -> bool inline constexpr
Referenced by detail::do_write_float(), detail::format_hexfloat(), detail::write_int(), detail::write_int(), and detail::write_nonfinite().
Member Data Documentation
data_
unsigned basic_specs::data_ = 1 << fill_size_shift private
Referenced by align(), alt(), clear_alt(), dynamic(), dynamic_precision(), dynamic_width(), fill_size(), localized(), set_align(), set_alt(), set_dynamic_precision(), set_dynamic_width(), set_fill_size(), set_localized(), set_sign(), set_type(), set_upper(), sign(), type(), and upper().
fill_data_
char basic_specs::fill_data_[max_fill_size] = {' '} private
Referenced by copy_fill_from(), fill(), fill_unit(), set_fill(), and set_fill().
The documentation for this class was generated from the following file:
thirdparty/fmt/include/fmt/base.h