CHRONOS-LoRa: parse_context< Char > Class Template Reference
parse_context< Char > Class Template Reference
#include <base.h>
Public Types
using char_type = Char
using iterator = const Char *
Public Member Functions
constexpr parse_context (basic_string_view< Char > fmt, int next_arg_id=0)
constexpr auto begin () const noexcept -> iterator
constexpr auto end () const noexcept -> iterator
Returns an iterator past the end of the format string range being parsed.
FMT_CONSTEXPR void advance_to (iterator it)
Advances the begin iterator to it.
FMT_CONSTEXPR auto next_arg_id () -> int
FMT_CONSTEXPR void check_arg_id (int id)
FMT_CONSTEXPR void check_arg_id (basic_string_view< Char >)
FMT_CONSTEXPR void check_dynamic_spec (int arg_id)
Private Types
enum
Private Member Functions
FMT_CONSTEXPR void do_check_arg_id (int arg_id)
Private Attributes
basic_string_view< Char > fmt_
int next_arg_id_
Detailed Description
template<typename Char = char>
class parse_context< Char >
Parsing context consisting of a format string range being parsed and an argument counter for automatic indexing.
Member Typedef Documentation
char_type
template<typename Char = char> using parse_context< Char >::char_type = Char
iterator
template<typename Char = char> using parse_context< Char >::iterator = const Char*
Member Enumeration Documentation
anonymous enum
template<typename Char = char> anonymous enum private
Constructor & Destructor Documentation
parse_context()
template<typename Char = char> constexpr parse_context< Char >::parse_context (basic_string_view< Char > fmt, int next_arg_id = 0) inline explicit constexpr
Referenced by detail::vformat_to().
Member Function Documentation
advance_to()
template<typename Char = char> FMT_CONSTEXPR void parse_context< Char >::advance_to (iterator it) inline
Advances the begin iterator to it.
begin()
template<typename Char = char> constexpr auto parse_context< Char >::begin () const -> iterator inline constexpr noexcept
Returns an iterator to the beginning of the format string range being parsed.
Referenced by parse_context< Char >::advance_to(), formatter< detail::bigint >::parse(), formatter< bytes >::parse(), formatter< group_digits_view< T > >::parse(), formatter< std::error_code >::parse(), and formatter< T, char, typename std::enable_if< std::is_base_of< std::exception, T >::value >::type >::parse().
check_arg_id() [1/2]
template<typename Char = char> FMT_CONSTEXPR void parse_context< Char >::check_arg_id (basic_string_view< Char >) inline
check_arg_id() [2/2]
template<typename Char = char> FMT_CONSTEXPR void parse_context< Char >::check_arg_id (int id) inline
Reports an error if using the automatic argument indexing; otherwise switches to the manual indexing.
check_dynamic_spec()
template<typename Char = char> FMT_CONSTEXPR void parse_context< Char >::check_dynamic_spec (int arg_id)
do_check_arg_id()
template<typename Char = char> FMT_CONSTEXPR void parse_context< Char >::do_check_arg_id (int arg_id) private
Referenced by parse_context< Char >::check_arg_id(), and parse_context< Char >::next_arg_id().
end()
template<typename Char = char> constexpr auto parse_context< Char >::end () const -> iterator inline constexpr noexcept
Returns an iterator past the end of the format string range being parsed.
Referenced by formatter< bytes >::parse(), formatter< group_digits_view< T > >::parse(), formatter< std::error_code >::parse(), and formatter< T, char, typename std::enable_if< std::is_base_of< std::exception, T >::value >::type >::parse().
next_arg_id()
template<typename Char = char> FMT_CONSTEXPR auto parse_context< Char >::next_arg_id () -> int inline
Reports an error if using the manual argument indexing; otherwise returns the next argument index and switches to the automatic indexing.
Member Data Documentation
fmt_
template<typename Char = char> basic_string_view<Char> parse_context< Char >::fmt_ private
Referenced by parse_context< Char >::advance_to(), parse_context< Char >::begin(), parse_context< Char >::end(), and parse_context< Char >::parse_context().
next_arg_id_
template<typename Char = char> int parse_context< Char >::next_arg_id_ private
Referenced by parse_context< Char >::check_arg_id(), parse_context< Char >::check_arg_id(), parse_context< Char >::next_arg_id(), and parse_context< Char >::parse_context().
The documentation for this class was generated from the following file:
thirdparty/fmt/include/fmt/base.h