CHRONOS-LoRa: /usr/include/GraphicsMagick/magick/constitute.h File Reference
constitute.h File Reference
Classes
struct _ExportPixelAreaOptions
struct _ExportPixelAreaInfo
struct _ImportPixelAreaOptions
struct _ImportPixelAreaInfo
Typedefs
typedef struct _ExportPixelAreaOptions ExportPixelAreaOptions
typedef struct _ExportPixelAreaInfo ExportPixelAreaInfo
typedef struct _ImportPixelAreaOptions ImportPixelAreaOptions
typedef struct _ImportPixelAreaInfo ImportPixelAreaInfo
Enumerations
enum QuantumType {
UndefinedQuantum , IndexQuantum , GrayQuantum , IndexAlphaQuantum ,
GrayAlphaQuantum , RedQuantum , CyanQuantum , GreenQuantum ,
YellowQuantum , BlueQuantum , MagentaQuantum , AlphaQuantum ,
BlackQuantum , RGBQuantum , RGBAQuantum , CMYKQuantum ,
CMYKAQuantum , CIEYQuantum , CIEXYZQuantum
}
enum QuantumSampleType { UndefinedQuantumSampleType , UnsignedQuantumSampleType , FloatQuantumSampleType }
enum StorageType {
CharPixel , ShortPixel , IntegerPixel , LongPixel ,
FloatPixel , DoublePixel
}
Functions
MagickExport const char * StorageTypeToString (const StorageType storage_type)
MagickExport const char * QuantumSampleTypeToString (const QuantumSampleType sample_type)
MagickExport const char * QuantumTypeToString (const QuantumType quantum_type)
MagickExport Image * ConstituteImage (const unsigned long width, const unsigned long height, const char *map, const StorageType type, const void *pixels, ExceptionInfo *exception)
MagickExport Image * ConstituteTextureImage (const unsigned long columns, const unsigned long rows, const Image *texture, ExceptionInfo *exception)
MagickExport Image * PingImage (const ImageInfo *image_info, ExceptionInfo *exception)
MagickExport Image * ReadImage (const ImageInfo *image_info, ExceptionInfo *exception)
MagickExport Image * ReadInlineImage (const ImageInfo *image_info, const char *content, ExceptionInfo *exception)
MagickExport MagickPassFail DispatchImage (const Image *image, const long x_offset, const long y_offset, const unsigned long columns, const unsigned long rows, const char *map, const StorageType type, void *pixels, ExceptionInfo *exception)
MagickExport MagickPassFail ExportImagePixelArea (const Image *image, const QuantumType quantum_type, const unsigned int quantum_size, unsigned char *destination, const ExportPixelAreaOptions *options, ExportPixelAreaInfo *export_info)
MagickExport MagickPassFail ExportViewPixelArea (const ViewInfo *view, const QuantumType quantum_type, const unsigned int quantum_size, unsigned char *destination, const ExportPixelAreaOptions *options, ExportPixelAreaInfo *export_info)
MagickExport MagickPassFail ImportImagePixelArea (Image *image, const QuantumType quantum_type, const unsigned int quantum_size, const unsigned char *source, const ImportPixelAreaOptions *options, ImportPixelAreaInfo *import_info)
MagickExport MagickPassFail ImportViewPixelArea (ViewInfo *view, const QuantumType quantum_type, const unsigned int quantum_size, const unsigned char *source, const ImportPixelAreaOptions *options, ImportPixelAreaInfo *import_info)
MagickExport MagickPassFail WriteImage (const ImageInfo *image_info, Image *image)
MagickExport MagickPassFail WriteImages (const ImageInfo *image_info, Image *image, const char *filename, ExceptionInfo *exception)
MagickExport MagickPassFail WriteImagesFile (const ImageInfo *image_info, Image *image, FILE *file, ExceptionInfo *exception)
MagickExport void ExportPixelAreaOptionsInit (ExportPixelAreaOptions *options)
MagickExport void ImportPixelAreaOptionsInit (ImportPixelAreaOptions *options)
MagickExport MagickPassFail MagickFindRawImageMinMax (Image *image, EndianType endian, unsigned long width, unsigned long height, StorageType type, unsigned scanline_octets, void *scanline_buffer, double *min, double *max)
MagickExport unsigned int MagickGetQuantumSamplesPerPixel (const QuantumType quantum_type) MAGICK_FUNC_CONST
Typedef Documentation
ExportPixelAreaInfo
typedef struct _ExportPixelAreaInfo ExportPixelAreaInfo
ExportPixelAreaOptions
typedef struct _ExportPixelAreaOptions ExportPixelAreaOptions
ImportPixelAreaInfo
typedef struct _ImportPixelAreaInfo ImportPixelAreaInfo
ImportPixelAreaOptions
typedef struct _ImportPixelAreaOptions ImportPixelAreaOptions
Enumeration Type Documentation
QuantumSampleType
enum QuantumSampleType
Enumerator
UndefinedQuantumSampleType
UnsignedQuantumSampleType
FloatQuantumSampleType
QuantumType
enum QuantumType
Enumerator
UndefinedQuantum
IndexQuantum
GrayQuantum
IndexAlphaQuantum
GrayAlphaQuantum
RedQuantum
CyanQuantum
GreenQuantum
YellowQuantum
BlueQuantum
MagentaQuantum
AlphaQuantum
BlackQuantum
RGBQuantum
RGBAQuantum
CMYKQuantum
CMYKAQuantum
CIEYQuantum
CIEXYZQuantum
StorageType
enum StorageType
Enumerator
CharPixel
ShortPixel
IntegerPixel
LongPixel
FloatPixel
DoublePixel
Function Documentation
ConstituteImage()
MagickExport Image * ConstituteImage (const unsigned long width, const unsigned long height, const char * map, const StorageType type, const void * pixels, ExceptionInfo * exception) extern
ConstituteTextureImage()
MagickExport Image * ConstituteTextureImage (const unsigned long columns, const unsigned long rows, const Image * texture, ExceptionInfo * exception)
DispatchImage()
MagickExport MagickPassFail DispatchImage (const Image * image, const long x_offset, const long y_offset, const unsigned long columns, const unsigned long rows, const char * map, const StorageType type, void * pixels, ExceptionInfo * exception) extern
ExportImagePixelArea()
MagickExport MagickPassFail ExportImagePixelArea (const Image * image, const QuantumType quantum_type, const unsigned int quantum_size, unsigned char * destination, const ExportPixelAreaOptions * options, ExportPixelAreaInfo * export_info)
ExportPixelAreaOptionsInit()
MagickExport void ExportPixelAreaOptionsInit (ExportPixelAreaOptions * options) extern
ExportViewPixelArea()
MagickExport MagickPassFail ExportViewPixelArea (const ViewInfo * view, const QuantumType quantum_type, const unsigned int quantum_size, unsigned char * destination, const ExportPixelAreaOptions * options, ExportPixelAreaInfo * export_info)
ImportImagePixelArea()
MagickExport MagickPassFail ImportImagePixelArea (Image * image, const QuantumType quantum_type, const unsigned int quantum_size, const unsigned char * source, const ImportPixelAreaOptions * options, ImportPixelAreaInfo * import_info) extern
ImportPixelAreaOptionsInit()
MagickExport void ImportPixelAreaOptionsInit (ImportPixelAreaOptions * options)
ImportViewPixelArea()
MagickExport MagickPassFail ImportViewPixelArea (ViewInfo * view, const QuantumType quantum_type, const unsigned int quantum_size, const unsigned char * source, const ImportPixelAreaOptions * options, ImportPixelAreaInfo * import_info)
MagickFindRawImageMinMax()
MagickExport MagickPassFail MagickFindRawImageMinMax (Image * image, EndianType endian, unsigned long width, unsigned long height, StorageType type, unsigned scanline_octets, void * scanline_buffer, double * min, double * max) extern
MagickGetQuantumSamplesPerPixel()
MagickExport unsigned int MagickGetQuantumSamplesPerPixel (const QuantumType quantum_type) extern
PingImage()
MagickExport Image * PingImage (const ImageInfo * image_info, ExceptionInfo * exception)
QuantumSampleTypeToString()
MagickExport const char * QuantumSampleTypeToString (const QuantumSampleType sample_type)
QuantumTypeToString()
MagickExport const char * QuantumTypeToString (const QuantumType quantum_type)
ReadImage()
MagickExport Image * ReadImage (const ImageInfo * image_info, ExceptionInfo * exception)
Referenced by chronos_process_image(), chronos_resize_image(), and chronos_rgb_to_ycocg().
ReadInlineImage()
MagickExport Image * ReadInlineImage (const ImageInfo * image_info, const char * content, ExceptionInfo * exception)
StorageTypeToString()
MagickExport const char * StorageTypeToString (const StorageType storage_type) extern
WriteImage()
MagickExport MagickPassFail WriteImage (const ImageInfo * image_info, Image * image)
Referenced by chronos_process_image(), chronos_resize_image(), and chronos_rgb_to_ycocg().
WriteImages()
MagickExport MagickPassFail WriteImages (const ImageInfo * image_info, Image * image, const char * filename, ExceptionInfo * exception)
WriteImagesFile()
MagickExport MagickPassFail WriteImagesFile (const ImageInfo * image_info, Image * image, FILE * file, ExceptionInfo * exception)