CHRONOS-LoRa: /usr/include/GraphicsMagick/magick/error.h File Reference
error.h File Reference
#include <magick/log.h>
Classes
struct _ExceptionInfo
Typedefs
typedef struct _ExceptionInfo ExceptionInfo
typedef void(* ErrorHandler) (const ExceptionType severity, const char *reason, const char *description)
typedef void(* FatalErrorHandler) (const ExceptionType severity, const char *reason, const char *description) MAGICK_FUNC_NORETURN
typedef void(* WarningHandler) (const ExceptionType severity, const char *reason, const char *description)
Enumerations
enum ExceptionBaseType {
UndefinedExceptionBase = 0 , ExceptionBase = 1 , ResourceBase = 2 , ResourceLimitBase = 2 ,
TypeBase = 5 , AnnotateBase = 5 , OptionBase = 10 , DelegateBase = 15 ,
MissingDelegateBase = 20 , CorruptImageBase = 25 , FileOpenBase = 30 , BlobBase = 35 ,
StreamBase = 40 , CacheBase = 45 , CoderBase = 50 , ModuleBase = 55 ,
DrawBase = 60 , RenderBase = 60 , ImageBase = 65 , WandBase = 67 ,
TemporaryFileBase = 70 , TransformBase = 75 , XServerBase = 80 , X11Base = 81 ,
UserBase = 82 , MonitorBase = 85 , LocaleBase = 86 , DeprecateBase = 87 ,
RegistryBase = 90 , ConfigureBase = 95
}
enum ExceptionType {
UndefinedException = 0 , EventException = 100 , ExceptionEvent = EventException + ExceptionBase , ResourceEvent = EventException + ResourceBase ,
ResourceLimitEvent = EventException + ResourceLimitBase , TypeEvent = EventException + TypeBase , AnnotateEvent = EventException + AnnotateBase , OptionEvent = EventException + OptionBase ,
DelegateEvent = EventException + DelegateBase , MissingDelegateEvent = EventException + MissingDelegateBase , CorruptImageEvent = EventException + CorruptImageBase , FileOpenEvent = EventException + FileOpenBase ,
BlobEvent = EventException + BlobBase , StreamEvent = EventException + StreamBase , CacheEvent = EventException + CacheBase , CoderEvent = EventException + CoderBase ,
ModuleEvent = EventException + ModuleBase , DrawEvent = EventException + DrawBase , RenderEvent = EventException + RenderBase , ImageEvent = EventException + ImageBase ,
WandEvent = EventException + WandBase , TemporaryFileEvent = EventException + TemporaryFileBase , TransformEvent = EventException + TransformBase , XServerEvent = EventException + XServerBase ,
X11Event = EventException + X11Base , UserEvent = EventException + UserBase , MonitorEvent = EventException + MonitorBase , LocaleEvent = EventException + LocaleBase ,
DeprecateEvent = EventException + DeprecateBase , RegistryEvent = EventException + RegistryBase , ConfigureEvent = EventException + ConfigureBase , WarningException = 300 ,
ExceptionWarning = WarningException + ExceptionBase , ResourceWarning = WarningException + ResourceBase , ResourceLimitWarning = WarningException + ResourceLimitBase , TypeWarning = WarningException + TypeBase ,
AnnotateWarning = WarningException + AnnotateBase , OptionWarning = WarningException + OptionBase , DelegateWarning = WarningException + DelegateBase , MissingDelegateWarning = WarningException + MissingDelegateBase ,
CorruptImageWarning = WarningException + CorruptImageBase , FileOpenWarning = WarningException + FileOpenBase , BlobWarning = WarningException + BlobBase , StreamWarning = WarningException + StreamBase ,
CacheWarning = WarningException + CacheBase , CoderWarning = WarningException + CoderBase , ModuleWarning = WarningException + ModuleBase , DrawWarning = WarningException + DrawBase ,
RenderWarning = WarningException + RenderBase , ImageWarning = WarningException + ImageBase , WandWarning = WarningException + WandBase , TemporaryFileWarning = WarningException + TemporaryFileBase ,
TransformWarning = WarningException + TransformBase , XServerWarning = WarningException + XServerBase , X11Warning = WarningException + X11Base , UserWarning = WarningException + UserBase ,
MonitorWarning = WarningException + MonitorBase , LocaleWarning = WarningException + LocaleBase , DeprecateWarning = WarningException + DeprecateBase , RegistryWarning = WarningException + RegistryBase ,
ConfigureWarning = WarningException + ConfigureBase , ErrorException = 400 , ExceptionError = ErrorException + ExceptionBase , ResourceError = ErrorException + ResourceBase ,
ResourceLimitError = ErrorException + ResourceLimitBase , TypeError = ErrorException + TypeBase , AnnotateError = ErrorException + AnnotateBase , OptionError = ErrorException + OptionBase ,
DelegateError = ErrorException + DelegateBase , MissingDelegateError = ErrorException + MissingDelegateBase , CorruptImageError = ErrorException + CorruptImageBase , FileOpenError = ErrorException + FileOpenBase ,
BlobError = ErrorException + BlobBase , StreamError = ErrorException + StreamBase , CacheError = ErrorException + CacheBase , CoderError = ErrorException + CoderBase ,
ModuleError = ErrorException + ModuleBase , DrawError = ErrorException + DrawBase , RenderError = ErrorException + RenderBase , ImageError = ErrorException + ImageBase ,
WandError = ErrorException + WandBase , TemporaryFileError = ErrorException + TemporaryFileBase , TransformError = ErrorException + TransformBase , XServerError = ErrorException + XServerBase ,
X11Error = ErrorException + X11Base , UserError = ErrorException + UserBase , MonitorError = ErrorException + MonitorBase , LocaleError = ErrorException + LocaleBase ,
DeprecateError = ErrorException + DeprecateBase , RegistryError = ErrorException + RegistryBase , ConfigureError = ErrorException + ConfigureBase , FatalErrorException = 700 ,
ExceptionFatalError = FatalErrorException + ExceptionBase , ResourceFatalError = FatalErrorException + ResourceBase , ResourceLimitFatalError = FatalErrorException + ResourceLimitBase , TypeFatalError = FatalErrorException + TypeBase ,
AnnotateFatalError = FatalErrorException + AnnotateBase , OptionFatalError = FatalErrorException + OptionBase , DelegateFatalError = FatalErrorException + DelegateBase , MissingDelegateFatalError = FatalErrorException + MissingDelegateBase ,
CorruptImageFatalError = FatalErrorException + CorruptImageBase , FileOpenFatalError = FatalErrorException + FileOpenBase , BlobFatalError = FatalErrorException + BlobBase , StreamFatalError = FatalErrorException + StreamBase ,
CacheFatalError = FatalErrorException + CacheBase , CoderFatalError = FatalErrorException + CoderBase , ModuleFatalError = FatalErrorException + ModuleBase , DrawFatalError = FatalErrorException + DrawBase ,
RenderFatalError = FatalErrorException + RenderBase , ImageFatalError = FatalErrorException + ImageBase , WandFatalError = FatalErrorException + WandBase , TemporaryFileFatalError = FatalErrorException + TemporaryFileBase ,
TransformFatalError = FatalErrorException + TransformBase , XServerFatalError = FatalErrorException + XServerBase , X11FatalError = FatalErrorException + X11Base , UserFatalError = FatalErrorException + UserBase ,
MonitorFatalError = FatalErrorException + MonitorBase , LocaleFatalError = FatalErrorException + LocaleBase , DeprecateFatalError = FatalErrorException + DeprecateBase , RegistryFatalError = FatalErrorException + RegistryBase ,
ConfigureFatalError = FatalErrorException + ConfigureBase
}
Functions
MagickExport const char * GetLocaleExceptionMessage (const ExceptionType severity, const char *tag)
MagickExport const char * GetLocaleMessage (const char *tag)
MagickExport ErrorHandler SetErrorHandler (ErrorHandler handler)
MagickExport FatalErrorHandler SetFatalErrorHandler (FatalErrorHandler handler)
MagickExport void CatchException (const ExceptionInfo *exception)
MagickExport void CopyException (ExceptionInfo *copy, const ExceptionInfo *original)
MagickExport void DestroyExceptionInfo (ExceptionInfo *exception)
MagickExport void GetExceptionInfo (ExceptionInfo *exception)
MagickExport void MagickError (const ExceptionType error, const char *reason, const char *description)
MagickExport void MagickFatalError (const ExceptionType error, const char *reason, const char *description) MAGICK_FUNC_NORETURN
MagickExport void MagickWarning (const ExceptionType severity, const char *reason, const char *description)
MagickExport void _MagickError (const ExceptionType severity, const char *reason, const char *description)
MagickExport void _MagickFatalError (const ExceptionType severity, const char *reason, const char *description) MAGICK_FUNC_NORETURN
MagickExport void _MagickWarning (const ExceptionType warning, const char *reason, const char *description)
MagickExport void SetExceptionInfo (ExceptionInfo *exception, ExceptionType severity)
MagickExport void ThrowException (ExceptionInfo *exception, const ExceptionType severity, const char *reason, const char *description)
MagickExport void ThrowLoggedException (ExceptionInfo *exception, const ExceptionType severity, const char *reason, const char *description, const char *module, const char *function, const unsigned long line)
MagickExport WarningHandler SetWarningHandler (WarningHandler handler)
Typedef Documentation
ErrorHandler
typedef void(* ErrorHandler) (const ExceptionType severity, const char *reason, const char *description)
ExceptionInfo
typedef struct _ExceptionInfo ExceptionInfo
FatalErrorHandler
typedef void(* FatalErrorHandler) (const ExceptionType severity, const char *reason, const char *description) MAGICK_FUNC_NORETURN
WarningHandler
typedef void(* WarningHandler) (const ExceptionType severity, const char *reason, const char *description)
Enumeration Type Documentation
ExceptionBaseType
enum ExceptionBaseType
Enumerator
UndefinedExceptionBase
ExceptionBase
ResourceBase
ResourceLimitBase
TypeBase
AnnotateBase
OptionBase
DelegateBase
MissingDelegateBase
CorruptImageBase
FileOpenBase
BlobBase
StreamBase
CacheBase
CoderBase
ModuleBase
DrawBase
RenderBase
ImageBase
WandBase
TemporaryFileBase
TransformBase
XServerBase
X11Base
UserBase
MonitorBase
LocaleBase
DeprecateBase
RegistryBase
ConfigureBase
ExceptionType
enum ExceptionType
Enumerator
UndefinedException
EventException
ExceptionEvent
ResourceEvent
ResourceLimitEvent
TypeEvent
AnnotateEvent
OptionEvent
DelegateEvent
MissingDelegateEvent
CorruptImageEvent
FileOpenEvent
BlobEvent
StreamEvent
CacheEvent
CoderEvent
ModuleEvent
DrawEvent
RenderEvent
ImageEvent
WandEvent
TemporaryFileEvent
TransformEvent
XServerEvent
X11Event
UserEvent
MonitorEvent
LocaleEvent
DeprecateEvent
RegistryEvent
ConfigureEvent
WarningException
ExceptionWarning
ResourceWarning
ResourceLimitWarning
TypeWarning
AnnotateWarning
OptionWarning
DelegateWarning
MissingDelegateWarning
CorruptImageWarning
FileOpenWarning
BlobWarning
StreamWarning
CacheWarning
CoderWarning
ModuleWarning
DrawWarning
RenderWarning
ImageWarning
WandWarning
TemporaryFileWarning
TransformWarning
XServerWarning
X11Warning
UserWarning
MonitorWarning
LocaleWarning
DeprecateWarning
RegistryWarning
ConfigureWarning
ErrorException
ExceptionError
ResourceError
ResourceLimitError
TypeError
AnnotateError
OptionError
DelegateError
MissingDelegateError
CorruptImageError
FileOpenError
BlobError
StreamError
CacheError
CoderError
ModuleError
DrawError
RenderError
ImageError
WandError
TemporaryFileError
TransformError
XServerError
X11Error
UserError
MonitorError
LocaleError
DeprecateError
RegistryError
ConfigureError
FatalErrorException
ExceptionFatalError
ResourceFatalError
ResourceLimitFatalError
TypeFatalError
AnnotateFatalError
OptionFatalError
DelegateFatalError
MissingDelegateFatalError
CorruptImageFatalError
FileOpenFatalError
BlobFatalError
StreamFatalError
CacheFatalError
CoderFatalError
ModuleFatalError
DrawFatalError
RenderFatalError
ImageFatalError
WandFatalError
TemporaryFileFatalError
TransformFatalError
XServerFatalError
X11FatalError
UserFatalError
MonitorFatalError
LocaleFatalError
DeprecateFatalError
RegistryFatalError
ConfigureFatalError
Function Documentation
_MagickError()
MagickExport void _MagickError (const ExceptionType severity, const char * reason, const char * description)
_MagickFatalError()
MagickExport void _MagickFatalError (const ExceptionType severity, const char * reason, const char * description)
_MagickWarning()
MagickExport void _MagickWarning (const ExceptionType warning, const char * reason, const char * description)
CatchException()
MagickExport void CatchException (const ExceptionInfo * exception) extern
Referenced by chronos_process_image().
CopyException()
MagickExport void CopyException (ExceptionInfo * copy, const ExceptionInfo * original)
DestroyExceptionInfo()
MagickExport void DestroyExceptionInfo (ExceptionInfo * exception)
Referenced by chronos_process_image(), chronos_resize_image(), and chronos_rgb_to_ycocg().
GetExceptionInfo()
MagickExport void GetExceptionInfo (ExceptionInfo * exception)
Referenced by chronos_process_image(), chronos_resize_image(), and chronos_rgb_to_ycocg().
GetLocaleExceptionMessage()
MagickExport const char * GetLocaleExceptionMessage (const ExceptionType severity, const char * tag) extern
GetLocaleMessage()
MagickExport const char * GetLocaleMessage (const char * tag)
MagickError()
MagickExport void MagickError (const ExceptionType error, const char * reason, const char * description)
MagickFatalError()
MagickExport void MagickFatalError (const ExceptionType error, const char * reason, const char * description)
MagickWarning()
MagickExport void MagickWarning (const ExceptionType severity, const char * reason, const char * description)
SetErrorHandler()
MagickExport ErrorHandler SetErrorHandler (ErrorHandler handler) extern
SetExceptionInfo()
MagickExport void SetExceptionInfo (ExceptionInfo * exception, ExceptionType severity)
SetFatalErrorHandler()
MagickExport FatalErrorHandler SetFatalErrorHandler (FatalErrorHandler handler) extern
SetWarningHandler()
MagickExport WarningHandler SetWarningHandler (WarningHandler handler) extern
ThrowException()
MagickExport void ThrowException (ExceptionInfo * exception, const ExceptionType severity, const char * reason, const char * description)
ThrowLoggedException()
MagickExport void ThrowLoggedException (ExceptionInfo * exception, const ExceptionType severity, const char * reason, const char * description, const char * module, const char * function, const unsigned long line)