CHRONOS-LoRa: /usr/include/GraphicsMagick/magick/image.h File Reference
image.h File Reference
#include "magick/forward.h"
#include "magick/colorspace.h"
#include "magick/error.h"
#include "magick/timer.h"
Classes
struct _AffineMatrix
struct _PrimaryInfo
struct _ChromaticityInfo
struct _PixelPacket
struct _DoublePixelPacket
struct _FloatPixelPacket
struct _ErrorInfo
struct _FrameInfo
struct _LongPixelPacket
struct _MontageInfo
struct _ProfileInfo
struct _RectangleInfo
struct _SegmentInfo
struct _Image
struct _ImageInfo
Macros
#define QuantumDepth 16
#define MaxColormapSize 65536U
#define MaxMap 65535U
#define MaxMapDepth 16
#define MaxMapFloat 65535.0f
#define MaxMapDouble 65535.0
#define MaxRGB 65535U
#define MaxRGBFloat 65535.0f
#define MaxRGBDouble 65535.0
#define ScaleCharToMap(value) ((unsigned short) (257U*(value)))
#define ScaleCharToQuantum(value) ((Quantum) (257U*(value)))
#define ScaleLongToQuantum(value) ((Quantum) ((value)/65537UL))
#define ScaleMapToChar(value) ((unsigned int) ((value)/257U))
#define ScaleMapToQuantum(value) ((Quantum) (value))
#define ScaleQuantum(quantum) ((unsigned long) ((quantum)/257UL))
#define ScaleQuantumToChar(quantum) ((unsigned char) ((quantum)/257U))
#define ScaleQuantumToLong(quantum) ((unsigned long) (65537UL*(quantum)))
#define ScaleQuantumToMap(quantum) ((unsigned short) (quantum))
#define ScaleQuantumToShort(quantum) ((unsigned short) (quantum))
#define ScaleShortToQuantum(value) ((Quantum) (value))
#define ScaleToQuantum(value) ((unsigned long) (257UL*(value)))
#define ScaleQuantumToIndex(value) ((unsigned short) (value))
#define OpaqueOpacity 0UL
#define TransparentOpacity MaxRGB
#define RoundDoubleToQuantum(value)
#define RoundDoubleToQuantumN(value)
#define RoundFloatToQuantum(value)
#define ConstrainToRange(min, max, value)
#define ConstrainToQuantum(value) ConstrainToRange(0,MaxRGB,value)
#define ScaleAnyToQuantum(x, max_value) ((Quantum) (((double) MaxRGBDouble*x)/max_value+0.5))
#define MagickBoolToString(value) (value != MagickFalse ? "True" : "False")
#define MagickChannelEnabled(channels, channel) ((channels == AllChannels) || (channels == channel))
#define RunlengthEncodedCompression RLECompression
#define RoundSignedToQuantum(value) RoundDoubleToQuantum(value)
#define RoundToQuantum(value) RoundDoubleToQuantum(value)
#define MAGICK_PIXELS_BGRA 1
Typedefs
typedef unsigned short Quantum
typedef struct _AffineMatrix AffineMatrix
typedef struct _PrimaryInfo PrimaryInfo
typedef struct _ChromaticityInfo ChromaticityInfo
typedef struct _PixelPacket PixelPacket
typedef struct _DoublePixelPacket DoublePixelPacket
typedef struct _FloatPixelPacket FloatPixelPacket
typedef struct _ErrorInfo ErrorInfo
typedef struct _FrameInfo FrameInfo
typedef Quantum IndexPacket
typedef struct _LongPixelPacket LongPixelPacket
typedef struct _MontageInfo MontageInfo
typedef struct _ProfileInfo ProfileInfo
typedef struct _RectangleInfo RectangleInfo
typedef struct _SegmentInfo SegmentInfo
typedef struct _Image Image
typedef struct _ImageInfo ImageInfo
Enumerations
enum AlphaType { UnspecifiedAlpha , AssociatedAlpha , UnassociatedAlpha }
enum ChannelType {
UndefinedChannel , RedChannel , CyanChannel , GreenChannel ,
MagentaChannel , BlueChannel , YellowChannel , OpacityChannel ,
BlackChannel , MatteChannel , AllChannels , GrayChannel
}
enum ClassType { UndefinedClass , DirectClass , PseudoClass }
enum CompositeOperator {
UndefinedCompositeOp = 0 , OverCompositeOp , InCompositeOp , OutCompositeOp ,
AtopCompositeOp , XorCompositeOp , PlusCompositeOp , MinusCompositeOp ,
AddCompositeOp , SubtractCompositeOp , DifferenceCompositeOp , MultiplyCompositeOp ,
BumpmapCompositeOp , CopyCompositeOp , CopyRedCompositeOp , CopyGreenCompositeOp ,
CopyBlueCompositeOp , CopyOpacityCompositeOp , ClearCompositeOp , DissolveCompositeOp ,
DisplaceCompositeOp , ModulateCompositeOp , ThresholdCompositeOp , NoCompositeOp ,
DarkenCompositeOp , LightenCompositeOp , HueCompositeOp , SaturateCompositeOp ,
ColorizeCompositeOp , LuminizeCompositeOp , ScreenCompositeOp , OverlayCompositeOp ,
CopyCyanCompositeOp , CopyMagentaCompositeOp , CopyYellowCompositeOp , CopyBlackCompositeOp ,
DivideCompositeOp , HardLightCompositeOp , ExclusionCompositeOp , ColorDodgeCompositeOp ,
ColorBurnCompositeOp , SoftLightCompositeOp , LinearBurnCompositeOp , LinearDodgeCompositeOp ,
LinearLightCompositeOp , VividLightCompositeOp , PinLightCompositeOp , HardMixCompositeOp
}
enum CompressionType {
UndefinedCompression , NoCompression , BZipCompression , FaxCompression ,
Group3Compression = FaxCompression , Group4Compression , JPEGCompression , LosslessJPEGCompression ,
LZWCompression , RLECompression , ZipCompression , LZMACompression ,
JPEG2000Compression , JBIG1Compression , JBIG2Compression , ZSTDCompression ,
WebPCompression
}
enum DisposeType { UndefinedDispose , NoneDispose , BackgroundDispose , PreviousDispose }
enum EndianType { UndefinedEndian , LSBEndian , MSBEndian , NativeEndian }
enum FilterTypes {
UndefinedFilter , PointFilter , BoxFilter , TriangleFilter ,
HermiteFilter , HanningFilter , HammingFilter , BlackmanFilter ,
GaussianFilter , QuadraticFilter , CubicFilter , CatromFilter ,
MitchellFilter , LanczosFilter , BesselFilter , SincFilter
}
enum GeometryFlags {
NoValue = 0x00000 , XValue = 0x00001 , YValue = 0x00002 , WidthValue = 0x00004 ,
HeightValue = 0x00008 , AllValues = 0x0000F , XNegative = 0x00010 , YNegative = 0x00020 ,
PercentValue = 0x01000 , AspectValue = 0x02000 , LessValue = 0x04000 , GreaterValue = 0x08000 ,
AreaValue = 0x10000 , MinimumValue = 0x20000
}
enum GravityType {
ForgetGravity , NorthWestGravity , NorthGravity , NorthEastGravity ,
WestGravity , CenterGravity , EastGravity , SouthWestGravity ,
SouthGravity , SouthEastGravity , StaticGravity
}
enum ImageType {
UndefinedType , BilevelType , GrayscaleType , GrayscaleMatteType ,
PaletteType , PaletteMatteType , TrueColorType , TrueColorMatteType ,
ColorSeparationType , ColorSeparationMatteType , OptimizeType
}
enum InterlaceType {
UndefinedInterlace , NoInterlace , LineInterlace , PlaneInterlace ,
PartitionInterlace
}
enum MontageMode { UndefinedMode , FrameMode , UnframeMode , ConcatenateMode }
enum NoiseType {
UniformNoise , GaussianNoise , MultiplicativeGaussianNoise , ImpulseNoise ,
LaplacianNoise , PoissonNoise , RandomNoise , UndefinedNoise
}
enum OrientationType {
UndefinedOrientation , TopLeftOrientation , TopRightOrientation , BottomRightOrientation ,
BottomLeftOrientation , LeftTopOrientation , RightTopOrientation , RightBottomOrientation ,
LeftBottomOrientation
}
enum PreviewType {
UndefinedPreview = 0 , RotatePreview , ShearPreview , RollPreview ,
HuePreview , SaturationPreview , BrightnessPreview , GammaPreview ,
SpiffPreview , DullPreview , GrayscalePreview , QuantizePreview ,
DespecklePreview , ReduceNoisePreview , AddNoisePreview , SharpenPreview ,
BlurPreview , ThresholdPreview , EdgeDetectPreview , SpreadPreview ,
SolarizePreview , ShadePreview , RaisePreview , SegmentPreview ,
SwirlPreview , ImplodePreview , WavePreview , OilPaintPreview ,
CharcoalDrawingPreview , JPEGPreview
}
enum RenderingIntent {
UndefinedIntent , SaturationIntent , PerceptualIntent , AbsoluteIntent ,
RelativeIntent
}
enum ResolutionType { UndefinedResolution , PixelsPerInchResolution , PixelsPerCentimeterResolution }
Functions
MagickExport ExceptionType CatchImageException (Image *)
MagickExport Image * AllocateImage (const ImageInfo *)
MagickExport Image * AppendImages (const Image *, const unsigned int, ExceptionInfo *)
MagickExport Image * CloneImage (const Image *, const unsigned long, const unsigned long, const unsigned int, ExceptionInfo *)
MagickExport Image * GetImageClipMask (const Image *, ExceptionInfo *)
MagickExport Image * GetImageCompositeMask (const Image *, ExceptionInfo *)
MagickExport Image * ReferenceImage (Image *)
MagickExport ImageInfo * CloneImageInfo (const ImageInfo *)
MagickExport const char * AccessDefinition (const ImageInfo *image_info, const char *magick, const char *key)
MagickExport int GetImageGeometry (const Image *, const char *, const unsigned int, RectangleInfo *)
MagickExport MagickBool IsTaintImage (const Image *)
MagickExport MagickBool IsSubimage (const char *, const MagickBool)
MagickExport MagickPassFail AddDefinition (ImageInfo *image_info, const char *magick, const char *key, const char *value, ExceptionInfo *exception)
MagickExport MagickPassFail AddDefinitions (ImageInfo *image_info, const char *options, ExceptionInfo *exception)
MagickExport MagickPassFail AnimateImages (const ImageInfo *image_info, Image *image)
MagickExport MagickPassFail ClipImage (Image *image)
MagickExport MagickPassFail ClipPathImage (Image *image, const char *pathname, const MagickBool inside)
MagickExport MagickPassFail CompositeMaskImage (Image *image)
MagickExport MagickPassFail CompositePathImage (Image *image, const char *pathname, const MagickBool inside)
MagickExport MagickPassFail DisplayImages (const ImageInfo *image_info, Image *image)
MagickExport MagickPassFail RemoveDefinitions (const ImageInfo *image_info, const char *options)
MagickExport MagickPassFail ResetImagePage (Image *image, const char *page)
MagickExport MagickPassFail SetImage (Image *image, const Quantum)
MagickExport MagickPassFail SetImageEx (Image *image, const Quantum opacity, ExceptionInfo *exception)
MagickExport MagickPassFail SetImageColor (Image *image, const PixelPacket *pixel)
MagickExport MagickPassFail SetImageColorRegion (Image *image, long x, long y, unsigned long width, unsigned long height, const PixelPacket *pixel)
MagickExport MagickPassFail SetImageClipMask (Image *image, const Image *clip_mask)
MagickExport MagickPassFail SetImageCompositeMask (Image *image, const Image *composite_mask)
MagickExport MagickPassFail SetImageDepth (Image *image, const unsigned long)
MagickExport MagickPassFail SetImageInfo (ImageInfo *image_info, const unsigned int flags, ExceptionInfo *exception)
MagickExport MagickPassFail SetImageOpacity (Image *, const unsigned int)
MagickExport MagickPassFail SetImageType (Image *image, const ImageType)
MagickExport MagickPassFail StripImage (Image *image)
MagickExport MagickPassFail SyncImage (Image *image)
MagickExport void AllocateNextImage (const ImageInfo *, Image *)
MagickExport void DestroyImage (Image *)
MagickExport void DestroyImageInfo (ImageInfo *)
MagickExport void GetImageException (Image *, ExceptionInfo *)
MagickExport void GetImageInfo (ImageInfo *)
MagickExport void ModifyImage (Image **, ExceptionInfo *)
MagickExport Image ** ImageGetClipMask (const Image *) MAGICK_FUNC_PURE
MagickExport Image ** ImageGetCompositeMask (const Image *) MAGICK_FUNC_PURE
Macro Definition Documentation
ConstrainToQuantum
#define ConstrainToQuantum (value) ConstrainToRange(0,MaxRGB,value)
ConstrainToRange
#define ConstrainToRange (min, max, value)
Value:
  (value < min ? min :    \
  (value > max) ? max : value)
MAGICK_PIXELS_BGRA
#define MAGICK_PIXELS_BGRA 1
MagickBoolToString
#define MagickBoolToString (value) (value != MagickFalse ? "True" : "False")
MagickChannelEnabled
#define MagickChannelEnabled (channels, channel) ((channels == AllChannels) || (channels == channel))
MaxColormapSize
#define MaxColormapSize 65536U
MaxMap
#define MaxMap 65535U
MaxMapDepth
#define MaxMapDepth 16
MaxMapDouble
#define MaxMapDouble 65535.0
MaxMapFloat
#define MaxMapFloat 65535.0f
MaxRGB
#define MaxRGB 65535U
MaxRGBDouble
#define MaxRGBDouble 65535.0
MaxRGBFloat
#define MaxRGBFloat 65535.0f
OpaqueOpacity
#define OpaqueOpacity 0UL
QuantumDepth
#define QuantumDepth 16
RoundDoubleToQuantum
#define RoundDoubleToQuantum (value)
Value:
  ((Quantum) (value < 0.0 ? 0U : \
  (value > MaxRGBDouble) ? MaxRGB : value + 0.5))
RoundDoubleToQuantumN
#define RoundDoubleToQuantumN (value)
Value:
  ((Quantum) (MAGICK_ISNAN(value) ? 0U : \
  (value < 0.0 ? 0U : (value > MaxRGBDouble) ? MaxRGB : value + 0.5)))
RoundFloatToQuantum
#define RoundFloatToQuantum (value)
Value:
  ((Quantum) (value < 0.0f ? 0U : \
  (value > MaxRGBFloat) ? MaxRGB : value + 0.5f))
RoundSignedToQuantum
#define RoundSignedToQuantum (value) RoundDoubleToQuantum(value)
RoundToQuantum
#define RoundToQuantum (value) RoundDoubleToQuantum(value)
RunlengthEncodedCompression
#define RunlengthEncodedCompression RLECompression
ScaleAnyToQuantum
#define ScaleAnyToQuantum (x, max_value) ((Quantum) (((double) MaxRGBDouble*x)/max_value+0.5))
ScaleCharToMap
#define ScaleCharToMap (value) ((unsigned short) (257U*(value)))
ScaleCharToQuantum
#define ScaleCharToQuantum (value) ((Quantum) (257U*(value)))
ScaleLongToQuantum
#define ScaleLongToQuantum (value) ((Quantum) ((value)/65537UL))
ScaleMapToChar
#define ScaleMapToChar (value) ((unsigned int) ((value)/257U))
ScaleMapToQuantum
#define ScaleMapToQuantum (value) ((Quantum) (value))
ScaleQuantum
#define ScaleQuantum (quantum) ((unsigned long) ((quantum)/257UL))
ScaleQuantumToChar
#define ScaleQuantumToChar (quantum) ((unsigned char) ((quantum)/257U))
ScaleQuantumToIndex
#define ScaleQuantumToIndex (value) ((unsigned short) (value))
ScaleQuantumToLong
#define ScaleQuantumToLong (quantum) ((unsigned long) (65537UL*(quantum)))
ScaleQuantumToMap
#define ScaleQuantumToMap (quantum) ((unsigned short) (quantum))
ScaleQuantumToShort
#define ScaleQuantumToShort (quantum) ((unsigned short) (quantum))
ScaleShortToQuantum
#define ScaleShortToQuantum (value) ((Quantum) (value))
ScaleToQuantum
#define ScaleToQuantum (value) ((unsigned long) (257UL*(value)))
TransparentOpacity
#define TransparentOpacity MaxRGB
Typedef Documentation
AffineMatrix
typedef struct _AffineMatrix AffineMatrix
ChromaticityInfo
typedef struct _ChromaticityInfo ChromaticityInfo
DoublePixelPacket
typedef struct _DoublePixelPacket DoublePixelPacket
ErrorInfo
typedef struct _ErrorInfo ErrorInfo
FloatPixelPacket
typedef struct _FloatPixelPacket FloatPixelPacket
FrameInfo
typedef struct _FrameInfo FrameInfo
Image
typedef struct _Image Image
ImageInfo
typedef struct _ImageInfo ImageInfo
IndexPacket
typedef Quantum IndexPacket
LongPixelPacket
typedef struct _LongPixelPacket LongPixelPacket
MontageInfo
typedef struct _MontageInfo MontageInfo
PixelPacket
typedef struct _PixelPacket PixelPacket
PrimaryInfo
typedef struct _PrimaryInfo PrimaryInfo
ProfileInfo
typedef struct _ProfileInfo ProfileInfo
Quantum
typedef unsigned short Quantum
RectangleInfo
typedef struct _RectangleInfo RectangleInfo
SegmentInfo
typedef struct _SegmentInfo SegmentInfo
Enumeration Type Documentation
AlphaType
enum AlphaType
Enumerator
UnspecifiedAlpha
AssociatedAlpha
UnassociatedAlpha
ChannelType
enum ChannelType
Enumerator
UndefinedChannel
RedChannel
CyanChannel
GreenChannel
MagentaChannel
BlueChannel
YellowChannel
OpacityChannel
BlackChannel
MatteChannel
AllChannels
GrayChannel
ClassType
enum ClassType
Enumerator
UndefinedClass
DirectClass
PseudoClass
CompositeOperator
enum CompositeOperator
Enumerator
UndefinedCompositeOp
OverCompositeOp
InCompositeOp
OutCompositeOp
AtopCompositeOp
XorCompositeOp
PlusCompositeOp
MinusCompositeOp
AddCompositeOp
SubtractCompositeOp
DifferenceCompositeOp
MultiplyCompositeOp
BumpmapCompositeOp
CopyCompositeOp
CopyRedCompositeOp
CopyGreenCompositeOp
CopyBlueCompositeOp
CopyOpacityCompositeOp
ClearCompositeOp
DissolveCompositeOp
DisplaceCompositeOp
ModulateCompositeOp
ThresholdCompositeOp
NoCompositeOp
DarkenCompositeOp
LightenCompositeOp
HueCompositeOp
SaturateCompositeOp
ColorizeCompositeOp
LuminizeCompositeOp
ScreenCompositeOp
OverlayCompositeOp
CopyCyanCompositeOp
CopyMagentaCompositeOp
CopyYellowCompositeOp
CopyBlackCompositeOp
DivideCompositeOp
HardLightCompositeOp
ExclusionCompositeOp
ColorDodgeCompositeOp
ColorBurnCompositeOp
SoftLightCompositeOp
LinearBurnCompositeOp
LinearDodgeCompositeOp
LinearLightCompositeOp
VividLightCompositeOp
PinLightCompositeOp
HardMixCompositeOp
CompressionType
enum CompressionType
Enumerator
UndefinedCompression
NoCompression
BZipCompression
FaxCompression
Group3Compression
Group4Compression
JPEGCompression
LosslessJPEGCompression
LZWCompression
RLECompression
ZipCompression
LZMACompression
JPEG2000Compression
JBIG1Compression
JBIG2Compression
ZSTDCompression
WebPCompression
DisposeType
enum DisposeType
Enumerator
UndefinedDispose
NoneDispose
BackgroundDispose
PreviousDispose
EndianType
enum EndianType
Enumerator
UndefinedEndian
LSBEndian
MSBEndian
NativeEndian
FilterTypes
enum FilterTypes
Enumerator
UndefinedFilter
PointFilter
BoxFilter
TriangleFilter
HermiteFilter
HanningFilter
HammingFilter
BlackmanFilter
GaussianFilter
QuadraticFilter
CubicFilter
CatromFilter
MitchellFilter
LanczosFilter
BesselFilter
SincFilter
GeometryFlags
enum GeometryFlags
Enumerator
NoValue
XValue
YValue
WidthValue
HeightValue
AllValues
XNegative
YNegative
PercentValue
AspectValue
LessValue
GreaterValue
AreaValue
MinimumValue
GravityType
enum GravityType
Enumerator
ForgetGravity
NorthWestGravity
NorthGravity
NorthEastGravity
WestGravity
CenterGravity
EastGravity
SouthWestGravity
SouthGravity
SouthEastGravity
StaticGravity
ImageType
enum ImageType
Enumerator
UndefinedType
BilevelType
GrayscaleType
GrayscaleMatteType
PaletteType
PaletteMatteType
TrueColorType
TrueColorMatteType
ColorSeparationType
ColorSeparationMatteType
OptimizeType
InterlaceType
enum InterlaceType
Enumerator
UndefinedInterlace
NoInterlace
LineInterlace
PlaneInterlace
PartitionInterlace
MontageMode
enum MontageMode
Enumerator
UndefinedMode
FrameMode
UnframeMode
ConcatenateMode
NoiseType
enum NoiseType
Enumerator
UniformNoise
GaussianNoise
MultiplicativeGaussianNoise
ImpulseNoise
LaplacianNoise
PoissonNoise
RandomNoise
UndefinedNoise
OrientationType
enum OrientationType
Enumerator
UndefinedOrientation
TopLeftOrientation
TopRightOrientation
BottomRightOrientation
BottomLeftOrientation
LeftTopOrientation
RightTopOrientation
RightBottomOrientation
LeftBottomOrientation
PreviewType
enum PreviewType
Enumerator
UndefinedPreview
RotatePreview
ShearPreview
RollPreview
HuePreview
SaturationPreview
BrightnessPreview
GammaPreview
SpiffPreview
DullPreview
GrayscalePreview
QuantizePreview
DespecklePreview
ReduceNoisePreview
AddNoisePreview
SharpenPreview
BlurPreview
ThresholdPreview
EdgeDetectPreview
SpreadPreview
SolarizePreview
ShadePreview
RaisePreview
SegmentPreview
SwirlPreview
ImplodePreview
WavePreview
OilPaintPreview
CharcoalDrawingPreview
JPEGPreview
RenderingIntent
enum RenderingIntent
Enumerator
UndefinedIntent
SaturationIntent
PerceptualIntent
AbsoluteIntent
RelativeIntent
ResolutionType
enum ResolutionType
Enumerator
UndefinedResolution
PixelsPerInchResolution
PixelsPerCentimeterResolution
Function Documentation
AccessDefinition()
MagickExport const char * AccessDefinition (const ImageInfo * image_info, const char * magick, const char * key) extern
AddDefinition()
MagickExport MagickPassFail AddDefinition (ImageInfo * image_info, const char * magick, const char * key, const char * value, ExceptionInfo * exception) extern
AddDefinitions()
MagickExport MagickPassFail AddDefinitions (ImageInfo * image_info, const char * options, ExceptionInfo * exception)
AllocateImage()
MagickExport Image * AllocateImage (const ImageInfo *) extern
AllocateNextImage()
MagickExport void AllocateNextImage (const ImageInfo * , Image *) extern
AnimateImages()
MagickExport MagickPassFail AnimateImages (const ImageInfo * image_info, Image * image)
AppendImages()
MagickExport Image * AppendImages (const Image * , const unsigned int , ExceptionInfo *)
CatchImageException()
MagickExport ExceptionType CatchImageException (Image *) extern
ClipImage()
MagickExport MagickPassFail ClipImage (Image * image)
ClipPathImage()
MagickExport MagickPassFail ClipPathImage (Image * image, const char * pathname, const MagickBool inside)
CloneImage()
MagickExport Image * CloneImage (const Image * , const unsigned long , const unsigned long , const unsigned int , ExceptionInfo *)
CloneImageInfo()
MagickExport ImageInfo * CloneImageInfo (const ImageInfo *) extern
Referenced by chronos_process_image(), chronos_resize_image(), and chronos_rgb_to_ycocg().
CompositeMaskImage()
MagickExport MagickPassFail CompositeMaskImage (Image * image)
CompositePathImage()
MagickExport MagickPassFail CompositePathImage (Image * image, const char * pathname, const MagickBool inside)
DestroyImage()
MagickExport void DestroyImage (Image *)
Referenced by chronos_process_image(), chronos_resize_image(), and chronos_rgb_to_ycocg().
DestroyImageInfo()
MagickExport void DestroyImageInfo (ImageInfo *)
Referenced by chronos_process_image(), chronos_resize_image(), and chronos_rgb_to_ycocg().
DisplayImages()
MagickExport MagickPassFail DisplayImages (const ImageInfo * image_info, Image * image)
GetImageClipMask()
MagickExport Image * GetImageClipMask (const Image * , ExceptionInfo *)
GetImageCompositeMask()
MagickExport Image * GetImageCompositeMask (const Image * , ExceptionInfo *)
GetImageException()
MagickExport void GetImageException (Image * , ExceptionInfo *)
GetImageGeometry()
MagickExport int GetImageGeometry (const Image * , const char * , const unsigned int , RectangleInfo *) extern
GetImageInfo()
MagickExport void GetImageInfo (ImageInfo *)
ImageGetClipMask()
MagickExport Image ** ImageGetClipMask (const Image *) extern
ImageGetCompositeMask()
MagickExport Image ** ImageGetCompositeMask (const Image *) extern
IsSubimage()
MagickExport MagickBool IsSubimage (const char * , const MagickBool)
IsTaintImage()
MagickExport MagickBool IsTaintImage (const Image *) extern
ModifyImage()
MagickExport void ModifyImage (Image ** , ExceptionInfo *)
ReferenceImage()
MagickExport Image * ReferenceImage (Image *)
RemoveDefinitions()
MagickExport MagickPassFail RemoveDefinitions (const ImageInfo * image_info, const char * options)
ResetImagePage()
MagickExport MagickPassFail ResetImagePage (Image * image, const char * page)
SetImage()
MagickExport MagickPassFail SetImage (Image * image, const Quantum)
SetImageClipMask()
MagickExport MagickPassFail SetImageClipMask (Image * image, const Image * clip_mask)
SetImageColor()
MagickExport MagickPassFail SetImageColor (Image * image, const PixelPacket * pixel)
SetImageColorRegion()
MagickExport MagickPassFail SetImageColorRegion (Image * image, long x, long y, unsigned long width, unsigned long height, const PixelPacket * pixel)
SetImageCompositeMask()
MagickExport MagickPassFail SetImageCompositeMask (Image * image, const Image * composite_mask)
SetImageDepth()
MagickExport MagickPassFail SetImageDepth (Image * image, const unsigned long)
SetImageEx()
MagickExport MagickPassFail SetImageEx (Image * image, const Quantum opacity, ExceptionInfo * exception)
SetImageInfo()
MagickExport MagickPassFail SetImageInfo (ImageInfo * image_info, const unsigned int flags, ExceptionInfo * exception)
SetImageOpacity()
MagickExport MagickPassFail SetImageOpacity (Image * , const unsigned int)
SetImageType()
MagickExport MagickPassFail SetImageType (Image * image, const ImageType)
StripImage()
MagickExport MagickPassFail StripImage (Image * image)
SyncImage()
MagickExport MagickPassFail SyncImage (Image * image)