CHRONOS-LoRa: /usr/include/GraphicsMagick/magick/magick.h File Reference
magick.h File Reference
Classes
struct _MagickInfo
Macros
#define MAGICK_OPT_NO_SIGNAL_HANDER 0x0001 /* Don't register ANSI/POSIX signal handlers */
Typedefs
typedef Image *(* DecoderHandler) (const ImageInfo *, ExceptionInfo *)
typedef unsigned int(* EncoderHandler) (const ImageInfo *, Image *)
typedef unsigned int(*)(* MagickHandler) (const unsigned char *, const size_t)
typedef struct _MagickInfo MagickInfo
Enumerations
enum CoderClass { BrokenCoderClass = -1 , UnstableCoderClass = 0 , StableCoderClass , PrimaryCoderClass }
enum ExtensionTreatment { HintExtensionTreatment = 0 , ObeyExtensionTreatment , IgnoreExtensionTreatment }
Functions
MagickExport char * MagickToMime (const char *magick)
MagickExport const char * GetImageMagick (const unsigned char *magick, const size_t length)
MagickExport MagickBool IsMagickConflict (const char *magick) MAGICK_FUNC_PURE
MagickExport MagickPassFail ListModuleMap (FILE *file, ExceptionInfo *exception)
MagickExport MagickPassFail ListMagickInfo (FILE *file, ExceptionInfo *exception)
MagickExport MagickPassFail InitializeMagickEx (const char *path, unsigned int options, ExceptionInfo *exception)
MagickExport MagickPassFail UnregisterMagickInfo (const char *name)
MagickExport void DestroyMagick (void)
MagickExport void InitializeMagick (const char *path)
MagickExport void PanicDestroyMagick (void)
MagickExport const MagickInfo * GetMagickInfo (const char *name, ExceptionInfo *exception)
MagickExport MagickInfo ** GetMagickInfoArray (ExceptionInfo *exception)
MagickExport MagickInfo * RegisterMagickInfo (MagickInfo *magick_info)
MagickExport MagickInfo * SetMagickInfo (const char *name)
Macro Definition Documentation
MAGICK_OPT_NO_SIGNAL_HANDER
#define MAGICK_OPT_NO_SIGNAL_HANDER 0x0001 /* Don't register ANSI/POSIX signal handlers */
Typedef Documentation
DecoderHandler
typedef Image *(* DecoderHandler) (const ImageInfo *, ExceptionInfo *)
EncoderHandler
typedef unsigned int(* EncoderHandler) (const ImageInfo *, Image *)
MagickHandler
typedef unsigned int(*)(* MagickHandler) (const unsigned char *, const size_t)
MagickInfo
typedef struct _MagickInfo MagickInfo
Enumeration Type Documentation
CoderClass
enum CoderClass
Enumerator
BrokenCoderClass
UnstableCoderClass
StableCoderClass
PrimaryCoderClass
ExtensionTreatment
enum ExtensionTreatment
Enumerator
HintExtensionTreatment
ObeyExtensionTreatment
IgnoreExtensionTreatment
Function Documentation
DestroyMagick()
MagickExport void DestroyMagick (void) extern
Referenced by chronos_process_image(), chronos_resize_image(), and chronos_rgb_to_ycocg().
GetImageMagick()
MagickExport const char * GetImageMagick (const unsigned char * magick, const size_t length) extern
GetMagickInfo()
MagickExport const MagickInfo * GetMagickInfo (const char * name, ExceptionInfo * exception) extern
GetMagickInfoArray()
MagickExport MagickInfo ** GetMagickInfoArray (ExceptionInfo * exception) extern
InitializeMagick()
MagickExport void InitializeMagick (const char * path)
Referenced by chronos_process_image(), chronos_resize_image(), chronos_rgb_to_grayscale(), and chronos_rgb_to_ycocg().
InitializeMagickEx()
MagickExport MagickPassFail InitializeMagickEx (const char * path, unsigned int options, ExceptionInfo * exception)
IsMagickConflict()
MagickExport MagickBool IsMagickConflict (const char * magick) extern
ListMagickInfo()
MagickExport MagickPassFail ListMagickInfo (FILE * file, ExceptionInfo * exception)
ListModuleMap()
MagickExport MagickPassFail ListModuleMap (FILE * file, ExceptionInfo * exception) extern
MagickToMime()
MagickExport char * MagickToMime (const char * magick) extern
PanicDestroyMagick()
MagickExport void PanicDestroyMagick (void)
RegisterMagickInfo()
MagickExport MagickInfo * RegisterMagickInfo (MagickInfo * magick_info) extern
SetMagickInfo()
MagickExport MagickInfo * SetMagickInfo (const char * name)
UnregisterMagickInfo()
MagickExport MagickPassFail UnregisterMagickInfo (const char * name)