CHRONOS-LoRa: /usr/include/GraphicsMagick/wand/magick_wand.h File Reference
magick_wand.h File Reference
#include "magick/api.h"
#include "wand/wand_symbols.h"
#include "wand/drawing_wand.h"
#include "wand/pixel_wand.h"
Macros
#define WandExport
#define MagickSizeType magick_int64_t
#define ReplaceCompositeOp CopyCompositeOp
#define IndexChannel BlackChannel
#define AreaResource UndefinedResource /* not supported */
Typedefs
typedef struct _MagickWand MagickWand
Functions
WandExport int FormatMagickString (char *, const size_t, const char *,...) MAGICK_ATTRIBUTE((format(printf
WandExport int WandExport size_t CopyMagickString (char *, const char *, const size_t)
WandExport char * MagickDescribeImage (MagickWand *)
WandExport char * MagickGetConfigureInfo (MagickWand *, const char *) MAGICK_FUNC_CONST
WandExport char * MagickGetException (const MagickWand *, ExceptionType *)
WandExport char * MagickGetFilename (const MagickWand *)
WandExport char * MagickGetImageAttribute (MagickWand *, const char *)
WandExport char * MagickGetImageFilename (MagickWand *)
WandExport char * MagickGetImageFormat (MagickWand *)
WandExport char * MagickGetImageSignature (MagickWand *)
WandExport char ** MagickQueryFonts (const char *, unsigned long *)
WandExport char ** MagickQueryFormats (const char *, unsigned long *)
WandExport CompositeOperator MagickGetImageCompose (MagickWand *)
WandExport ColorspaceType MagickGetImageColorspace (MagickWand *)
WandExport CompressionType MagickGetImageCompression (MagickWand *)
WandExport const char * MagickGetCopyright (void) MAGICK_FUNC_CONST
WandExport const char * MagickGetHomeURL (void) MAGICK_FUNC_CONST
WandExport const char * MagickGetImageGeometry (MagickWand *)
WandExport const char * MagickGetPackageName (void) MAGICK_FUNC_CONST
WandExport const char * MagickGetQuantumDepth (unsigned long *)
WandExport const char * MagickGetReleaseDate (void) MAGICK_FUNC_CONST
WandExport const char * MagickGetVersion (unsigned long *) MAGICK_FUNC_CONST
WandExport DisposeType MagickGetImageDispose (MagickWand *)
WandExport double MagickGetImageGamma (MagickWand *)
WandExport double MagickGetImageFuzz (MagickWand *)
WandExport double * MagickGetSamplingFactors (MagickWand *, unsigned long *)
WandExport double * MagickQueryFontMetrics (MagickWand *, const DrawingWand *, const char *)
WandExport GravityType MagickGetImageGravity (MagickWand *wand)
WandExport ImageType MagickGetImageType (MagickWand *)
WandExport ImageType MagickGetImageSavedType (MagickWand *) MAGICK_FUNC_PURE
WandExport InterlaceType MagickGetImageInterlaceScheme (MagickWand *)
WandExport long MagickGetImageIndex (MagickWand *)
WandExport MagickSizeType MagickGetImageSize (MagickWand *)
WandExport MagickWand * CloneMagickWand (const MagickWand *)
WandExport MagickWand * MagickAppendImages (MagickWand *, const unsigned int)
WandExport MagickWand * MagickAverageImages (MagickWand *)
WandExport MagickWand * MagickCoalesceImages (MagickWand *)
WandExport MagickWand * MagickCompareImageChannels (MagickWand *, const MagickWand *, const ChannelType, const MetricType, double *)
WandExport MagickWand * MagickCompareImages (MagickWand *, const MagickWand *, const MetricType, double *)
WandExport MagickWand * MagickDeconstructImages (MagickWand *)
WandExport MagickWand * MagickFlattenImages (MagickWand *)
WandExport MagickWand * MagickFxImage (MagickWand *, const char *)
WandExport MagickWand * MagickFxImageChannel (MagickWand *, const ChannelType, const char *)
WandExport MagickWand * MagickGetImage (MagickWand *)
WandExport MagickWand * MagickMorphImages (MagickWand *, const unsigned long)
WandExport MagickWand * MagickMosaicImages (MagickWand *)
WandExport MagickWand * MagickMontageImage (MagickWand *, const DrawingWand *, const char *, const char *, const MontageMode, const char *)
WandExport MagickWand * MagickPreviewImages (MagickWand *wand, const PreviewType)
WandExport MagickWand * MagickSteganoImage (MagickWand *, const MagickWand *, const long)
WandExport MagickWand * MagickStereoImage (MagickWand *, const MagickWand *)
WandExport MagickWand * MagickTextureImage (MagickWand *, const MagickWand *)
WandExport MagickWand * MagickTransformImage (MagickWand *, const char *, const char *)
WandExport MagickWand * NewMagickWand (void)
WandExport OrientationType MagickGetImageOrientation (MagickWand *)
WandExport PixelWand ** MagickGetImageHistogram (MagickWand *, unsigned long *)
WandExport RenderingIntent MagickGetImageRenderingIntent (MagickWand *)
WandExport ResolutionType MagickGetImageUnits (MagickWand *)
WandExport unsigned int DestroyMagickWand (MagickWand *)
WandExport unsigned int MagickAdaptiveThresholdImage (MagickWand *, const unsigned long, const unsigned long, const long)
WandExport unsigned int MagickAddImage (MagickWand *, const MagickWand *)
WandExport unsigned int MagickAddNoiseImage (MagickWand *, const NoiseType)
WandExport unsigned int MagickAffineTransformImage (MagickWand *, const DrawingWand *)
WandExport unsigned int MagickAnnotateImage (MagickWand *, const DrawingWand *, const double, const double, const double, const char *)
WandExport unsigned int MagickAnimateImages (MagickWand *, const char *)
WandExport unsigned int MagickAutoOrientImage (MagickWand *wand, const OrientationType)
WandExport unsigned int MagickBlackThresholdImage (MagickWand *, const PixelWand *)
WandExport unsigned int MagickBlurImage (MagickWand *, const double, const double)
WandExport unsigned int MagickBorderImage (MagickWand *, const PixelWand *, const unsigned long, const unsigned long)
WandExport unsigned int MagickCdlImage (MagickWand *wand, const char *cdl)
WandExport unsigned int MagickCharcoalImage (MagickWand *, const double, const double)
WandExport unsigned int MagickChopImage (MagickWand *, const unsigned long, const unsigned long, const long, const long)
WandExport unsigned int MagickClipImage (MagickWand *)
WandExport unsigned int MagickClipPathImage (MagickWand *, const char *, const unsigned int)
WandExport unsigned int MagickColorFloodfillImage (MagickWand *, const PixelWand *, const double, const PixelWand *, const long, const long)
WandExport unsigned int MagickColorizeImage (MagickWand *, const PixelWand *, const PixelWand *)
WandExport unsigned int MagickCommentImage (MagickWand *, const char *)
WandExport unsigned int MagickCompositeImage (MagickWand *, const MagickWand *, const CompositeOperator, const long, const long)
WandExport unsigned int MagickContrastImage (MagickWand *, const unsigned int)
WandExport unsigned int MagickConvolveImage (MagickWand *, const unsigned long, const double *)
WandExport unsigned int MagickCropImage (MagickWand *, const unsigned long, const unsigned long, const long, const long)
WandExport unsigned int MagickCycleColormapImage (MagickWand *, const long)
WandExport unsigned int MagickDespeckleImage (MagickWand *)
WandExport unsigned int MagickDisplayImage (MagickWand *, const char *)
WandExport unsigned int MagickDisplayImages (MagickWand *, const char *)
WandExport unsigned int MagickDrawImage (MagickWand *, const DrawingWand *)
WandExport unsigned int MagickEdgeImage (MagickWand *, const double)
WandExport unsigned int MagickEmbossImage (MagickWand *, const double, const double)
WandExport unsigned int MagickEnhanceImage (MagickWand *)
WandExport unsigned int MagickEqualizeImage (MagickWand *)
WandExport unsigned int MagickExtentImage (MagickWand *, const size_t, const size_t, const ssize_t, const ssize_t)
WandExport unsigned int MagickFlipImage (MagickWand *)
WandExport unsigned int MagickFlopImage (MagickWand *)
WandExport unsigned int MagickFrameImage (MagickWand *, const PixelWand *, const unsigned long, const unsigned long, const long, const long)
WandExport unsigned int MagickGammaImage (MagickWand *, const double)
WandExport unsigned int MagickGammaImageChannel (MagickWand *, const ChannelType, const double)
WandExport unsigned int MagickGetImageBackgroundColor (MagickWand *, PixelWand *)
WandExport unsigned int MagickGetImageBluePrimary (MagickWand *, double *, double *)
WandExport unsigned int MagickGetImageBorderColor (MagickWand *, PixelWand *)
WandExport unsigned int MagickGetImageBoundingBox (MagickWand *wand, const double fuzz, unsigned long *width, unsigned long *height, long *x, long *y)
WandExport unsigned int MagickGetImageChannelExtrema (MagickWand *, const ChannelType, unsigned long *, unsigned long *)
WandExport unsigned int MagickGetImageChannelMean (MagickWand *, const ChannelType, double *, double *)
WandExport unsigned int MagickGetImageColormapColor (MagickWand *, const unsigned long, PixelWand *)
WandExport unsigned int MagickGetImageExtrema (MagickWand *, unsigned long *, unsigned long *)
WandExport unsigned int MagickGetImageGreenPrimary (MagickWand *, double *, double *)
WandExport unsigned int MagickGetImageMatte (MagickWand *)
WandExport unsigned int MagickGetImageMatteColor (MagickWand *, PixelWand *)
WandExport unsigned int MagickGetImagePage (MagickWand *wand, unsigned long *width, unsigned long *height, long *x, long *y)
WandExport unsigned int MagickGetImagePixels (MagickWand *, const long, const long, const unsigned long, const unsigned long, const char *, const StorageType, unsigned char *)
WandExport unsigned int MagickGetImageRedPrimary (MagickWand *, double *, double *)
WandExport unsigned int MagickGetImageResolution (MagickWand *, double *, double *)
WandExport unsigned int MagickGetImageWhitePoint (MagickWand *, double *, double *)
WandExport unsigned int MagickGetSize (const MagickWand *, unsigned long *, unsigned long *)
WandExport unsigned int MagickHaldClutImage (MagickWand *wand, const MagickWand *clut_wand)
WandExport unsigned int MagickHasColormap (MagickWand *, unsigned int *)
WandExport unsigned int MagickHasNextImage (MagickWand *)
WandExport unsigned int MagickHasPreviousImage (MagickWand *)
WandExport unsigned int MagickImplodeImage (MagickWand *, const double)
WandExport unsigned int MagickIsGrayImage (MagickWand *, unsigned int *)
WandExport unsigned int MagickIsMonochromeImage (MagickWand *, unsigned int *)
WandExport unsigned int MagickIsOpaqueImage (MagickWand *, unsigned int *)
WandExport unsigned int MagickIsPaletteImage (MagickWand *, unsigned int *)
WandExport unsigned int MagickLabelImage (MagickWand *, const char *)
WandExport unsigned int MagickLevelImage (MagickWand *, const double, const double, const double)
WandExport unsigned int MagickLevelImageChannel (MagickWand *, const ChannelType, const double, const double, const double)
WandExport unsigned int MagickMagnifyImage (MagickWand *)
WandExport unsigned int MagickMapImage (MagickWand *, const MagickWand *, const unsigned int)
WandExport unsigned int MagickMatteFloodfillImage (MagickWand *, const Quantum, const double, const PixelWand *, const long, const long)
WandExport unsigned int MagickMedianFilterImage (MagickWand *, const double)
WandExport unsigned int MagickMinifyImage (MagickWand *)
WandExport unsigned int MagickModulateImage (MagickWand *, const double, const double, const double)
WandExport unsigned int MagickMotionBlurImage (MagickWand *, const double, const double, const double)
WandExport unsigned int MagickNegateImage (MagickWand *, const unsigned int)
WandExport unsigned int MagickNegateImageChannel (MagickWand *, const ChannelType, const unsigned int)
WandExport unsigned int MagickNextImage (MagickWand *)
WandExport unsigned int MagickNormalizeImage (MagickWand *)
WandExport unsigned int MagickOilPaintImage (MagickWand *, const double)
WandExport unsigned int MagickOpaqueImage (MagickWand *, const PixelWand *, const PixelWand *, const double)
WandExport unsigned int MagickOperatorImageChannel (MagickWand *, const ChannelType, const QuantumOperator, const double)
WandExport unsigned int MagickPingImage (MagickWand *, const char *)
WandExport unsigned int MagickPreviousImage (MagickWand *)
WandExport unsigned int MagickProfileImage (MagickWand *, const char *, const unsigned char *, const unsigned long)
WandExport unsigned int MagickQuantizeImage (MagickWand *, const unsigned long, const ColorspaceType, const unsigned long, const unsigned int, const unsigned int)
WandExport unsigned int MagickQuantizeImages (MagickWand *, const unsigned long, const ColorspaceType, const unsigned long, const unsigned int, const unsigned int)
WandExport unsigned int MagickRadialBlurImage (MagickWand *, const double)
WandExport unsigned int MagickRaiseImage (MagickWand *, const unsigned long, const unsigned long, const long, const long, const unsigned int)
WandExport unsigned int MagickReadImage (MagickWand *, const char *)
WandExport unsigned int MagickReadImageBlob (MagickWand *, const unsigned char *, const size_t length)
WandExport unsigned int MagickReadImageFile (MagickWand *, FILE *)
WandExport unsigned int MagickReduceNoiseImage (MagickWand *, const double)
WandExport unsigned int MagickRelinquishMemory (void *)
WandExport unsigned int MagickRemoveImage (MagickWand *)
WandExport unsigned int MagickRemoveImageOption (MagickWand *wand, const char *, const char *)
WandExport unsigned int MagickResampleImage (MagickWand *, const double, const double, const FilterTypes, const double)
WandExport unsigned int MagickResizeImage (MagickWand *, const unsigned long, const unsigned long, const FilterTypes, const double)
WandExport unsigned int MagickRollImage (MagickWand *, const long, const long)
WandExport unsigned int MagickRotateImage (MagickWand *, const PixelWand *, const double)
WandExport unsigned int MagickSampleImage (MagickWand *, const unsigned long, const unsigned long)
WandExport unsigned int MagickScaleImage (MagickWand *, const unsigned long, const unsigned long)
WandExport unsigned int MagickSeparateImageChannel (MagickWand *, const ChannelType)
WandExport unsigned int MagickSetCompressionQuality (MagickWand *wand, const unsigned long quality)
WandExport unsigned int MagickSetFilename (MagickWand *, const char *)
WandExport unsigned int MagickSetFormat (MagickWand *, const char *)
WandExport unsigned int MagickSetImage (MagickWand *, const MagickWand *)
WandExport unsigned int MagickSetImageAttribute (MagickWand *, const char *, const char *)
WandExport unsigned int MagickSetImageBackgroundColor (MagickWand *, const PixelWand *)
WandExport unsigned int MagickSetImageBluePrimary (MagickWand *, const double, const double)
WandExport unsigned int MagickSetImageBorderColor (MagickWand *, const PixelWand *)
WandExport unsigned int MagickSetImageChannelDepth (MagickWand *, const ChannelType, const unsigned long)
WandExport unsigned int MagickSetImageColormapColor (MagickWand *, const unsigned long, const PixelWand *)
WandExport unsigned int MagickSetImageCompose (MagickWand *, const CompositeOperator)
WandExport unsigned int MagickSetImageCompression (MagickWand *, const CompressionType)
WandExport unsigned int MagickSetImageDelay (MagickWand *, const unsigned long)
WandExport unsigned int MagickSetImageDepth (MagickWand *, const unsigned long)
WandExport unsigned int MagickSetImageDispose (MagickWand *, const DisposeType)
WandExport unsigned int MagickSetImageColorspace (MagickWand *, const ColorspaceType)
WandExport unsigned int MagickSetImageGreenPrimary (MagickWand *, const double, const double)
WandExport unsigned int MagickSetImageGamma (MagickWand *, const double)
WandExport unsigned int MagickSetImageGeometry (MagickWand *, const char *)
WandExport unsigned int MagickSetImageGravity (MagickWand *, const GravityType)
WandExport unsigned int MagickSetImageFilename (MagickWand *, const char *)
WandExport unsigned int MagickSetImageFormat (MagickWand *wand, const char *format)
WandExport unsigned int MagickSetImageFuzz (MagickWand *, const double)
WandExport unsigned int MagickSetImageIndex (MagickWand *, const long)
WandExport unsigned int MagickSetImageInterlaceScheme (MagickWand *, const InterlaceType)
WandExport unsigned int MagickSetImageIterations (MagickWand *, const unsigned long)
WandExport unsigned int MagickSetImageMatte (MagickWand *, const unsigned int)
WandExport unsigned int MagickSetImageMatteColor (MagickWand *, const PixelWand *)
WandExport unsigned int MagickSetImageOption (MagickWand *, const char *, const char *, const char *)
WandExport unsigned int MagickSetImageOrientation (MagickWand *, const OrientationType)
WandExport unsigned int MagickSetImagePage (MagickWand *wand, const unsigned long width, const unsigned long height, const long x, const long y)
WandExport unsigned int MagickSetImagePixels (MagickWand *, const long, const long, const unsigned long, const unsigned long, const char *, const StorageType, unsigned char *)
WandExport unsigned int MagickSetImageRedPrimary (MagickWand *, const double, const double)
WandExport unsigned int MagickSetImageRenderingIntent (MagickWand *, const RenderingIntent)
WandExport unsigned int MagickSetImageResolution (MagickWand *, const double, const double)
WandExport unsigned int MagickSetImageScene (MagickWand *, const unsigned long)
WandExport unsigned int MagickSetImageType (MagickWand *, const ImageType)
WandExport unsigned int MagickSetImageSavedType (MagickWand *, const ImageType)
WandExport unsigned int MagickSetImageUnits (MagickWand *, const ResolutionType)
WandExport unsigned int MagickSetImageVirtualPixelMethod (MagickWand *, const VirtualPixelMethod)
WandExport unsigned int MagickSetPassphrase (MagickWand *, const char *)
WandExport unsigned int MagickSetImageProfile (MagickWand *, const char *, const unsigned char *, const unsigned long)
WandExport unsigned int MagickSetResolution (MagickWand *wand, const double x_resolution, const double y_resolution)
WandExport unsigned int MagickSetResolutionUnits (MagickWand *wand, const ResolutionType units)
WandExport unsigned int MagickSetResourceLimit (const ResourceType type, const unsigned long limit)
WandExport unsigned int MagickSetSamplingFactors (MagickWand *, const unsigned long, const double *)
WandExport unsigned int MagickSetSize (MagickWand *, const unsigned long, const unsigned long)
WandExport unsigned int MagickSetImageWhitePoint (MagickWand *, const double, const double)
WandExport unsigned int MagickSetInterlaceScheme (MagickWand *, const InterlaceType)
WandExport unsigned int MagickSharpenImage (MagickWand *, const double, const double)
WandExport unsigned int MagickShaveImage (MagickWand *, const unsigned long, const unsigned long)
WandExport unsigned int MagickShearImage (MagickWand *, const PixelWand *, const double, const double)
WandExport unsigned int MagickSolarizeImage (MagickWand *, const double)
WandExport unsigned int MagickSpreadImage (MagickWand *, const double)
WandExport unsigned int MagickStripImage (MagickWand *)
WandExport unsigned int MagickSwirlImage (MagickWand *, const double)
WandExport unsigned int MagickTintImage (MagickWand *, const PixelWand *, const PixelWand *)
WandExport unsigned int MagickThresholdImage (MagickWand *, const double)
WandExport unsigned int MagickThresholdImageChannel (MagickWand *, const ChannelType, const double)
WandExport unsigned int MagickTransparentImage (MagickWand *, const PixelWand *, const Quantum, const double)
WandExport unsigned int MagickTrimImage (MagickWand *, const double)
WandExport unsigned int MagickUnsharpMaskImage (MagickWand *, const double, const double, const double, const double)
WandExport unsigned int MagickWaveImage (MagickWand *, const double, const double)
WandExport unsigned int MagickWhiteThresholdImage (MagickWand *, const PixelWand *)
WandExport unsigned int MagickWriteImage (MagickWand *, const char *)
WandExport unsigned int MagickWriteImageFile (MagickWand *, FILE *)
WandExport unsigned int MagickWriteImagesFile (MagickWand *, FILE *, const unsigned int)
WandExport unsigned int MagickWriteImages (MagickWand *, const char *, const unsigned int)
WandExport unsigned long MagickGetImageColors (MagickWand *)
WandExport unsigned long MagickGetImageDelay (MagickWand *)
WandExport unsigned long MagickGetImageChannelDepth (MagickWand *, const ChannelType)
WandExport unsigned long MagickGetImageDepth (MagickWand *)
WandExport unsigned long MagickGetImageHeight (MagickWand *)
WandExport unsigned long MagickGetImageIterations (MagickWand *)
WandExport unsigned long MagickGetImageScene (MagickWand *)
WandExport unsigned long MagickGetImageWidth (MagickWand *)
WandExport unsigned long MagickGetNumberImages (MagickWand *)
WandExport unsigned long MagickGetResourceLimit (const ResourceType)
WandExport VirtualPixelMethod MagickGetImageVirtualPixelMethod (MagickWand *)
WandExport unsigned char * MagickGetImageProfile (MagickWand *, const char *, unsigned long *)
WandExport unsigned char * MagickRemoveImageProfile (MagickWand *, const char *, unsigned long *)
WandExport unsigned char * MagickWriteImageBlob (MagickWand *, size_t *)
WandExport void MagickClearException (MagickWand *)
WandExport void MagickResetIterator (MagickWand *)
Macro Definition Documentation
AreaResource
#define AreaResource UndefinedResource /* not supported */
IndexChannel
#define IndexChannel BlackChannel
MagickSizeType
#define MagickSizeType magick_int64_t
ReplaceCompositeOp
#define ReplaceCompositeOp CopyCompositeOp
WandExport
#define WandExport
Typedef Documentation
MagickWand
typedef struct _MagickWand MagickWand
Function Documentation
CloneMagickWand()
WandExport MagickWand * CloneMagickWand (const MagickWand *) extern
CopyMagickString()
WandExport int WandExport size_t CopyMagickString (char * , const char * , const size_t) extern
DestroyMagickWand()
WandExport unsigned int DestroyMagickWand (MagickWand *) extern
Referenced by chronos_rgb_to_grayscale().
FormatMagickString()
WandExport int FormatMagickString (char * , const size_t , const char * , ...) extern
MagickAdaptiveThresholdImage()
WandExport unsigned int MagickAdaptiveThresholdImage (MagickWand * , const unsigned long , const unsigned long , const long)
MagickAddImage()
WandExport unsigned int MagickAddImage (MagickWand * , const MagickWand *)
MagickAddNoiseImage()
WandExport unsigned int MagickAddNoiseImage (MagickWand * , const NoiseType)
MagickAffineTransformImage()
WandExport unsigned int MagickAffineTransformImage (MagickWand * , const DrawingWand *)
MagickAnimateImages()
WandExport unsigned int MagickAnimateImages (MagickWand * , const char *)
MagickAnnotateImage()
WandExport unsigned int MagickAnnotateImage (MagickWand * , const DrawingWand * , const double , const double , const double , const char *)
MagickAppendImages()
WandExport MagickWand * MagickAppendImages (MagickWand * , const unsigned int)
MagickAutoOrientImage()
WandExport unsigned int MagickAutoOrientImage (MagickWand * wand, const OrientationType)
MagickAverageImages()
WandExport MagickWand * MagickAverageImages (MagickWand *)
MagickBlackThresholdImage()
WandExport unsigned int MagickBlackThresholdImage (MagickWand * , const PixelWand *)
MagickBlurImage()
WandExport unsigned int MagickBlurImage (MagickWand * , const double , const double)
MagickBorderImage()
WandExport unsigned int MagickBorderImage (MagickWand * , const PixelWand * , const unsigned long , const unsigned long)
MagickCdlImage()
WandExport unsigned int MagickCdlImage (MagickWand * wand, const char * cdl)
MagickCharcoalImage()
WandExport unsigned int MagickCharcoalImage (MagickWand * , const double , const double)
MagickChopImage()
WandExport unsigned int MagickChopImage (MagickWand * , const unsigned long , const unsigned long , const long , const long)
MagickClearException()
WandExport void MagickClearException (MagickWand *) extern
MagickClipImage()
WandExport unsigned int MagickClipImage (MagickWand *)
MagickClipPathImage()
WandExport unsigned int MagickClipPathImage (MagickWand * , const char * , const unsigned int)
MagickCoalesceImages()
WandExport MagickWand * MagickCoalesceImages (MagickWand *)
MagickColorFloodfillImage()
WandExport unsigned int MagickColorFloodfillImage (MagickWand * , const PixelWand * , const double , const PixelWand * , const long , const long)
MagickColorizeImage()
WandExport unsigned int MagickColorizeImage (MagickWand * , const PixelWand * , const PixelWand *)
MagickCommentImage()
WandExport unsigned int MagickCommentImage (MagickWand * , const char *)
MagickCompareImageChannels()
WandExport MagickWand * MagickCompareImageChannels (MagickWand * , const MagickWand * , const ChannelType , const MetricType , double *)
MagickCompareImages()
WandExport MagickWand * MagickCompareImages (MagickWand * , const MagickWand * , const MetricType , double *)
MagickCompositeImage()
WandExport unsigned int MagickCompositeImage (MagickWand * , const MagickWand * , const CompositeOperator , const long , const long)
MagickContrastImage()
WandExport unsigned int MagickContrastImage (MagickWand * , const unsigned int)
MagickConvolveImage()
WandExport unsigned int MagickConvolveImage (MagickWand * , const unsigned long , const double *)
MagickCropImage()
WandExport unsigned int MagickCropImage (MagickWand * , const unsigned long , const unsigned long , const long , const long)
MagickCycleColormapImage()
WandExport unsigned int MagickCycleColormapImage (MagickWand * , const long)
MagickDeconstructImages()
WandExport MagickWand * MagickDeconstructImages (MagickWand *)
MagickDescribeImage()
WandExport char * MagickDescribeImage (MagickWand *) extern
MagickDespeckleImage()
WandExport unsigned int MagickDespeckleImage (MagickWand *)
MagickDisplayImage()
WandExport unsigned int MagickDisplayImage (MagickWand * , const char *)
MagickDisplayImages()
WandExport unsigned int MagickDisplayImages (MagickWand * , const char *)
MagickDrawImage()
WandExport unsigned int MagickDrawImage (MagickWand * , const DrawingWand *)
MagickEdgeImage()
WandExport unsigned int MagickEdgeImage (MagickWand * , const double)
MagickEmbossImage()
WandExport unsigned int MagickEmbossImage (MagickWand * , const double , const double)
MagickEnhanceImage()
WandExport unsigned int MagickEnhanceImage (MagickWand *)
MagickEqualizeImage()
WandExport unsigned int MagickEqualizeImage (MagickWand *)
MagickExtentImage()
WandExport unsigned int MagickExtentImage (MagickWand * , const size_t , const size_t , const ssize_t , const ssize_t)
MagickFlattenImages()
WandExport MagickWand * MagickFlattenImages (MagickWand *)
MagickFlipImage()
WandExport unsigned int MagickFlipImage (MagickWand *)
MagickFlopImage()
WandExport unsigned int MagickFlopImage (MagickWand *)
MagickFrameImage()
WandExport unsigned int MagickFrameImage (MagickWand * , const PixelWand * , const unsigned long , const unsigned long , const long , const long)
MagickFxImage()
WandExport MagickWand * MagickFxImage (MagickWand * , const char *)
MagickFxImageChannel()
WandExport MagickWand * MagickFxImageChannel (MagickWand * , const ChannelType , const char *)
MagickGammaImage()
WandExport unsigned int MagickGammaImage (MagickWand * , const double)
MagickGammaImageChannel()
WandExport unsigned int MagickGammaImageChannel (MagickWand * , const ChannelType , const double)
MagickGetConfigureInfo()
WandExport char * MagickGetConfigureInfo (MagickWand * , const char *)
MagickGetCopyright()
WandExport const char * MagickGetCopyright (void) extern
MagickGetException()
WandExport char * MagickGetException (const MagickWand * , ExceptionType *)
MagickGetFilename()
WandExport char * MagickGetFilename (const MagickWand *)
MagickGetHomeURL()
WandExport const char * MagickGetHomeURL (void)
MagickGetImage()
WandExport MagickWand * MagickGetImage (MagickWand *)
MagickGetImageAttribute()
WandExport char * MagickGetImageAttribute (MagickWand * , const char *)
MagickGetImageBackgroundColor()
WandExport unsigned int MagickGetImageBackgroundColor (MagickWand * , PixelWand *)
MagickGetImageBluePrimary()
WandExport unsigned int MagickGetImageBluePrimary (MagickWand * , double * , double *)
MagickGetImageBorderColor()
WandExport unsigned int MagickGetImageBorderColor (MagickWand * , PixelWand *)
MagickGetImageBoundingBox()
WandExport unsigned int MagickGetImageBoundingBox (MagickWand * wand, const double fuzz, unsigned long * width, unsigned long * height, long * x, long * y)
MagickGetImageChannelDepth()
WandExport unsigned long MagickGetImageChannelDepth (MagickWand * , const ChannelType)
MagickGetImageChannelExtrema()
WandExport unsigned int MagickGetImageChannelExtrema (MagickWand * , const ChannelType , unsigned long * , unsigned long *)
MagickGetImageChannelMean()
WandExport unsigned int MagickGetImageChannelMean (MagickWand * , const ChannelType , double * , double *)
MagickGetImageColormapColor()
WandExport unsigned int MagickGetImageColormapColor (MagickWand * , const unsigned long , PixelWand *)
MagickGetImageColors()
WandExport unsigned long MagickGetImageColors (MagickWand *) extern
MagickGetImageColorspace()
WandExport ColorspaceType MagickGetImageColorspace (MagickWand *) extern
MagickGetImageCompose()
WandExport CompositeOperator MagickGetImageCompose (MagickWand *) extern
MagickGetImageCompression()
WandExport CompressionType MagickGetImageCompression (MagickWand *) extern
MagickGetImageDelay()
WandExport unsigned long MagickGetImageDelay (MagickWand *)
MagickGetImageDepth()
WandExport unsigned long MagickGetImageDepth (MagickWand *)
MagickGetImageDispose()
WandExport DisposeType MagickGetImageDispose (MagickWand *) extern
MagickGetImageExtrema()
WandExport unsigned int MagickGetImageExtrema (MagickWand * , unsigned long * , unsigned long *)
MagickGetImageFilename()
WandExport char * MagickGetImageFilename (MagickWand *)
MagickGetImageFormat()
WandExport char * MagickGetImageFormat (MagickWand *)
MagickGetImageFuzz()
WandExport double MagickGetImageFuzz (MagickWand *)
MagickGetImageGamma()
WandExport double MagickGetImageGamma (MagickWand *) extern
MagickGetImageGeometry()
WandExport const char * MagickGetImageGeometry (MagickWand *)
MagickGetImageGravity()
WandExport GravityType MagickGetImageGravity (MagickWand * wand) extern
MagickGetImageGreenPrimary()
WandExport unsigned int MagickGetImageGreenPrimary (MagickWand * , double * , double *)
MagickGetImageHeight()
WandExport unsigned long MagickGetImageHeight (MagickWand *)
MagickGetImageHistogram()
WandExport PixelWand ** MagickGetImageHistogram (MagickWand * , unsigned long *) extern
MagickGetImageIndex()
WandExport long MagickGetImageIndex (MagickWand *) extern
MagickGetImageInterlaceScheme()
WandExport InterlaceType MagickGetImageInterlaceScheme (MagickWand *) extern
MagickGetImageIterations()
WandExport unsigned long MagickGetImageIterations (MagickWand *)
MagickGetImageMatte()
WandExport unsigned int MagickGetImageMatte (MagickWand *)
MagickGetImageMatteColor()
WandExport unsigned int MagickGetImageMatteColor (MagickWand * , PixelWand *)
MagickGetImageOrientation()
WandExport OrientationType MagickGetImageOrientation (MagickWand *) extern
MagickGetImagePage()
WandExport unsigned int MagickGetImagePage (MagickWand * wand, unsigned long * width, unsigned long * height, long * x, long * y)
MagickGetImagePixels()
WandExport unsigned int MagickGetImagePixels (MagickWand * , const long , const long , const unsigned long , const unsigned long , const char * , const StorageType , unsigned char *)
MagickGetImageProfile()
WandExport unsigned char * MagickGetImageProfile (MagickWand * , const char * , unsigned long *) extern
MagickGetImageRedPrimary()
WandExport unsigned int MagickGetImageRedPrimary (MagickWand * , double * , double *)
MagickGetImageRenderingIntent()
WandExport RenderingIntent MagickGetImageRenderingIntent (MagickWand *) extern
MagickGetImageResolution()
WandExport unsigned int MagickGetImageResolution (MagickWand * , double * , double *)
MagickGetImageSavedType()
WandExport ImageType MagickGetImageSavedType (MagickWand *) extern
MagickGetImageScene()
WandExport unsigned long MagickGetImageScene (MagickWand *)
MagickGetImageSignature()
WandExport char * MagickGetImageSignature (MagickWand *)
MagickGetImageSize()
WandExport MagickSizeType MagickGetImageSize (MagickWand *) extern
MagickGetImageType()
WandExport ImageType MagickGetImageType (MagickWand *) extern
MagickGetImageUnits()
WandExport ResolutionType MagickGetImageUnits (MagickWand *) extern
MagickGetImageVirtualPixelMethod()
WandExport VirtualPixelMethod MagickGetImageVirtualPixelMethod (MagickWand *) extern
MagickGetImageWhitePoint()
WandExport unsigned int MagickGetImageWhitePoint (MagickWand * , double * , double *)
MagickGetImageWidth()
WandExport unsigned long MagickGetImageWidth (MagickWand *)
MagickGetNumberImages()
WandExport unsigned long MagickGetNumberImages (MagickWand *)
MagickGetPackageName()
WandExport const char * MagickGetPackageName (void)
MagickGetQuantumDepth()
WandExport const char * MagickGetQuantumDepth (unsigned long *)
MagickGetReleaseDate()
WandExport const char * MagickGetReleaseDate (void)
MagickGetResourceLimit()
WandExport unsigned long MagickGetResourceLimit (const ResourceType)
MagickGetSamplingFactors()
WandExport double * MagickGetSamplingFactors (MagickWand * , unsigned long *)
MagickGetSize()
WandExport unsigned int MagickGetSize (const MagickWand * , unsigned long * , unsigned long *)
MagickGetVersion()
WandExport const char * MagickGetVersion (unsigned long *)
MagickHaldClutImage()
WandExport unsigned int MagickHaldClutImage (MagickWand * wand, const MagickWand * clut_wand)
MagickHasColormap()
WandExport unsigned int MagickHasColormap (MagickWand * , unsigned int *)
MagickHasNextImage()
WandExport unsigned int MagickHasNextImage (MagickWand *)
MagickHasPreviousImage()
WandExport unsigned int MagickHasPreviousImage (MagickWand *)
MagickImplodeImage()
WandExport unsigned int MagickImplodeImage (MagickWand * , const double)
MagickIsGrayImage()
WandExport unsigned int MagickIsGrayImage (MagickWand * , unsigned int *)
MagickIsMonochromeImage()
WandExport unsigned int MagickIsMonochromeImage (MagickWand * , unsigned int *)
MagickIsOpaqueImage()
WandExport unsigned int MagickIsOpaqueImage (MagickWand * , unsigned int *)
MagickIsPaletteImage()
WandExport unsigned int MagickIsPaletteImage (MagickWand * , unsigned int *)
MagickLabelImage()
WandExport unsigned int MagickLabelImage (MagickWand * , const char *)
MagickLevelImage()
WandExport unsigned int MagickLevelImage (MagickWand * , const double , const double , const double)
MagickLevelImageChannel()
WandExport unsigned int MagickLevelImageChannel (MagickWand * , const ChannelType , const double , const double , const double)
MagickMagnifyImage()
WandExport unsigned int MagickMagnifyImage (MagickWand *)
MagickMapImage()
WandExport unsigned int MagickMapImage (MagickWand * , const MagickWand * , const unsigned int)
MagickMatteFloodfillImage()
WandExport unsigned int MagickMatteFloodfillImage (MagickWand * , const Quantum , const double , const PixelWand * , const long , const long)
MagickMedianFilterImage()
WandExport unsigned int MagickMedianFilterImage (MagickWand * , const double)
MagickMinifyImage()
WandExport unsigned int MagickMinifyImage (MagickWand *)
MagickModulateImage()
WandExport unsigned int MagickModulateImage (MagickWand * , const double , const double , const double)
MagickMontageImage()
WandExport MagickWand * MagickMontageImage (MagickWand * , const DrawingWand * , const char * , const char * , const MontageMode , const char *)
MagickMorphImages()
WandExport MagickWand * MagickMorphImages (MagickWand * , const unsigned long)
MagickMosaicImages()
WandExport MagickWand * MagickMosaicImages (MagickWand *)
MagickMotionBlurImage()
WandExport unsigned int MagickMotionBlurImage (MagickWand * , const double , const double , const double)
MagickNegateImage()
WandExport unsigned int MagickNegateImage (MagickWand * , const unsigned int)
MagickNegateImageChannel()
WandExport unsigned int MagickNegateImageChannel (MagickWand * , const ChannelType , const unsigned int)
MagickNextImage()
WandExport unsigned int MagickNextImage (MagickWand *)
MagickNormalizeImage()
WandExport unsigned int MagickNormalizeImage (MagickWand *)
MagickOilPaintImage()
WandExport unsigned int MagickOilPaintImage (MagickWand * , const double)
MagickOpaqueImage()
WandExport unsigned int MagickOpaqueImage (MagickWand * , const PixelWand * , const PixelWand * , const double)
MagickOperatorImageChannel()
WandExport unsigned int MagickOperatorImageChannel (MagickWand * , const ChannelType , const QuantumOperator , const double)
MagickPingImage()
WandExport unsigned int MagickPingImage (MagickWand * , const char *)
MagickPreviewImages()
WandExport MagickWand * MagickPreviewImages (MagickWand * wand, const PreviewType)
MagickPreviousImage()
WandExport unsigned int MagickPreviousImage (MagickWand *)
MagickProfileImage()
WandExport unsigned int MagickProfileImage (MagickWand * , const char * , const unsigned char * , const unsigned long)
MagickQuantizeImage()
WandExport unsigned int MagickQuantizeImage (MagickWand * , const unsigned long , const ColorspaceType , const unsigned long , const unsigned int , const unsigned int)
MagickQuantizeImages()
WandExport unsigned int MagickQuantizeImages (MagickWand * , const unsigned long , const ColorspaceType , const unsigned long , const unsigned int , const unsigned int)
MagickQueryFontMetrics()
WandExport double * MagickQueryFontMetrics (MagickWand * , const DrawingWand * , const char *)
MagickQueryFonts()
WandExport char ** MagickQueryFonts (const char * , unsigned long *)
MagickQueryFormats()
WandExport char ** MagickQueryFormats (const char * , unsigned long *)
MagickRadialBlurImage()
WandExport unsigned int MagickRadialBlurImage (MagickWand * , const double)
MagickRaiseImage()
WandExport unsigned int MagickRaiseImage (MagickWand * , const unsigned long , const unsigned long , const long , const long , const unsigned int)
MagickReadImage()
WandExport unsigned int MagickReadImage (MagickWand * , const char *)
Referenced by chronos_rgb_to_grayscale().
MagickReadImageBlob()
WandExport unsigned int MagickReadImageBlob (MagickWand * , const unsigned char * , const size_t length)
MagickReadImageFile()
WandExport unsigned int MagickReadImageFile (MagickWand * , FILE *)
MagickReduceNoiseImage()
WandExport unsigned int MagickReduceNoiseImage (MagickWand * , const double)
MagickRelinquishMemory()
WandExport unsigned int MagickRelinquishMemory (void *)
MagickRemoveImage()
WandExport unsigned int MagickRemoveImage (MagickWand *)
MagickRemoveImageOption()
WandExport unsigned int MagickRemoveImageOption (MagickWand * wand, const char * , const char *)
MagickRemoveImageProfile()
WandExport unsigned char * MagickRemoveImageProfile (MagickWand * , const char * , unsigned long *)
MagickResampleImage()
WandExport unsigned int MagickResampleImage (MagickWand * , const double , const double , const FilterTypes , const double)
MagickResetIterator()
WandExport void MagickResetIterator (MagickWand *)
MagickResizeImage()
WandExport unsigned int MagickResizeImage (MagickWand * , const unsigned long , const unsigned long , const FilterTypes , const double)
MagickRollImage()
WandExport unsigned int MagickRollImage (MagickWand * , const long , const long)
MagickRotateImage()
WandExport unsigned int MagickRotateImage (MagickWand * , const PixelWand * , const double)
MagickSampleImage()
WandExport unsigned int MagickSampleImage (MagickWand * , const unsigned long , const unsigned long)
MagickScaleImage()
WandExport unsigned int MagickScaleImage (MagickWand * , const unsigned long , const unsigned long)
MagickSeparateImageChannel()
WandExport unsigned int MagickSeparateImageChannel (MagickWand * , const ChannelType)
MagickSetCompressionQuality()
WandExport unsigned int MagickSetCompressionQuality (MagickWand * wand, const unsigned long quality)
MagickSetFilename()
WandExport unsigned int MagickSetFilename (MagickWand * , const char *)
MagickSetFormat()
WandExport unsigned int MagickSetFormat (MagickWand * , const char *)
MagickSetImage()
WandExport unsigned int MagickSetImage (MagickWand * , const MagickWand *)
MagickSetImageAttribute()
WandExport unsigned int MagickSetImageAttribute (MagickWand * , const char * , const char *)
MagickSetImageBackgroundColor()
WandExport unsigned int MagickSetImageBackgroundColor (MagickWand * , const PixelWand *)
MagickSetImageBluePrimary()
WandExport unsigned int MagickSetImageBluePrimary (MagickWand * , const double , const double)
MagickSetImageBorderColor()
WandExport unsigned int MagickSetImageBorderColor (MagickWand * , const PixelWand *)
MagickSetImageChannelDepth()
WandExport unsigned int MagickSetImageChannelDepth (MagickWand * , const ChannelType , const unsigned long)
MagickSetImageColormapColor()
WandExport unsigned int MagickSetImageColormapColor (MagickWand * , const unsigned long , const PixelWand *)
MagickSetImageColorspace()
WandExport unsigned int MagickSetImageColorspace (MagickWand * , const ColorspaceType)
Referenced by chronos_rgb_to_grayscale().
MagickSetImageCompose()
WandExport unsigned int MagickSetImageCompose (MagickWand * , const CompositeOperator)
MagickSetImageCompression()
WandExport unsigned int MagickSetImageCompression (MagickWand * , const CompressionType)
MagickSetImageDelay()
WandExport unsigned int MagickSetImageDelay (MagickWand * , const unsigned long)
MagickSetImageDepth()
WandExport unsigned int MagickSetImageDepth (MagickWand * , const unsigned long)
MagickSetImageDispose()
WandExport unsigned int MagickSetImageDispose (MagickWand * , const DisposeType)
MagickSetImageFilename()
WandExport unsigned int MagickSetImageFilename (MagickWand * , const char *)
MagickSetImageFormat()
WandExport unsigned int MagickSetImageFormat (MagickWand * wand, const char * format)
MagickSetImageFuzz()
WandExport unsigned int MagickSetImageFuzz (MagickWand * , const double)
MagickSetImageGamma()
WandExport unsigned int MagickSetImageGamma (MagickWand * , const double)
MagickSetImageGeometry()
WandExport unsigned int MagickSetImageGeometry (MagickWand * , const char *)
MagickSetImageGravity()
WandExport unsigned int MagickSetImageGravity (MagickWand * , const GravityType)
MagickSetImageGreenPrimary()
WandExport unsigned int MagickSetImageGreenPrimary (MagickWand * , const double , const double)
MagickSetImageIndex()
WandExport unsigned int MagickSetImageIndex (MagickWand * , const long)
MagickSetImageInterlaceScheme()
WandExport unsigned int MagickSetImageInterlaceScheme (MagickWand * , const InterlaceType)
MagickSetImageIterations()
WandExport unsigned int MagickSetImageIterations (MagickWand * , const unsigned long)
MagickSetImageMatte()
WandExport unsigned int MagickSetImageMatte (MagickWand * , const unsigned int)
MagickSetImageMatteColor()
WandExport unsigned int MagickSetImageMatteColor (MagickWand * , const PixelWand *)
MagickSetImageOption()
WandExport unsigned int MagickSetImageOption (MagickWand * , const char * , const char * , const char *)
MagickSetImageOrientation()
WandExport unsigned int MagickSetImageOrientation (MagickWand * , const OrientationType)
MagickSetImagePage()
WandExport unsigned int MagickSetImagePage (MagickWand * wand, const unsigned long width, const unsigned long height, const long x, const long y)
MagickSetImagePixels()
WandExport unsigned int MagickSetImagePixels (MagickWand * , const long , const long , const unsigned long , const unsigned long , const char * , const StorageType , unsigned char *)
MagickSetImageProfile()
WandExport unsigned int MagickSetImageProfile (MagickWand * , const char * , const unsigned char * , const unsigned long)
MagickSetImageRedPrimary()
WandExport unsigned int MagickSetImageRedPrimary (MagickWand * , const double , const double)
MagickSetImageRenderingIntent()
WandExport unsigned int MagickSetImageRenderingIntent (MagickWand * , const RenderingIntent)
MagickSetImageResolution()
WandExport unsigned int MagickSetImageResolution (MagickWand * , const double , const double)
MagickSetImageSavedType()
WandExport unsigned int MagickSetImageSavedType (MagickWand * , const ImageType)
MagickSetImageScene()
WandExport unsigned int MagickSetImageScene (MagickWand * , const unsigned long)
MagickSetImageType()
WandExport unsigned int MagickSetImageType (MagickWand * , const ImageType)
MagickSetImageUnits()
WandExport unsigned int MagickSetImageUnits (MagickWand * , const ResolutionType)
MagickSetImageVirtualPixelMethod()
WandExport unsigned int MagickSetImageVirtualPixelMethod (MagickWand * , const VirtualPixelMethod)
MagickSetImageWhitePoint()
WandExport unsigned int MagickSetImageWhitePoint (MagickWand * , const double , const double)
MagickSetInterlaceScheme()
WandExport unsigned int MagickSetInterlaceScheme (MagickWand * , const InterlaceType)
MagickSetPassphrase()
WandExport unsigned int MagickSetPassphrase (MagickWand * , const char *)
MagickSetResolution()
WandExport unsigned int MagickSetResolution (MagickWand * wand, const double x_resolution, const double y_resolution)
MagickSetResolutionUnits()
WandExport unsigned int MagickSetResolutionUnits (MagickWand * wand, const ResolutionType units)
MagickSetResourceLimit()
WandExport unsigned int MagickSetResourceLimit (const ResourceType type, const unsigned long limit)
MagickSetSamplingFactors()
WandExport unsigned int MagickSetSamplingFactors (MagickWand * , const unsigned long , const double *)
MagickSetSize()
WandExport unsigned int MagickSetSize (MagickWand * , const unsigned long , const unsigned long)
MagickSharpenImage()
WandExport unsigned int MagickSharpenImage (MagickWand * , const double , const double)
MagickShaveImage()
WandExport unsigned int MagickShaveImage (MagickWand * , const unsigned long , const unsigned long)
MagickShearImage()
WandExport unsigned int MagickShearImage (MagickWand * , const PixelWand * , const double , const double)
MagickSolarizeImage()
WandExport unsigned int MagickSolarizeImage (MagickWand * , const double)
MagickSpreadImage()
WandExport unsigned int MagickSpreadImage (MagickWand * , const double)
MagickSteganoImage()
WandExport MagickWand * MagickSteganoImage (MagickWand * , const MagickWand * , const long)
MagickStereoImage()
WandExport MagickWand * MagickStereoImage (MagickWand * , const MagickWand *)
MagickStripImage()
WandExport unsigned int MagickStripImage (MagickWand *)
MagickSwirlImage()
WandExport unsigned int MagickSwirlImage (MagickWand * , const double)
MagickTextureImage()
WandExport MagickWand * MagickTextureImage (MagickWand * , const MagickWand *)
MagickThresholdImage()
WandExport unsigned int MagickThresholdImage (MagickWand * , const double)
MagickThresholdImageChannel()
WandExport unsigned int MagickThresholdImageChannel (MagickWand * , const ChannelType , const double)
MagickTintImage()
WandExport unsigned int MagickTintImage (MagickWand * , const PixelWand * , const PixelWand *)
MagickTransformImage()
WandExport MagickWand * MagickTransformImage (MagickWand * , const char * , const char *)
MagickTransparentImage()
WandExport unsigned int MagickTransparentImage (MagickWand * , const PixelWand * , const Quantum , const double)
MagickTrimImage()
WandExport unsigned int MagickTrimImage (MagickWand * , const double)
MagickUnsharpMaskImage()
WandExport unsigned int MagickUnsharpMaskImage (MagickWand * , const double , const double , const double , const double)
MagickWaveImage()
WandExport unsigned int MagickWaveImage (MagickWand * , const double , const double)
MagickWhiteThresholdImage()
WandExport unsigned int MagickWhiteThresholdImage (MagickWand * , const PixelWand *)
MagickWriteImage()
WandExport unsigned int MagickWriteImage (MagickWand * , const char *)
Referenced by chronos_rgb_to_grayscale().
MagickWriteImageBlob()
WandExport unsigned char * MagickWriteImageBlob (MagickWand * , size_t *)
MagickWriteImageFile()
WandExport unsigned int MagickWriteImageFile (MagickWand * , FILE *)
MagickWriteImages()
WandExport unsigned int MagickWriteImages (MagickWand * , const char * , const unsigned int)
MagickWriteImagesFile()
WandExport unsigned int MagickWriteImagesFile (MagickWand * , FILE * , const unsigned int)
NewMagickWand()
WandExport MagickWand * NewMagickWand (void)
Referenced by chronos_rgb_to_grayscale().