CHRONOS-LoRa: Magick Namespace Reference
Magick Namespace Reference
Classes
class Blob
class CoderInfo
class Color
class ColorGray
class ColorHSL
class ColorMono
class ColorRGB
class ColorYUV
class Coordinate
class Drawable
class DrawableAffine
class DrawableArc
class DrawableBezier
class DrawableCircle
class DrawableClipPath
class DrawableColor
class DrawableCompositeImage
class DrawableDashArray
class DrawableDashOffset
class DrawableEllipse
class DrawableFillColor
class DrawableFillOpacity
class DrawableFillRule
class DrawableFont
class DrawableGravity
class DrawableLine
class DrawableMatte
class DrawableMiterLimit
class DrawablePath
class DrawablePoint
class DrawablePointSize
class DrawablePolygon
class DrawablePolyline
class DrawablePopClipPath
class DrawablePopGraphicContext
class DrawablePopPattern
class DrawablePushClipPath
class DrawablePushGraphicContext
class DrawablePushPattern
class DrawableRectangle
class DrawableRotation
class DrawableRoundRectangle
class DrawableScaling
class DrawableSkewX
class DrawableSkewY
class DrawableStrokeAntialias
class DrawableStrokeColor
class DrawableStrokeLineCap
class DrawableStrokeLineJoin
class DrawableStrokeOpacity
class DrawableStrokeWidth
class DrawableText
class DrawableTextAntialias
class DrawableTextDecoration
class DrawableTextUnderColor
class DrawableTranslation
class DrawableViewbox
class Error
class ErrorBlob
class ErrorCache
class ErrorCoder
class ErrorConfigure
class ErrorCorruptImage
class ErrorDelegate
class ErrorDraw
class ErrorFileOpen
class ErrorImage
class ErrorMissingDelegate
class ErrorModule
class ErrorMonitor
class ErrorOption
class ErrorRegistry
class ErrorResourceLimit
class ErrorStream
class ErrorType
class ErrorUndefined
class ErrorXServer
class Exception
class Geometry
class Image
class MAGICK_UNARY_FUNCTION_DRAWCONTEXT_REF_BASE
class MAGICK_UNARY_FUNCTION_IMAGE_REF_BASE
class Montage
class MontageFramed
class PathArcAbs
class PathArcArgs
class PathArcRel
class PathClosePath
class PathCurvetoAbs
class PathCurvetoArgs
class PathCurvetoRel
class PathLinetoAbs
class PathLinetoHorizontalAbs
class PathLinetoHorizontalRel
class PathLinetoRel
class PathLinetoVerticalAbs
class PathLinetoVerticalRel
class PathMovetoAbs
class PathMovetoRel
class PathQuadraticCurvetoAbs
class PathQuadraticCurvetoArgs
class PathQuadraticCurvetoRel
class PathSmoothCurvetoAbs
class PathSmoothCurvetoRel
class PathSmoothQuadraticCurvetoAbs
class PathSmoothQuadraticCurvetoRel
class Pixels
class TypeMetric
class VPath
class VPathBase
class Warning
class WarningBlob
class WarningCache
class WarningCoder
class WarningConfigure
class WarningCorruptImage
class WarningDelegate
class WarningDraw
class WarningFileOpen
class WarningImage
class WarningMissingDelegate
class WarningModule
class WarningMonitor
class WarningOption
class WarningRegistry
class WarningResourceLimit
class WarningStream
class WarningType
class WarningUndefined
class WarningXServer
Typedefs
typedef std::list< Magick::Coordinate > CoordinateList
typedef std::list< Magick::Drawable > DrawableList
typedef std::list< Magick::VPath > VPathList
typedef std::list< Magick::PathArcArgs > PathArcArgsList
typedef std::list< Magick::PathCurvetoArgs > PathCurveToArgsList
typedef std::list< Magick::PathQuadraticCurvetoArgs > PathQuadraticCurvetoArgsList
Functions
int MagickDLLDecl operator== (const Magick::Color &left_, const Magick::Color &right_)
int MagickDLLDecl operator!= (const Magick::Color &left_, const Magick::Color &right_)
int MagickDLLDecl operator> (const Magick::Color &left_, const Magick::Color &right_)
int MagickDLLDecl operator< (const Magick::Color &left_, const Magick::Color &right_)
int MagickDLLDecl operator>= (const Magick::Color &left_, const Magick::Color &right_)
int MagickDLLDecl operator<= (const Magick::Color &left_, const Magick::Color &right_)
MagickDLLDeclExtern int operator== (const Coordinate &left_, const Coordinate &right_)
MagickDLLDeclExtern int operator!= (const Coordinate &left_, const Coordinate &right_)
MagickDLLDeclExtern int operator> (const Coordinate &left_, const Coordinate &right_)
MagickDLLDeclExtern int operator< (const Coordinate &left_, const Coordinate &right_)
MagickDLLDeclExtern int operator>= (const Coordinate &left_, const Coordinate &right_)
MagickDLLDeclExtern int operator<= (const Coordinate &left_, const Coordinate &right_)
MagickDLLDeclExtern int operator== (const Drawable &left_, const Drawable &right_)
MagickDLLDeclExtern int operator!= (const Drawable &left_, const Drawable &right_)
MagickDLLDeclExtern int operator> (const Drawable &left_, const Drawable &right_)
MagickDLLDeclExtern int operator< (const Drawable &left_, const Drawable &right_)
MagickDLLDeclExtern int operator>= (const Drawable &left_, const Drawable &right_)
MagickDLLDeclExtern int operator<= (const Drawable &left_, const Drawable &right_)
MagickDLLDeclExtern int operator== (const VPath &left_, const VPath &right_)
MagickDLLDeclExtern int operator!= (const VPath &left_, const VPath &right_)
MagickDLLDeclExtern int operator> (const VPath &left_, const VPath &right_)
MagickDLLDeclExtern int operator< (const VPath &left_, const VPath &right_)
MagickDLLDeclExtern int operator>= (const VPath &left_, const VPath &right_)
MagickDLLDeclExtern int operator<= (const VPath &left_, const VPath &right_)
MagickDLLDeclExtern int operator== (const PathArcArgs &left_, const PathArcArgs &right_)
MagickDLLDeclExtern int operator!= (const PathArcArgs &left_, const PathArcArgs &right_)
MagickDLLDeclExtern int operator> (const PathArcArgs &left_, const PathArcArgs &right_)
MagickDLLDeclExtern int operator< (const PathArcArgs &left_, const PathArcArgs &right_)
MagickDLLDeclExtern int operator>= (const PathArcArgs &left_, const PathArcArgs &right_)
MagickDLLDeclExtern int operator<= (const PathArcArgs &left_, const PathArcArgs &right_)
MagickDLLDeclExtern int operator== (const PathCurvetoArgs &left_, const PathCurvetoArgs &right_)
MagickDLLDeclExtern int operator!= (const PathCurvetoArgs &left_, const PathCurvetoArgs &right_)
MagickDLLDeclExtern int operator> (const PathCurvetoArgs &left_, const PathCurvetoArgs &right_)
MagickDLLDeclExtern int operator< (const PathCurvetoArgs &left_, const PathCurvetoArgs &right_)
MagickDLLDeclExtern int operator>= (const PathCurvetoArgs &left_, const PathCurvetoArgs &right_)
MagickDLLDeclExtern int operator<= (const PathCurvetoArgs &left_, const PathCurvetoArgs &right_)
MagickDLLDeclExtern int operator== (const PathQuadraticCurvetoArgs &left_, const PathQuadraticCurvetoArgs &right_)
MagickDLLDeclExtern int operator!= (const PathQuadraticCurvetoArgs &left_, const PathQuadraticCurvetoArgs &right_)
MagickDLLDeclExtern int operator> (const PathQuadraticCurvetoArgs &left_, const PathQuadraticCurvetoArgs &right_)
MagickDLLDeclExtern int operator< (const PathQuadraticCurvetoArgs &left_, const PathQuadraticCurvetoArgs &right_)
MagickDLLDeclExtern int operator>= (const PathQuadraticCurvetoArgs &left_, const PathQuadraticCurvetoArgs &right_)
MagickDLLDeclExtern int operator<= (const PathQuadraticCurvetoArgs &left_, const PathQuadraticCurvetoArgs &right_)
MagickDLLDeclExtern void throwExceptionExplicit (const MagickLib::ExceptionType severity_, const char *reason_, const char *description_=0)
MagickDLLDeclExtern void throwException (MagickLib::ExceptionInfo &exception_, const bool quiet_=false)
int MagickDLLDecl operator== (const Magick::Geometry &left_, const Magick::Geometry &right_)
int MagickDLLDecl operator!= (const Magick::Geometry &left_, const Magick::Geometry &right_)
int MagickDLLDecl operator> (const Magick::Geometry &left_, const Magick::Geometry &right_)
int MagickDLLDecl operator< (const Magick::Geometry &left_, const Magick::Geometry &right_)
int MagickDLLDecl operator>= (const Magick::Geometry &left_, const Magick::Geometry &right_)
int MagickDLLDecl operator<= (const Magick::Geometry &left_, const Magick::Geometry &right_)
int MagickDLLDecl operator== (const Magick::Image &left_, const Magick::Image &right_)
int MagickDLLDecl operator!= (const Magick::Image &left_, const Magick::Image &right_)
int MagickDLLDecl operator> (const Magick::Image &left_, const Magick::Image &right_)
int MagickDLLDecl operator< (const Magick::Image &left_, const Magick::Image &right_)
int MagickDLLDecl operator>= (const Magick::Image &left_, const Magick::Image &right_)
int MagickDLLDecl operator<= (const Magick::Image &left_, const Magick::Image &right_)
void MagickDLLDecl SetLogDefaultEventType (const std::string &events_)
void MagickDLLDecl SetLogDefaultGenerations (const unsigned int generations_)
void MagickDLLDecl SetLogDefaultLimit (const unsigned int limit_)
void MagickDLLDecl SetLogDefaultFileName (const std::string &filename_)
void MagickDLLDecl SetLogDefaultFormat (const std::string &format_)
void MagickDLLDecl SetLogDefaultLogMethod (const Magick::LogMethod method_)
void MagickDLLDecl SetLogDefaultOutputType (const Magick::LogOutputType output_type_)
void MagickDLLDecl InitializeMagick (const char *path_)
template<class InputIterator >
void linkImages (InputIterator first_, InputIterator last_)
template<class InputIterator >
void unlinkImages (InputIterator first_, InputIterator last_)
template<class Container >
void insertImages (Container *sequence_, MagickLib::Image *images_)
template<class InputIterator >
void animateImages (InputIterator first_, InputIterator last_)
template<class InputIterator >
void appendImages (Image *appendedImage_, InputIterator first_, InputIterator last_, bool stack_=false)
template<class InputIterator >
void averageImages (Image *averagedImage_, InputIterator first_, InputIterator last_)
template<class InputIterator , class Container >
void coalesceImages (Container *coalescedImages_, InputIterator first_, InputIterator last_)
template<class Container >
void coderInfoList (Container *container_, CoderInfo::MatchType isReadable_=CoderInfo::AnyMatch, CoderInfo::MatchType isWritable_=CoderInfo::AnyMatch, CoderInfo::MatchType isMultiFrame_=CoderInfo::AnyMatch)
template<class Container >
void colorHistogram (Container *histogram_, const Image image)
template<class InputIterator , class Container >
void deconstructImages (Container *deconstructedImages_, InputIterator first_, InputIterator last_)
template<class InputIterator >
void displayImages (InputIterator first_, InputIterator last_)
template<class InputIterator >
void flattenImages (Image *flattendImage_, InputIterator first_, InputIterator last_)
template<class InputIterator >
void mapImages (InputIterator first_, InputIterator last_, const Image &mapImage_, bool dither_=false, bool measureError_=false)
template<class Container , class InputIterator >
void montageImages (Container *montageImages_, InputIterator first_, InputIterator last_, const Montage &montageOpts_)
template<class InputIterator , class Container >
void morphImages (Container *morphedImages_, InputIterator first_, InputIterator last_, unsigned int frames_)
template<class InputIterator >
void mosaicImages (Image *mosaicImage_, InputIterator first_, InputIterator last_)
template<class InputIterator >
void quantizeImages (InputIterator first_, InputIterator last_, bool measureError_=false)
template<class Container >
void readImages (Container *sequence_, const std::string &imageSpec_)
template<class Container >
void readImages (Container *sequence_, const Blob &blob_)
template<class InputIterator >
void writeImages (InputIterator first_, InputIterator last_, const std::string &imageSpec_, bool adjoin_=true)
template<class InputIterator >
void writeImages (InputIterator first_, InputIterator last_, Blob *blob_, bool adjoin_=true)
Variables
class MagickDLLDecl Color
class MagickDLLDecl Image
class MagickDLLDecl Geometry
MagickDLLDecl const char * borderGeometryDefault
MagickDLLDecl const char * frameGeometryDefault
MagickDLLDecl const char * raiseGeometryDefault
Typedef Documentation
CoordinateList
typedef std::list<Magick::Coordinate> Magick::CoordinateList
DrawableList
typedef std::list<Magick::Drawable> Magick::DrawableList
PathArcArgsList
typedef std::list<Magick::PathArcArgs> Magick::PathArcArgsList
PathCurveToArgsList
typedef std::list<Magick::PathCurvetoArgs> Magick::PathCurveToArgsList
PathQuadraticCurvetoArgsList
typedef std::list<Magick::PathQuadraticCurvetoArgs> Magick::PathQuadraticCurvetoArgsList
VPathList
typedef std::list<Magick::VPath> Magick::VPathList
Function Documentation
animateImages()
template<class InputIterator > void Magick::animateImages (InputIterator first_, InputIterator last_)
appendImages()
template<class InputIterator > void Magick::appendImages (Image * appendedImage_, InputIterator first_, InputIterator last_, bool stack_ = false)
averageImages()
template<class InputIterator > void Magick::averageImages (Image * averagedImage_, InputIterator first_, InputIterator last_)
coalesceImages()
template<class InputIterator , class Container > void Magick::coalesceImages (Container * coalescedImages_, InputIterator first_, InputIterator last_)
coderInfoList()
template<class Container > void Magick::coderInfoList (Container * container_, CoderInfo::MatchType isReadable_ = CoderInfo::AnyMatch, CoderInfo::MatchType isWritable_ = CoderInfo::AnyMatch, CoderInfo::MatchType isMultiFrame_ = CoderInfo::AnyMatch)
colorHistogram()
template<class Container > void Magick::colorHistogram (Container * histogram_, const Image image)
deconstructImages()
template<class InputIterator , class Container > void Magick::deconstructImages (Container * deconstructedImages_, InputIterator first_, InputIterator last_)
displayImages()
template<class InputIterator > void Magick::displayImages (InputIterator first_, InputIterator last_)
flattenImages()
template<class InputIterator > void Magick::flattenImages (Image * flattendImage_, InputIterator first_, InputIterator last_)
InitializeMagick()
void MagickDLLDecl Magick::InitializeMagick (const char * path_)
insertImages()
template<class Container > void Magick::insertImages (Container * sequence_, MagickLib::Image * images_)
linkImages()
template<class InputIterator > void Magick::linkImages (InputIterator first_, InputIterator last_)
mapImages()
template<class InputIterator > void Magick::mapImages (InputIterator first_, InputIterator last_, const Image & mapImage_, bool dither_ = false, bool measureError_ = false)
montageImages()
template<class Container , class InputIterator > void Magick::montageImages (Container * montageImages_, InputIterator first_, InputIterator last_, const Montage & montageOpts_)
morphImages()
template<class InputIterator , class Container > void Magick::morphImages (Container * morphedImages_, InputIterator first_, InputIterator last_, unsigned int frames_)
mosaicImages()
template<class InputIterator > void Magick::mosaicImages (Image * mosaicImage_, InputIterator first_, InputIterator last_)
operator!=() [1/9]
MagickDLLDeclExtern int Magick::operator!= (const Coordinate & left_, const Coordinate & right_)
operator!=() [2/9]
MagickDLLDeclExtern int Magick::operator!= (const Drawable & left_, const Drawable & right_)
operator!=() [3/9]
int MagickDLLDecl Magick::operator!= (const Magick::Color & left_, const Magick::Color & right_)
operator!=() [4/9]
int MagickDLLDecl Magick::operator!= (const Magick::Geometry & left_, const Magick::Geometry & right_)
operator!=() [5/9]
int MagickDLLDecl Magick::operator!= (const Magick::Image & left_, const Magick::Image & right_)
operator!=() [6/9]
MagickDLLDeclExtern int Magick::operator!= (const PathArcArgs & left_, const PathArcArgs & right_)
operator!=() [7/9]
MagickDLLDeclExtern int Magick::operator!= (const PathCurvetoArgs & left_, const PathCurvetoArgs & right_)
operator!=() [8/9]
MagickDLLDeclExtern int Magick::operator!= (const PathQuadraticCurvetoArgs & left_, const PathQuadraticCurvetoArgs & right_)
operator!=() [9/9]
MagickDLLDeclExtern int Magick::operator!= (const VPath & left_, const VPath & right_)
operator<() [1/9]
MagickDLLDeclExtern int Magick::operator< (const Coordinate & left_, const Coordinate & right_)
operator<() [2/9]
MagickDLLDeclExtern int Magick::operator< (const Drawable & left_, const Drawable & right_)
operator<() [3/9]
int MagickDLLDecl Magick::operator< (const Magick::Color & left_, const Magick::Color & right_)
operator<() [4/9]
int MagickDLLDecl Magick::operator< (const Magick::Geometry & left_, const Magick::Geometry & right_)
operator<() [5/9]
int MagickDLLDecl Magick::operator< (const Magick::Image & left_, const Magick::Image & right_)
operator<() [6/9]
MagickDLLDeclExtern int Magick::operator< (const PathArcArgs & left_, const PathArcArgs & right_)
operator<() [7/9]
MagickDLLDeclExtern int Magick::operator< (const PathCurvetoArgs & left_, const PathCurvetoArgs & right_)
operator<() [8/9]
MagickDLLDeclExtern int Magick::operator< (const PathQuadraticCurvetoArgs & left_, const PathQuadraticCurvetoArgs & right_)
operator<() [9/9]
MagickDLLDeclExtern int Magick::operator< (const VPath & left_, const VPath & right_)
operator<=() [1/9]
MagickDLLDeclExtern int Magick::operator<= (const Coordinate & left_, const Coordinate & right_)
operator<=() [2/9]
MagickDLLDeclExtern int Magick::operator<= (const Drawable & left_, const Drawable & right_)
operator<=() [3/9]
int MagickDLLDecl Magick::operator<= (const Magick::Color & left_, const Magick::Color & right_)
operator<=() [4/9]
int MagickDLLDecl Magick::operator<= (const Magick::Geometry & left_, const Magick::Geometry & right_)
operator<=() [5/9]
int MagickDLLDecl Magick::operator<= (const Magick::Image & left_, const Magick::Image & right_)
operator<=() [6/9]
MagickDLLDeclExtern int Magick::operator<= (const PathArcArgs & left_, const PathArcArgs & right_)
operator<=() [7/9]
MagickDLLDeclExtern int Magick::operator<= (const PathCurvetoArgs & left_, const PathCurvetoArgs & right_)
operator<=() [8/9]
MagickDLLDeclExtern int Magick::operator<= (const PathQuadraticCurvetoArgs & left_, const PathQuadraticCurvetoArgs & right_)
operator<=() [9/9]
MagickDLLDeclExtern int Magick::operator<= (const VPath & left_, const VPath & right_)
operator==() [1/9]
MagickDLLDeclExtern int Magick::operator== (const Coordinate & left_, const Coordinate & right_)
operator==() [2/9]
MagickDLLDeclExtern int Magick::operator== (const Drawable & left_, const Drawable & right_)
operator==() [3/9]
int MagickDLLDecl Magick::operator== (const Magick::Color & left_, const Magick::Color & right_)
operator==() [4/9]
int MagickDLLDecl Magick::operator== (const Magick::Geometry & left_, const Magick::Geometry & right_)
operator==() [5/9]
int MagickDLLDecl Magick::operator== (const Magick::Image & left_, const Magick::Image & right_)
operator==() [6/9]
MagickDLLDeclExtern int Magick::operator== (const PathArcArgs & left_, const PathArcArgs & right_)
operator==() [7/9]
MagickDLLDeclExtern int Magick::operator== (const PathCurvetoArgs & left_, const PathCurvetoArgs & right_)
operator==() [8/9]
MagickDLLDeclExtern int Magick::operator== (const PathQuadraticCurvetoArgs & left_, const PathQuadraticCurvetoArgs & right_)
operator==() [9/9]
MagickDLLDeclExtern int Magick::operator== (const VPath & left_, const VPath & right_)
operator>() [1/9]
MagickDLLDeclExtern int Magick::operator> (const Coordinate & left_, const Coordinate & right_)
operator>() [2/9]
MagickDLLDeclExtern int Magick::operator> (const Drawable & left_, const Drawable & right_)
operator>() [3/9]
int MagickDLLDecl Magick::operator> (const Magick::Color & left_, const Magick::Color & right_)
operator>() [4/9]
int MagickDLLDecl Magick::operator> (const Magick::Geometry & left_, const Magick::Geometry & right_)
operator>() [5/9]
int MagickDLLDecl Magick::operator> (const Magick::Image & left_, const Magick::Image & right_)
operator>() [6/9]
MagickDLLDeclExtern int Magick::operator> (const PathArcArgs & left_, const PathArcArgs & right_)
operator>() [7/9]
MagickDLLDeclExtern int Magick::operator> (const PathCurvetoArgs & left_, const PathCurvetoArgs & right_)
operator>() [8/9]
MagickDLLDeclExtern int Magick::operator> (const PathQuadraticCurvetoArgs & left_, const PathQuadraticCurvetoArgs & right_)
operator>() [9/9]
MagickDLLDeclExtern int Magick::operator> (const VPath & left_, const VPath & right_)
operator>=() [1/9]
MagickDLLDeclExtern int Magick::operator>= (const Coordinate & left_, const Coordinate & right_)
operator>=() [2/9]
MagickDLLDeclExtern int Magick::operator>= (const Drawable & left_, const Drawable & right_)
operator>=() [3/9]
int MagickDLLDecl Magick::operator>= (const Magick::Color & left_, const Magick::Color & right_)
operator>=() [4/9]
int MagickDLLDecl Magick::operator>= (const Magick::Geometry & left_, const Magick::Geometry & right_)
operator>=() [5/9]
int MagickDLLDecl Magick::operator>= (const Magick::Image & left_, const Magick::Image & right_)
operator>=() [6/9]
MagickDLLDeclExtern int Magick::operator>= (const PathArcArgs & left_, const PathArcArgs & right_)
operator>=() [7/9]
MagickDLLDeclExtern int Magick::operator>= (const PathCurvetoArgs & left_, const PathCurvetoArgs & right_)
operator>=() [8/9]
MagickDLLDeclExtern int Magick::operator>= (const PathQuadraticCurvetoArgs & left_, const PathQuadraticCurvetoArgs & right_)
operator>=() [9/9]
MagickDLLDeclExtern int Magick::operator>= (const VPath & left_, const VPath & right_)
quantizeImages()
template<class InputIterator > void Magick::quantizeImages (InputIterator first_, InputIterator last_, bool measureError_ = false)
readImages() [1/2]
template<class Container > void Magick::readImages (Container * sequence_, const Blob & blob_)
readImages() [2/2]
template<class Container > void Magick::readImages (Container * sequence_, const std::string & imageSpec_)
SetLogDefaultEventType()
void MagickDLLDecl Magick::SetLogDefaultEventType (const std::string & events_)
SetLogDefaultFileName()
void MagickDLLDecl Magick::SetLogDefaultFileName (const std::string & filename_)
SetLogDefaultFormat()
void MagickDLLDecl Magick::SetLogDefaultFormat (const std::string & format_)
SetLogDefaultGenerations()
void MagickDLLDecl Magick::SetLogDefaultGenerations (const unsigned int generations_)
SetLogDefaultLimit()
void MagickDLLDecl Magick::SetLogDefaultLimit (const unsigned int limit_)
SetLogDefaultLogMethod()
void MagickDLLDecl Magick::SetLogDefaultLogMethod (const Magick::LogMethod method_)
SetLogDefaultOutputType()
void MagickDLLDecl Magick::SetLogDefaultOutputType (const Magick::LogOutputType output_type_)
throwException()
MagickDLLDeclExtern void Magick::throwException (MagickLib::ExceptionInfo & exception_, const bool quiet_ = false)
Referenced by coderInfoList(), readImages(), and readImages().
throwExceptionExplicit()
MagickDLLDeclExtern void Magick::throwExceptionExplicit (const MagickLib::ExceptionType severity_, const char * reason_, const char * description_ = 0)
Referenced by coderInfoList().
unlinkImages()
template<class InputIterator > void Magick::unlinkImages (InputIterator first_, InputIterator last_)
writeImages() [1/2]
template<class InputIterator > void Magick::writeImages (InputIterator first_, InputIterator last_, Blob * blob_, bool adjoin_ = true)
writeImages() [2/2]
template<class InputIterator > void Magick::writeImages (InputIterator first_, InputIterator last_, const std::string & imageSpec_, bool adjoin_ = true)
Variable Documentation
borderGeometryDefault
MagickDLLDecl const char* Magick::borderGeometryDefault extern
Color
class MagickDLLDecl Magick::Color
frameGeometryDefault
MagickDLLDecl const char* Magick::frameGeometryDefault extern
Geometry
class MagickDLLDecl Magick::Geometry
Image
class MagickDLLDecl Magick::Image
raiseGeometryDefault
MagickDLLDecl const char* Magick::raiseGeometryDefault extern