CHRONOS-LoRa: detail::color_type Struct Reference
detail::color_type Struct Reference
#include <color.h>
Public Member Functions
constexpr color_type () noexcept=default
constexpr color_type (color rgb_color) noexcept
constexpr color_type (rgb rgb_color) noexcept
constexpr color_type (terminal_color term_color) noexcept
constexpr auto is_terminal_color () const noexcept -> bool
constexpr auto value () const noexcept -> uint32_t
constexpr color_type (uint32_t value) noexcept
Public Attributes
uint32_t value_ = 0
Constructor & Destructor Documentation
color_type() [1/5]
constexpr detail::color_type::color_type () constexpr default noexcept
color_type() [2/5]
constexpr detail::color_type::color_type (color rgb_color) inline constexpr noexcept
Referenced by color_type().
color_type() [3/5]
constexpr detail::color_type::color_type (rgb rgb_color) inline constexpr noexcept
color_type() [4/5]
constexpr detail::color_type::color_type (terminal_color term_color) inline constexpr noexcept
color_type() [5/5]
constexpr detail::color_type::color_type (uint32_t value) inline constexpr noexcept
Member Function Documentation
is_terminal_color()
constexpr auto detail::color_type::is_terminal_color () const -> bool inline constexpr noexcept
Referenced by detail::ansi_color_escape< Char >::ansi_color_escape().
value()
constexpr auto detail::color_type::value () const -> uint32_t inline constexpr noexcept
Referenced by detail::ansi_color_escape< Char >::ansi_color_escape().
Member Data Documentation
value_
uint32_t detail::color_type::value_ = 0
Referenced by color_type(), color_type(), color_type(), is_terminal_color(), and value().
The documentation for this struct was generated from the following file:
thirdparty/fmt/include/fmt/color.h